### ISSUE TITLE
dht: get rid of timing functions in favor of using the scheduler

### ISSUE THREAD

**Issue by sim590** [savoirfairelinux/opendht#112]
Before the Network Engine (#52),  the design implied to use functions that would check the time had come to do some operations. But since, we've implemented a Scheduler which lets us time operations for the network engine. The time has come to do the same for the rest of the DHT operations which are not yet timed using the scheduler. Among the timing functions, there are:

- `SearchNode::canGet`
- `SearchNode::getAnnounceTime`
- `Search::getNextStepTime`
- `Search::getUpdateTime`
- `Search::getAnnounceTime`
- `Search::getListenTime`

*This issue is meant to be a discussion thread for exploring what we can do for achieving this goal. It is not yet defined how far we can go with using the scheduler. It is also suggested that the `Scheduler` may require enhancements.*

**Comment by aberaud** [comment]
ok

**Comment by yomgui1** [comment]
nice

**Comment by sim590** [comment]
I think this issue was a bubble in my head that exploded and now that I look at it again, I think that it cannot be done. We will always need `SearchNode::canGet`, `Search::getNextStepTime`, etc. `Scheduler` needs to know when to schedule and that's what such functions as `getNextStepTime` are for.

Meh. Closing this until some idea linked to this comes to the mind of anyone.
