### ISSUE TITLE
Current maximum values per hash implementation may be a problem for the PHT

### ISSUE THREAD

**Issue by sim590** [savoirfairelinux/opendht#118]
## The PHT problem

While analysing #116, a problem has been raised. We could imagine the scenario where an application indexes the same value over and over and, eventually passes by the cap of 1024 values allowed by the DHT layer. As it is right now, the PHT node would not split since it counts a total of 1 value as they're all the same.

Then, if the application would go on by indexing periodically the same value each time with an interval of time less than the expiration time of the value, the pht would never grow and no indexation will be possible on that tree.
## It extends to the DHT

The problem is not limited to the use of PHT. While this problem is less likely to happen by the simple use of the DHT, the problem we face on the PHT layer is actually due to a limitation enforced by the DHT. This limitation is the number of values per hash.
## Solution

Instead of having a cap of values per hash, the DHT node could limit the number of values per IP. Furthermore, a mechanism replacing oldest values by the newest announced by a same IP could make things even better. This would eliminate the majority of cases where the PHT could be blocked by the cap of values.

**Comment by aberaud** [comment]
the issue goes wider than the PHT, but the problem should be mitigated by the per-IP storage ratio.
