### ISSUE TITLE
put finished with failure, why?

### ISSUE THREAD

**Issue by hfmanly** [savoirfairelinux/opendht#12]
My code(a little change of the Example ):
```c++
#include <opendht.h>
#include <vector>

#include <unistd.h>

#include <iostream>
using namespace std;

int main()
{
    dht::DhtRunner node;

    // Launch a dht node on a new thread, using a
    // generated RSA key pair, and listen on port 4222.
    node.run(4222, dht::crypto::generateIdentity(), true);

    // Join the network through any running node,
    // here using a known bootstrap node.
	
	node.bootstrap("bootstrap.ring.cx", "4222");
    //node.bootstrap("192.95.9.63", "4222");
	 //node.bootstrap("192.168.109.127", "4222");

    // put some data on the dht
    std::vector<uint8_t> some_data;//(5, 10);
	std::vector<uint8_t>::iterator iter = some_data.begin();
	uint8_t j = 0x31;
	for(; j < 0x39; j++ ) 
	{ 		
      //cout << j << endl;
      some_data.push_back( j );
    }

	auto hfkey1 = dht::InfoHash::get("testDHT_first_hello");
	auto hfkey2 = dht::InfoHash::get("testDHT_first_hello");
	cout <<hfkey1 <<endl;
	cout <<hfkey2 <<endl;
    node.put(hfkey1, some_data,[](bool success) {
        std::cout << "put finished with " << (success ? "success" : "failure") << std::endl;
    });

    // put some data on the dht, signed with our generated private key
    //node.putSigned("unique_key_42", some_data);

    // get data from the dht
    node.get(hfkey1, [](const std::vector<std::shared_ptr<dht::Value>>& values) {
        // Callback called when values are found
        for (const auto& value : values)
            std::cout << "Found value: " << *value << std::endl;
        return true; // return false to stop the search
    },
	[](bool success) {
        std::cout << "Get finished with " << (success ? "success" : "failure") << std::endl;
    }	
	);

    // here we could wait for some operations to complete
    // instead of ending now.

    int k = 0;
	for(; k < 661; k++)
	{		
		std::cout << "k =  " << k << endl;
        int m = 0;
		for(; m < 661; m++)
	    {
			int a = 20 + 21;
		//sleep(1);
		//std::cout << "for k =  " << k << endl;
	   }

	}

    //sleep(20);

    // wait for dht threads to end
    node.join();

    return 0;
}
```

It prints :
put finished with failure
Get finished with failure

I have tested the tools of opendht:
root@ubuntu:/home/hf/hfdht/opendht/tools# ./dhtnode -p 4222 -b bootstrap.ring.cx
Bootstrap: bootstrap.ring.cx:4222
OpenDht node 269aee6d81cfbb89ea2399706a7fd5fbfec3e452 running on port 4222
 (type 'h' or 'help' for a list of possible commands)

>> p 6f24cdd519c445d30bfdc4f8039228985355f5a2 testDHT_first_hello
>> g 6f24cdd519c445d30bfdc4f8039228985355f5a2
>> Put: failure (took 8.12075s)
Get: failure (took 0.000443155s)

BTY ,my system:
uname -a
Linux ubuntu 3.16.0-29-generic #39-Ubuntu SMP Mon Dec 15 22:27:29 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
and ufw is disable
why?

thanks

**Comment by aberaud** [comment]
Hello and thanks for reporting this bug.

When bootstrap() was called, the script was continuing but haven't received any reply yet. At that point routing tables are empty so every operation failed immediately.

In v2 (now merged to master), we wait for the dht to know at least another node before starting to process operations. That should solve your issue. Note that you should still do something like sleep or cv.wait to give a change for ops to complete before ending the program.
