### ISSUE TITLE
OSX won't allow a larger datagram size than 9216 bytes

### ISSUE THREAD

**Issue by aberaud** [savoirfairelinux/opendht#135]
Ring account export wasn't working on OS X.
After investigation is seems related to:
https://github.com/BanTheRewind/Cinder-Asio/issues/9#issuecomment-67540675

**Comment by aberaud** [comment]
Drop OS X support ?

**Comment by sim590** [comment]
Since this issue is assigned to me, I pronounce the support for OSX now dropped.

**Comment by aberaud** [comment]
The hidden message was: is your TCP patch ready soon ? :-P
