### ISSUE TITLE
Unable to build python bindings

### ISSUE THREAD

**Issue by zorun** [savoirfairelinux/opendht#15]
The python bindings do not build on my system.  I am using Archlinux, with Python 3.4.3 and Cython 0.22.1.

Here is the compilation log of the failure:

<pre>
Making all in python
make[2]: Entering directory '/tmp/opendht/python'
LDFLAGS="-L../src/.libs" /usr/bin/python setup.py build_ext --inplace
running build_ext
building 'opendht' extension
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -march=x86-64 -mtune=generic -O2 -pipe -fstack-protector-strong --param=ssp-buffer-size=4 -D_FORTIFY_SOURCE=2 -fPIC -I../../include -I/usr/include/python3.4m -c opendht.cpp -o build/temp.linux-x86_64-3.4/opendht.o -std=c++11
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
opendht.cpp:532:25: error: ‘Config’ in ‘class dht::DhtRunner’ does not name a type
 typedef dht::DhtRunner::Config __pyx_t_11opendht_cpp_Config;
                         ^
opendht.cpp:687:3: error: ‘__pyx_t_11opendht_cpp_Config’ does not name a type
   __pyx_t_11opendht_cpp_Config _config;
   ^
opendht.cpp: In function ‘PyObject* __pyx_pf_7opendht_8InfoHash_16getRandom()’:
opendht.cpp:2592:26: error: ‘getRandom’ is not a member of ‘dht::InfoHash’
   __pyx_v_h->_infohash = dht::InfoHash::getRandom();
                          ^
opendht.cpp: In function ‘PyObject* __pyx_pf_7opendht_4Node_4isExpired(__pyx_obj_7opendht_Node*)’:
opendht.cpp:2811:74: error: no matching function for call to ‘dht::Node::isExpired()’
 _t_1 = __Pyx_PyBool_FromLong(__pyx_v_self->_node.get()->isExpired()); if (unl
                                                                   ^
opendht.cpp:379:36: note: in definition of macro ‘__Pyx_PyBool_FromLong’
 #define __Pyx_PyBool_FromLong(b) ((b) ? (Py_INCREF(Py_True), Py_True) : (Py_I
                                    ^
In file included from opendht.cpp:296:0:
/usr/include/opendht/dht.h:78:10: note: candidate: bool dht::Node::isExpired(dht::time_point) const
     bool isExpired(time_point now) const;
          ^
/usr/include/opendht/dht.h:78:10: note:   candidate expects 1 argument, 0 provided
opendht.cpp: In function ‘int __pyx_pf_7opendht_9DhtConfig___init__(__pyx_obj_7opendht_DhtConfig*)’:
opendht.cpp:4637:3: error: ‘__pyx_t_11opendht_cpp_Config’ was not declared in this scope
   __pyx_t_11opendht_cpp_Config __pyx_t_1;
   ^
opendht.cpp:4651:5: error: ‘__pyx_t_1’ was not declared in this scope
     __pyx_t_1 = __pyx_t_11opendht_cpp_Config();
     ^
opendht.cpp:4656:17: error: ‘struct __pyx_obj_7opendht_DhtConfig’ has no member named ‘_config’
   __pyx_v_self->_config = __pyx_t_1;
                 ^
opendht.cpp:4656:27: error: ‘__pyx_t_1’ was not declared in this scope
   __pyx_v_self->_config = __pyx_t_1;
                           ^
opendht.cpp:4665:17: error: ‘struct __pyx_obj_7opendht_DhtConfig’ has no member named ‘_config’
   __pyx_v_self->_config.threaded = 1;
                 ^
opendht.cpp: In function ‘PyObject* __pyx_pf_7opendht_9DhtConfig_2setIdentity(__pyx_obj_7opendht_DhtConfig*, __pyx_obj_7opendht_Identity*)’:
opendht.cpp:4729:17: error: ‘struct __pyx_obj_7opendht_DhtConfig’ has no member named ‘_config’
   __pyx_v_self->_config.dht_config.id = __pyx_t_1;
                 ^
opendht.cpp: In function ‘PyObject* __pyx_pf_7opendht_9DhtConfig_4setBootstrapMode(__pyx_obj_7opendht_DhtConfig*, bool)’:
opendht.cpp:4792:17: error: ‘struct __pyx_obj_7opendht_DhtConfig’ has no member named ‘_config’
   __pyx_v_self->_config.dht_config.node_config.is_bootstrap = __pyx_v_bootstr
                 ^
opendht.cpp: In function ‘PyObject* __pyx_pf_7opendht_9DhtRunner_8run(__pyx_obj_7opendht_DhtRunner*, __pyx_obj_7opendht_Identity*, PyObject*, __pyx_t_11opendht_cpp_in_port_t, PyObject*, PyObject*)’:
opendht.cpp:5391:81: error: ‘struct __pyx_obj_7opendht_DhtConfig’ has no member named ‘_config’
 self->thisptr->run(__pyx_t_7, __pyx_t_8, __pyx_t_9, __pyx_v_config->_config);
                                                                     ^
opendht.cpp:5406:62: error: ‘struct __pyx_obj_7opendht_DhtConfig’ has no member named ‘_config’
     __pyx_v_self->thisptr->run(__pyx_v_port, __pyx_v_config->_config);
                                                              ^
opendht.cpp: In function ‘PyObject* __pyx_tp_new_7opendht_DhtConfig(PyTypeObject*, PyObject*, PyObject*)’:
opendht.cpp:7576:19: error: ‘struct __pyx_obj_7opendht_DhtConfig’ has no member named ‘_config’
   new((void*)&(p->_config)) __pyx_t_11opendht_cpp_Config();
                   ^
opendht.cpp:7576:29: error: expected type-specifier before ‘__pyx_t_11opendht_cpp_Config’
   new((void*)&(p->_config)) __pyx_t_11opendht_cpp_Config();
                             ^
opendht.cpp: In function ‘void __pyx_tp_dealloc_7opendht_DhtConfig(PyObject*)’:
opendht.cpp:7587:29: error: ‘struct __pyx_obj_7opendht_DhtConfig’ has no member named ‘_config’
   __Pyx_call_destructor(&p->_config);
                             ^
error: command 'gcc' failed with exit status 1
Makefile:466: recipe for target 'pybuild.stamp' failed
make[2]: *** [pybuild.stamp] Error 1
make[2]: Leaving directory '/tmp/opendht/python'
Makefile:491: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/tmp/opendht'
Makefile:400: recipe for target 'all' failed
make: *** [all] Error 2
</pre>

**Comment by zorun** [comment]
If that's any help, here is the output of `./configure` related to python:

<pre>
checking for a Python interpreter with version >= 3.3... python
checking for python... /usr/bin/python
checking for python version... 3.4
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.4/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.4/site-packages
checking for cython... cython
</pre>

**Comment by aberaud** [comment]
Hello and thanks for the report.
There currently is an issue that makes the python binding use the system-installed OpenDHT instead of the parent directory, reading the log it seems you have an old version installed.

If you just pulled the latest master, first rebuild the library (with --disable-python) and install it system-wide (make install), then rebuild with the python binding enabled.

I will keep the bug open while this issue remains.

**Comment by aberaud** [comment]
Fixed by https://github.com/savoirfairelinux/opendht/commit/a31bd73a6d228658cb40d4d7d6b1db4ee297903e

**Comment by kaldoran** [comment]
Hi,
Since this issue is resolved 5 months ago, are you going to update the PKGBUILD on archlinux AUR ?
Thanks 
Link : https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=opendht

**Comment by zorun** [comment]
Please use the AUR comment system, as your question is unrelated to upstream: https://aur.archlinux.org/packages/opendht
