### ISSUE TITLE
Question: OpenDHT under NAT

### ISSUE THREAD

**Issue by paulobrizolara** [savoirfairelinux/opendht#151]
Hello!

I am learning about `opendht` and trying to understand if i can use it under NAT.
I dig around the wiki and code, but did not find anything.
So, my specific questions:

1) If a node in running under NAT, it is possible to it join the DHT (do queries and publish content).
2) After joining the DHT, it is possible to two nodes under different NAT establish a direct connection?
3) If it is not possible, what can we do to handle those cases? What libraries can you recommend to handle NAT traversal?

Thanks to all!

P.s.: i know there are different types of NAT and some (i believe) cannot be directly traversed (Symmetric NATs, i think). So, i am more interested in the cases that is possible to traverse NAT.

**Comment by sim590** [comment]
Hi @paulobrizolara.

> 1) If a node in running under NAT, it is possible to it join the DHT (do queries and publish content).

Yes. A node behind a NAT will issue outgoing requests to non-NATed nodes and will success to get response from them like you can access a web page from a non-NATed web server while you are NATed.

 > 2) After joining the DHT, it is possible to two nodes under different NAT establish a direct connection?

You can use OpenDHT to establish a "rendez-vous" point (using a same *hash*) between two peers (NATed or not) and use that "rendez-vous" point to exchange data. After this, it comes down to the usual problem of punching though NAT. There are ways to do this, but this is not supported by OpenDHT. 

> 3) If it is not possible, what can we do to handle those cases? What libraries can you recommend to handle NAT traversal?

For e.g, [Ring][] uses OpenDHT to exchange [ICE][] candidates (IP address candidates). Then, both peers have to figure out together if they can open ports from one side or the other by using [NATPMP][].

If you want to find out more, I suggest you give a look at [Ring source code][] at https://gerrit-ring.savoirfairelinux.com/.

Cheers!

[Ring]: https://ring.cx
[Ring source code]: https://gerrit-ring.savoirfairelinux.com/
[ICE]: https://en.wikipedia.org/wiki/Interactive_Connectivity_Establishment
[NATPMP]: https://en.wikipedia.org/wiki/NAT_Port_Mapping_Protocol

**Comment by aberaud** [comment]
Very good answer @sim590 . @paulobrizolara Ring makes use of [PJNATH](http://www.pjsip.org/pjnath/docs/html/) to go through NATs by performing an ICE negotiation, after exchanging encrypted ICE descriptors using OpenDHT.

**Comment by paulobrizolara** [comment]
Very nice!
Thanks @sim590 !
I will take a look at the Ring source code!

**Comment by Lanius-collaris** [comment]
> Where does this source code live nowadays?

https://git.jami.net/savoirfairelinux/jami-daemon
