### ISSUE TITLE
[Question] Value expiration

### ISSUE THREAD

**Issue by imadari** [savoirfairelinux/opendht#162]
I have two dht nodes on two machines (call them odhtput and odhtget). Odhtput adds one key and few values, odhtget is polling the the same key and writes the values out to the consol (odhtget).

From the opendht source code I suspect that the values default duration is 10 minutes. However after 10 minutes the odhtget still gives back the (expired) values.

How the value expiration should work?

I tried to create my own ValueType with one minute expiration, but I experienced the same issue. The values are returned by the get() for few more minutes after the expiration.

**Comment by sim590** [comment]
> From the opendht source code I suspect that the values default duration is 10 minutes. However after 10 minutes the odhtget still gives back the (expired) values.

That's correct. Default expiration time is in fact 10 minutes (for `ValueType` set to `USER_DATA`).

> How the value expiration should work?

Values should normally be erased after having expired. Can you explain a little bit more about the test you have done. Were you using only two nodes as the whole network? Did you rather bootstrap your nodes from the main network? Either way, this doesn't sound right. I will write a note about it and update when I have news.

> I tried to create my own ValueType with one minute expiration, but I experienced the same issue. The values are returned by the get() for few more minutes after the expiration.

Judging by this ^, I suspect that you were bootstrapped on a bigger network than the nodes you own as the behavior you have noticed is in fact expected. Nodes that don't know the custom ValueType you have created will just default it to `USER_DATA`.

**Comment by sim590** [comment]
Did you set the bool `permanent` as `true` in your `DhtRunner::put` call?

**Comment by imadari** [comment]
In my test case I had two executable: `odhtget` and `odhtput`. `odhtget` reads a specific key in every fifth second:
```
while(!zsys_interrupted){
        dhtNode.get(key,
            [](const std::vector<std::shared_ptr<dht::Value>>& values) {
                if (values.size()>0){
                    for (const auto& v : values) {
                        std::string result = std::string(v->data.begin(), v->data.end());
                        std::cout << result << "; ";
                    }
                    std::cout << std::endl;
                }
                else {
                    std::cout << "No results " << std::endl;
                }
                return true;
            }//,
            //[](bool success) {
            //    std::cout << "Get finished with " << (success ? "success" : "failure") << std::endl;
            //}
            );
         
        std::cout << "Zzzz..." << std::endl;
        sleep(5);
    }
```

`odhtput` saves a value in every second (for 40 seconds), and runs a query in every fifth second:

```
while(!zsys_interrupted){
        sleep(1);
        
        if (counter%5 == 0){
            dhtNode.get(key,
                [](const std::vector<std::shared_ptr<dht::Value>>& values) {
                    
                    if (values.size()>0){
                        for (const auto& v : values) {
                            std::string result = std::string(v->data.begin(), v->data.end());
                            std::cout << v << "; ";
                        }
                        std::cout << std::endl;
                    }
                    else {
                        std::cout << "No results " << std::endl;
                    }
                    return true;
                },
                [](bool success) {
                    std::cout << "Get finished with " << (success ? "success" : "failure") << std::endl;
                }
                );
        }

        if (counter++<40){
            std::string d = std::string("D") + std::to_string(counter);
            std::vector<uint8_t> o(d.begin(), d.end());
            dht::time_point now = std::chrono::steady_clock::now();
            dhtNode.put(keyhash, dht::Value(vt, o), [](bool success){}, now);
        }

    }

```

So what I experienced: after 10 minutes, the queries still returned the values, but if I waited few more minutes (~3-4 mins), the values are disappeared.

I called the bootstrap only in the `odhtget`:

```
dht::DhtRunner dhtNode;
dhtNode.run(ODHT_PORT, {}, true);
dhtNode.bootstrap(target, std::to_string(ODHT_PORT));
```

In the `odhtput`, I just run the node without calling the bootstrap:

```
 dht::DhtRunner dhtNode;
 dhtNode.run(ODHT_PORT, {}, true);
```

**Comment by imadari** [comment]
I haven't tried to set the `permanent`.

**Comment by imadari** [comment]
I've pushed my tests [here](https://bitbucket.org/istvan_madari/opendhttest/src)

**Comment by sim590** [comment]
Expired values are cleared every 4 minutes in average (see the [code](https://github.com/savoirfairelinux/opendht/blob/master/src/dht.cpp#L2978)), hence the delay you have noticed.

This will surely change in the near future as we can easily schedule clearing value at value expiration (per value) using our internal scheduler tool.
