### ISSUE TITLE
AnnounceValue design

### ISSUE THREAD

**Issue by manuels** [savoirfairelinux/opendht#171]
I have a question about the design of [sendAnnounceValue()](https://github.com/savoirfairelinux/opendht/blob/ac65ca51775b6882b8f96470a5ec5cd128846ecf/src/network_engine.cpp#L1103):

Apparently the function send out first header message and then several messages with chunks of the value. Is this correct?
If so, how are the properties of the underlying transportation layer (UDP) accounted for? Especially, how do you take into account that the header or one of the chunks is not lost? How do you account for mis-ordered packets?

**Comment by aberaud** [comment]
Hi,
There is a basic retransmission system that will retransmit the whole thing if no ack is received after 1 second, up to 2 times (total 3 transmissions max). For now mis-ordered packets will cause one transmission failure (it's a implementation detail, the protocol has enough info to handle those).
Note the goal isn't to achieve TCP-style data streaming but to allow punctual transmission of small values (up to 64k) while staying bellow the MTU (around 1500 bytes).

**Comment by manuels** [comment]
Ok, thanks for clarification!
