### ISSUE TITLE
python: backward compatibility issue

### ISSUE THREAD

**Issue by sim590** [savoirfairelinux/opendht#180]
The whole benchmark is broken by 768bfa5d444bab566d7c0721200678d89bd226f1 since the `SockAddr` is not used by the benchmark and [no "legacy" signature (with address as string) is still available in the python API for bootstraping][legacy-bootstrap] :unamused:.

This is the case for benchmark, but also all python code which have already been written before 768bfa5d444bab566d7c0721200678d89bd226f1. For instance, the [pingpong][] script is broken. I think that some of ring's dht small swarm is using python bindings also. This is dangerous.

This kind of changes should be made more carefuly in the future since we never know who may use the python bindings also and we don't want to just drop support for API as fundamental as `DhtRunner.bootstrap`. I suggest, a legacy signature should be provided. If we want to deprecate it, then we could add a message on standard error specifying the matter, but anyhow I don't think it's good idea to remove this signature before a long time (couple of weeks or months).

[legacy-bootstrap]: https://github.com/savoirfairelinux/opendht/commit/768bfa5d444bab566d7c0721200678d89bd226f1#diff-46374efcb7905f7cd6ed62f3c1310dc6L287
[pingpong]: https://github.com/savoirfairelinux/opendht/blob/4540be7460d3760b32c2ffbe2b0826cd1da6314b/python/tools/pingpong.py#L30

**Comment by aberaud** [comment]
it's a bug, this is exactly the kind of things that will be detected automatically with unit tests

**Comment by sim590** [comment]
Oh. I just noticed that you in fact [kept the legacy signature available][legacy]. I didn't look close enough at first. So, yeah, like you say, this is a bug ;)

[legacy]: https://jenkins.ring.cx/job/daemon-ubuntu/384/consoleFull

**Comment by aberaud** [comment]
Fixed by 99f8c2950b4c1d4af8e668e3d6ed317683924005

**Comment by sim590** [comment]
@aberaud: But now, the bootstrap signature `bootstrap(string, string)` is not present anymore which was in part what I was complaining about. Don't you think that this canonical signature should always be available?

**Comment by aberaud** [comment]
I think `bootstrap(string, string)` was always present (as you noticed above) and still is, but was not working because of a conflict with the now-removed signature.

**Comment by sim590** [comment]
@aberaud. I really have trouble reading github's diffs.
