### ISSUE TITLE
Are there any C wrapper of opendht?

### ISSUE THREAD

**Issue by amirouche** [savoirfairelinux/opendht#181]
I'd like to create bindings for GNU Guile of opendht. To be able to do that, I need C wrappers. Does any exists? Or I need to write them?

**Comment by sim590** [comment]
Hi @amirouche. Unfortunately, there is no C wrappers written at the moment. We would be glad to receive contribution on this matter as we have not thought writing that any time soon and I'm sure that a couple of C projects could benifit from this.

**Comment by amirouche** [comment]
I will need some help regarding the Makefiles (or is it cmake). Can someone bootstrap the c wrappers project by adding the correct automake incantation and make a PR to [my fork](https://github.com/amirouche/opendht/)? Or maybe explain to me how I should do it.

Thanks!

**Comment by aberaud** [comment]
I did a very basic wrapper to be extended https://github.com/amirouche/opendht/pull/1

**Comment by AmarOk1412** [comment]
And updated a lot since (https://github.com/savoirfairelinux/opendht/tree/master/c) @aberaud I think you can close :)

**Comment by ghenry** [comment]
Closing. Thanks for the pointer @AmarOk1412
