### ISSUE TITLE
test_bootstrap doesn't work on mac

### ISSUE THREAD

**Issue by ChristopheMotte** [savoirfairelinux/opendht#188]
Hello guys, 
it seems that some recent changes make _test_bootstrap_ (in opendht_tests) fail.
I saw that you worked on bootstrap signature and SockAddr recently but can't manage to see how to make the test pass again.
Can you run it and tell me if you see the same issue?

I spent hours trying to figure it out myself,  I'm kind of lost...  :)

**Comment by ChristopheMotte** [comment]
I think I found the explanation to my problem, I understand I have to use ping() instead of bootstrap() to bootstrap two nodes, am I right? It seems to work.

Anyway there is still a problem on mac, where ping()(still in python api) returns false when trying to boostrap two simple nodes.

**Comment by aberaud** [comment]
Cool the tests already found a bug !
