### ISSUE TITLE
opendht should depend on gnutls-3.4.1 or higher

### ISSUE THREAD

**Issue by stefan-langenmaier** [savoirfairelinux/opendht#189]
The symbol GNUTLS_KEYID_USE_SHA256 is only available in gnutls-3.4.1 and higher.

**Comment by sim590** [comment]
Thank you! We have been adding this recently.

@aberaud: Are there any other symbols recently added that are subject to influencing such dependency numbers?

**Comment by aberaud** [comment]
should be fixed by 79e266aac674a85bfd60cd4d338c46d25c0a2856
