### ISSUE TITLE
python api:  ping() deadlock

### ISSUE THREAD

**Issue by ChristopheMotte** [savoirfairelinux/opendht#193]
Hello, while writing a unittest for the ping() function, I tried to ping a running node from a non-running node like this:

import opendht as dht
a = dht.DhtRunner()
a.run()
b = dht.DhtRunner()
b.ping(a.getBound())

and it gets stuck

is it a normal behaviour?

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by aberaud** [comment]
Fixed in latest versions
