### ISSUE TITLE
python api: a node is still running after calling shutdown()

### ISSUE THREAD

**Issue by ChristopheMotte** [savoirfairelinux/opendht#194]
Hello, I'm trying to test the shutdown() function in python api, I'm trying this in ipython:

>>> import opendht as dht
>>> a = dht.DhtRunner()
>>> a.isRunning()
False
>>> a.run()
>>> a.isRunning()
True
>>> a.shutdown()
>>> a.isRunning()
True

is it the normal behaviour?

**Comment by sim590** [comment]
> is it the normal behaviour?

Yes. If you take a look at the API (`dhtrunner.cpp`), you should notice that the shutdown function doesn't do exactly what it may sound like. It just calls some final instructions before really "shutting down". You have to call `join` afterwards.

In fact, for semantic purposes, I really think that shutdown should call `join`, but may be @aberaud can give his opinion on this?

**Comment by ChristopheMotte** [comment]
Ok thanks!

**Comment by ChristopheMotte** [comment]
Speaking of semantic, I don't understand exactly why the second function is called "join"?

**Comment by ChristopheMotte** [comment]
There is still something I'm not sure about, in DhtRunner.h, the comment says that shutdown() disconnects the node from the network. Should I still be able to ping it afterwards? Right now we still can.

**Comment by sim590** [comment]
@ChristopheMotte. According to what we decided to make the function do, then yes you should. However, as I said earlier, I think the more logical thing is not to, hence the `shutdown` function should call `join` IMO.

**Comment by kaldoran** [comment]
Even if I'm not mention in that review I will give mine ^^
Since the name is shutdown, it should .. shutdown, and so call join instead of leaving this action to the user.

**Comment by aberaud** [comment]
`join()` comes from the POSIX threading world. It means that the current thread will wait for other threads/process forks to end before continuing.

Indeed this term might not be clear/relevent in this scenario, we shall find a better name. What about simply `stop()` ?

I agree that `shutdown()` should perform all steps to put the node back to it's original state so run() can then be called again.
Currently, after shutdown(), the node it in an unspecified state.

**Comment by sim590** [comment]
@kaldoran don't bother being mentionned. You are welcome to comment anytime as everyone is! :wink:

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.
