### ISSUE TITLE
Persistence, removing values and expiration times

### ISSUE THREAD

**Issue by GrossoMoreira** [savoirfairelinux/opendht#196]
Hi,

I'm trying to use opendht in a system that needs to store values which lifetimes should be longer than just a few minutes. I've been trying to figure out a way to do this but it seems that the values that I put in the dht keep expiring. I could try to put the values using 'permanent' as True, but I don't want values to stay there forever, and I don't see a way to delete them either.

In dht.h there's a comment saying:
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/**
     * Listen on the network for any changes involving a specified hash.
     * The node will register to receive updates from relevent nodes when
     * new values are added or removed.
     *
     * @return a token to cancel the listener later.
     */
    virtual size_t listen(const InfoHash&, GetCallback, Value::Filter&&={}, Where&& w = {});
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

So I made a test where a node puts a value and another node listens to that value. When the value is put, the listening node is notified, but when the value eventually expires, the listening node is never notified.

Is it even possible to remove values? If so, how? If not, am I supposed to put the same value again and again, every time it expires, until I don't want it anymore? How do I know it expired?

Thanks in advance for the input!

Best regards,
-Pedro Moreira

**Comment by sim590** [comment]
> So I made a test where a node puts a value and another node listens to that value. When the value is put, the listening node is notified, but when the value eventually expires, the listening node is never notified.

Actually, the part "or removed" should be removed :wink: from the comment since it's not true. This comment is from 2014, i.e. when the project was in its debut.

> Is it even possible to remove values? If so, how? If not, am I supposed to put the same value again and again, every time it expires, until I don't want it anymore? How do I know it expired?

In fact, you cannot remove values. They expire on their own either in a deterministic way or by result of churn. Indeed, you then have to put values over and over again until you don't want it anymore, that's what the flag `permanent` is for. Effectively, the `permanent` flag may have misleading name, however it is accurate if you view it from the point of view of a single node and not considering the whole network.

**Comment by sim590** [comment]
Regarding my comment where I say:

> They expire on their own either in a deterministic way or by result of churn.

The latter will not be true in the future. In fact, there is a feature of "data persistence" trying to cancel out the effect of churn on storage. It is turned off for now for performance issues. However, in long term, it should be turned on.

**Comment by GrossoMoreira** [comment]
Ok, thanks

**Comment by aberaud** [comment]
Note that data persistence can be enabled by using the maintain_storage flag in the configuration
```c++
dhtRunner->run(4222, {
    /*.dht_config = */{
        /*.node_config = */{
            /*.node_id = */{},
            /*.network = */0,
            /*.is_bootstrap = */false,
            /*.maintain_storage*/true
        },
        /*.id = */dht::crypto::Identity{}
    },
    /*.threaded = */true
});
```

However that requires all nodes on the network to use this configuration for the feature to work, and it's currently not enabled on the public network.
But it's possible to build a private DHT network with that feature.

**Comment by aberaud** [comment]
As Simon mentioned, the "permanent" flag means that a given node will automatically keep the value on the network, but that requires the node to remain alive.

**Comment by GrossoMoreira** [comment]
I understand, but if all values remain in the network forever (because I can't delete them) the storage will keep growing and growing.

The alternative is to store the data set (hundreds of thousands of values) over and over again. But then not only will my system waste memory by storing values it no longer needs, as it will generate a lot of network traffic by re-putting all the values that keep expiring all the time.

I conclude that opendht does not the implement the features I am looking for. Thank you anyways!

**Comment by aberaud** [comment]
Even with data maintenance, values will expire after their normal "expiration time". Data persistence will just make sure that values remain on the network until they naturally expire.

**Comment by testbird** [comment]
Instead of flagging data "permanent" and the configuration option "maintain_storage", may this feature be made better to grasp by calling it something like "pass-data-on-exit" or "ensure-availability-on-exit"?

I may not have understood this yet, but IMHO "permanent" would fit better as a named value for the expiriation time (i.e. false).

**Comment by testbird** [comment]
"keep/pass-on-before-expiration", "drop-only-if-expired"?
