### ISSUE TITLE
Need build opendht on windows

### ISSUE THREAD

**Issue by gyb997** [savoirfairelinux/opendht#201]
I need some help to build opendht on windows.There is no document can be search on google or otherwise. Pls help me

**Comment by atraczyk** [comment]
@gyb997 first run `fetch_deps.bat` then `build_vs2015_release_x64.bat`.
The ouptuts should be located in the parent directory of opendht.

**Comment by gyb997** [comment]
thx a lot .I will try

**Comment by chiefBiiko** [comment]
same here. trying to build on win7..

- able to fetch dependencies with `fetch_deps.bat` by passing `--no-check-certificate` to `wget` and tossing file extensions of archives in each `opendht/MSVC/contrib/src/*/fetch_and_patch.bat`

- then downloaded `msbuild.exe` from [here](https://www.microsoft.com/en-us/download/confirmation.aspx?id=40760)

- running `build_vs2015_release_x64.bat` fails telling me that an imported project can not be found at `C:\Microsoft.Cpp.Default.props` -> its true no such directory.. -> what requirement am I missing?

**Comment by atraczyk** [comment]
@chiefBiiko the build tools link you posted is for Build Tools 2013, which is version 12.0, so changing line 6 in  `build_vs2015_release_x64.bat`
from
`set PATH=%PATH%;%ProgramFiles(x86)%\MSBuild\14.0\Bin\`
to
`set PATH=%PATH%;%ProgramFiles(x86)%\MSBuild\12.0\Bin\`
could work, but you should really just get [Build Tools 2015](https://www.microsoft.com/en-us/download/confirmation.aspx?id=48159) and use that instead, as we've only tested opendht windows builds using visual studio 2015.

**Comment by chiefBiiko** [comment]
thanks

**Comment by gyb997** [comment]
ok, thx
