### ISSUE TITLE
please handle connection problems gracefully

### ISSUE THREAD

**Issue by aviau** [savoirfairelinux/opendht#206]
From Debian bug [#869510](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869510)

>dhtnode defaults to connecting to bootstrap.ring.cx, which has both an
IPv4 and an IPv6 address.  However, it apparently insists on trying to
connect to the IPv6 address, even from systems like mine that still
lack v6 connectivity, and the resulting frequent retries lead to a lot
of syslog spam.
>
>Although I agree that my ISP should get with the times ;-), dhtnode
should meanwhile handle connection problems more gracefully.
Specifically, it should fall back on IPv4 if it can't get IPv6 to
work, and if neither works, it should pause for longer between
retries, perhaps with an exponential backoff.
>
>Could you please look into it?

Cheers,

**Comment by petterreinholdtsen** [comment]
Is this hard to implement?

**Comment by terrytw** [comment]
I ran into the same problem. The log file is humongous after a few hours.

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by petterreinholdtsen** [comment]
[Gavin Henry]
> Still a requirement?

What do you mean?  For whom, and when?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by ghenry** [comment]
I mean to politely ask if you've tried or tested again since 2019 :-)

**Comment by petterreinholdtsen** [comment]
[Gavin Henry]
> I mean to politely ask if you've tried or tested again since 2019 :-)

Right, then I understand the question.  I am not the one reporting it,
so I have no idea.  The one reporting it is listed in the Debian bug
report.

-- 
Happy hacking
Petter Reinholdtsen
