### ISSUE TITLE
no bittorrent?

### ISSUE THREAD

**Issue by Zibri** [savoirfairelinux/opendht#208]
Why it doesn't work with bittorrent bootstrap servers?

I tried:

dhtnode -b router.utorrent.com:6881
and
dhtnode dht.transmissionbt.com:6881

seems to work only with 
dhtnode -b bootstrap.ring.cx:4222

**Comment by aberaud** [comment]
The protocol is similar (and inspired by) but not compatible with mainline Bittorrent DHT

**Comment by Zibri** [comment]
can't you just add a compatibility flag? It would be great.
