### ISSUE TITLE
Possibly incorrect boolean comparisons

### ISSUE THREAD

**Issue by zorun** [savoirfairelinux/opendht#210]
There is a strange warning when building opendht:

```
/build/opendht/src/opendht-1.3.6/src/value.cpp: In constructor ‘dht::Where::Where(const string&)’:
/build/opendht/src/opendht-1.3.6/src/value.cpp:364:48: warning: enum constant in boolean context [-Wint-in-bool-context]
                         and value_str.size() > 1
                                                ^
```

The relevant code:

```
363                 if (convert.failbit
364                         and value_str.size() > 1
365                         and value_str[0] == '\"'
366                         and value_str[value_str.size()-1] == '\"')
```

I think the compiler parses this as `(convert.failbit and value_str.size()) > 1`.  I'm actually surprised of the usage of `and` and `or` instead of `&&` and `||`: is this something new in C+11?

**Comment by aberaud** [comment]
`and` and `or` are standard c++ keywords, see http://en.cppreference.com/w/cpp/language/operator_alternative

failbit is implementation-dependent, we now use the bool operator
