### ISSUE TITLE
NodeExport to string stream for easy file save

### ISSUE THREAD

**Issue by Deathsbreed** [savoirfairelinux/opendht#211]
Some solution to this problem may already exist, but it doesn't seem to be very well documented (which is another issue). I've been trying to create a program that saves known nodes to a file (so that it doesn't have to continuously find new nodes every time from the program starts, so it would be nice to have a simple way of converting this structure into a string stream (or something similar) that I could save into a file.

If a solution to this exists then I suggest that it be mentioned on [this page](https://github.com/savoirfairelinux/opendht/wiki/Running-a-node-in-your-program) after mentioning the `exportNodes()` function and the `struct NodeExport`.

I may be able to write something simple myself, as from what I can see the only element of `socketaddr_storage` used is `ss_family`, but I'm not as familiar with this repo as others. If I am correct then a simple operator should be quite simple to implement.

You could also set it up so it just saves to a path directly, but I'm not sure if y'all want to do that, so string stream is good enough.

Thanks.

**Comment by aberaud** [comment]
Since OpenDHT already makes use of msgpack serialization, I added support for msgpack serialization to the NodeExport structure in 1b9e9452c4382865ef61608d7b5d5f8f37185f97 .

Also added an example of exporting/importing nodes to/form a binary file here:
https://github.com/savoirfairelinux/opendht/wiki/Running-a-node-in-your-program#joining-an-existing-network

**Comment by Deathsbreed** [comment]
@aberaud alright, this is what I was looking for, thanks! :)

**Comment by Deathsbreed** [comment]
Sorry to reopen this issue, but it seems that the code provided does not function, more accurately the compiler gives me errors.

First, when trying to export the node using the code provided in the Wiki I get the following error:
```
/usr/include/msgpack/v1/object.hpp:198:11: error: ‘const struct dht::NodeExport’ has no member named ‘msgpack_pack’
         v.msgpack_pack(o);
         ~~^~~~~~~~~~~~
```

It's really a lot uglier than that, but this gives you the idea. Basically it's trying to find a `msgpack_pack()` function in `dht::NodeExport`, but cannot find one.

Then, when commenting that out and trying the import code I get a different error:
```
/usr/include/msgpack/v1/object.hpp:209:7: error: ‘struct dht::NodeExport’ has no member named ‘msgpack_unpack’
     v.msgpack_unpack(o.convert());
     ~~^~~~~~~~~~~~~~
```

As you can see, it's another missing function for the unpacking.

If you need more information I can give you the longer errors.

**Comment by aberaud** [comment]
Hi,
Sorry for the delayed answer,
Are you sure that you're using the latest OpenDHT, including https://github.com/savoirfairelinux/opendht/commit/1b9e9452c4382865ef61608d7b5d5f8f37185f97 ?
Before this commit NodeExport had no msgpack serialization.

**Comment by Deathsbreed** [comment]
Ah, it seems not, I'm using the v1.3.6 release from Arch's repository. I'll test it again with the repo, but do you know how long it may be until these commits get put into a release?
