### ISSUE TITLE
Lack of Documentation

### ISSUE THREAD

**Issue by Deathsbreed** [savoirfairelinux/opendht#212]
I don't want to sound petty, but there tends to be a problem if I have to read the header files in order to understand the public interfaces I have access to. It seems that some functions have Doxygen style comments to them (but only a few) and `Doxyfile.in` doesn't seem to compile correctly (unless there is a CMake flag I need to use, which I have not found documented in `README.md` or [the wiki](https://github.com/savoirfairelinux/opendht/wiki/Build-the-library) either).

Perhaps creating a general `Doxyfile` in the root directory and adding more Doxygen-style comments on the rest of the elements would help.

Thanks.

**Comment by aberaud** [comment]
Latest release (1.4) allows to build the Doxygen documentation using CMake (enabled by default if Doxygen is found).
The Doxygen documentation itself have also been sightly improved and will keep improving with next releases as an ongoing work.
