### ISSUE TITLE
cannot install opendht for windows ms visual studio 2015

### ISSUE THREAD

**Issue by cancny95** [savoirfairelinux/opendht#221]
I cloned the project.
Firstly, I runned "fetch_deps.bat" in MSVC after adding to --no-check-certificate to wgets and changing the files got with extension "tar.gz".
I installed msbuild tools from : 
https://www.microsoft.com/en-us/download/details.aspx?id=48159 .
When I run "build_vs2015_release_x64.bat" there are some errors one of them says in "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\BuildCustomizations\vsyasm.props" not found which is true.

Am I missing something. Is there anything that I must install before.

Also, there are some files that are not in same folder which must be in same folders according to the error messages. However, when I find and copy them to the same folder there is no error. But, I thought I did something wrong after these errors.

Thanks for any help.

**Comment by atraczyk** [comment]
Hello,

opendht depends on libgmp which requires that YASM be installed and configured for visual studio. You can follow the instructions here:
https://github.com/ShiftMediaProject/VSYASM/

Hope that helps.

**Comment by cancny95** [comment]
Thanks.
