### ISSUE TITLE
Cannot use -l or --logfile option when --daemonize or -d is used

### ISSUE THREAD

**Issue by Apteryks** [savoirfairelinux/opendht#230]
Hello,

There doesn't appear to be a way to generate log output (either to file, syslog, or stdout) when using the --daemonize or -d option of the dhtnode program.

This works: ``dhtnode --syslog -b bootstrap.ring.cx`` or ``dhtnode -v -b bootstrap.ring.cx`` or ``dhtnode  --logfile=dhtnode.log -b bootstrap.ring.cx``

These args are accepted but appear to not have an effect (no logs in syslog and the logfile is not created) ``dhtnode --syslog --daemonize -b bootstrap.ring.cx`` or ``dhtnode --daemonize --logfile=dhtnode.log -b bootstrap.ring.cx``

**Comment by AmarOk1412** [comment]
In fact log is broken.

**Comment by Apteryks** [comment]
After more testing I could get messages (but very few) in /var/log/syslog using the following:

``/usr/bin/dhtnode -d --syslog -b bootstrap.ring.cx``

Using --logfile or -l with --daemonize is truely broken though (doesn't even create the log file).
