### ISSUE TITLE
get() doesn't return all values

### ISSUE THREAD

**Issue by imadari** [savoirfairelinux/opendht#233]
I have two dht nodes, both of them storing different values under the same key.

When I call the ```get()``` _sometimes_ only the values which was ```put()``` on the same node are returned (if the value was ```put()``` on the another node, they just simply not returned or just few of them returned).

So the questions:
 - Are there any way to retrieve ALL the values under a given key?
 - When do the ```get()``` stops looking for more values? Is there a time limit on the ```get()```?
 - Does the ```GetCallback``` running time affect when the ```get()``` gives up the search for more values?

Thanks,
Istvan

**Comment by aberaud** [comment]
Hi,
`get()` is supposed to retrieve all values at a given key. The operation is ended when the `DoneCallback` is called, or if the `GetCallback` returns false. `listen()` can be used to have a long-running listener for a key.

- How many values do you store/retrieve at the given key, and at which rate ?
- What's the network/node configuration ?

**Comment by imadari** [comment]
Hi,

Thanks for the quick reply! Here are the details, please let me know if you have any idea what causes this strange behavior.

> What's the network/node configuration ?

The current setup:
 - Two DHT nodes are running on two machines. They are connected to the same router using ethernet (they are not on wifi).
 - The machines are armhf architecture. (BeagleBone Black boards)

> How many values do you store/retrieve at the given key, and at which rate ?

 - Node 1 and Node 2 ```put()``` one-one values about the same time and executes ```get()``` right after the ```put()```
 - Node 1 ```put()``` one more value and executes the ```get()``` to return the already stored ones. This is the step where the ```get()``` doesn't return the values stored on Node 2.

I tested a lot and I observed two factors that affect the behavior:

1. The ```put()``` and ```get()``` are too close
```c++
/**
  * get() is called immediately after the put()
  * The values stored on another node are not returned (or partially returned)
  */
_dhtNode.put(key, dht::Value::pack(myStructure));
_dhtNode.get(key, ...); 

/**
  * wait after the put() and the get() returned all the values
  */
_dhtNode.put(key, dht::Value::pack(myStructure));
sleep(5);
_dhtNode.get(key, ...); // Returns all values
```

2. ```GetCallback()``` execution time
```c++
/**
  * the results were also better if the get() callback
  * doesn't spend "too much time" in the callback
  */
_dhtNode.get(key, [this](const std::vector<std::shared_ptr<dht::Value>> &values){
  sleep(2);
  return true;
}); // Doesn't return all values

/**
  * Just start another thread and sleep there.
  */
_dhtNode.get(key, [this](const std::vector<std::shared_ptr<dht::Value>> &values){
  std::thread t = ...;
  t.detach();
  return true;
});
```

> listen() can be used to have a long-running listener for a key.

The ```listen()``` works, it gives back the newly put values.

One of my ideas is that the BeagleBone is using a single core armhf processor (clocking only on 1GHz) and the ```put()``` may block the ```get()``` and the ```get()``` just run out of time. Does it make any sense? This is just my theory I didn't dive deep in the ```OpenDHT``` source.

**Comment by aberaud** [comment]
Oh I see

- `get()` should be able to consistently retrieve a value as soon as the `put`' `DoneCallback` have been called (informing that the put operation is complete).
- Please don't block inside an OpenDHT callback as callbacks are called synchronously from the Dht thread so that might prevent the Dht from running properly (OpenDHT might call callbacks form a queue in the future to help with this).

**Comment by imadari** [comment]
Please correct me if I'm wrong. So, if I start the ```get()``` in the ```put()``` callback when the ```put()``` was succeeded will prevent this issue?

```c++
_dhtNode.put(key, dht::Value::pack(myStructure),[this, key](bool succ){
  if (succ) _dhtNode.get(key, ...);
});
```

**Comment by aberaud** [comment]
Yes indeed, at least for the value put by the same node. For node communication you might want to use listen to avoid race conditions. You can also check `python/tools/pingpong.py` for an example using the Python3 bindings (with similar API and semantics).
