### ISSUE TITLE
DHTNode compilation issue on Mac OS X

### ISSUE THREAD

**Issue by kiddouk** [savoirfairelinux/opendht#236]
hey guys,

I have been fiddling a bit with OpenDHT and I am hitting a road block. Compiling dhtnode tools triggers an error.

I am using `master` branch as a source. `cmake` or `autotools` are giving the same results.

Since the error is gigantic, I have created a pastebin for it located at  [https://pastebin.com/8kHB6rSx](https://pastebin.com/8kHB6rSx)

Isolating a little the commands that are responsible for such error, I get 

```/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DOPENDHT_LOG=true -DOPENDHT_PROXY_CLIENT=true -DOPENDHT_PROXY_SERVER=true -DOPENDHT_PROXY_SERVER_IDENTITY=false -DOPENDHT_PUSH_NOTIFICATIONS=true -isystem /usr/local/Cellar/msgpack/2.1.5/include -isystem /usr/local/Cellar/gnutls/3.5.17/include -isystem /usr/local/Cellar/nettle/3.4/include -isystem /usr/local/include -isystem /usr/local/Cellar/jsoncpp/1.8.4/include -I/Users/sebastien/code/opendht/opendht/. -I/Users/sebastien/code/opendht/opendht/include -I/Users/sebastien/code/opendht/opendht/include/opendht -I/Users/sebastien/code/opendht/opendht/build/include -I/Users/sebastien/code/opendht/opendht/argon2/include  -Wno-return-type -Wall -Wextra -Wnon-virtual-dtor -pedantic-errors -fvisibility=hidden -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -O3 -DNDEBUG   -std=gnu++11 -o CMakeFiles/dhtnode.dir/dhtnode.cpp.o -c /Users/sebastien/code/opendht/opendht/tools/dhtnode.cpp```

since we are on Mac OS X, my LLVM version is : 
```$> c++ --version
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

I also tried to `git bisect` my way back to a version that could compile without much success unfortunately. `1.5.0` doesn't compile either but for some other reasons and I need to use the push notification anyway.

Let me know if you need any more info regarding that error,

Cheers,

**Comment by aberaud** [comment]
Hi,
Thanks for the report,
It should be fixed by https://github.com/savoirfairelinux/opendht/commit/c03ba57895361d7f9f0f9874b59cb30c7b4e1e2e . Could you please confirm ?  (I use LLVM 9 which doesn't have the issue)

**Comment by kiddouk** [comment]
I confirm ! Thanks for this.
