### ISSUE TITLE
How to retrieve data from dht::Value

### ISSUE THREAD

**Issue by cr-ellis** [savoirfairelinux/opendht#237]
I'm having issues with retrieving the data from opendht.  I'm sure this should be obvious but it's not covered in the documentation or examples.

In this following code:
```
    // get data from the dht
    node.get("my_test_key",
    [](const std::vector<std::shared_ptr<dht::Value>>& values) {
        // Callback called when values are found
        for (const auto& value : values) {
            std::cout << "Found value: " << *value << std::endl;
        }
        return true; // return false to stop the search
    },
    [=] (bool success) {
        std::cout << "Get: ";
        done_cb(success);
    });
```
 
*value is of type dht::Value which has both Id and Data elements.
Found value: Value[id:62171dd4be1960d6 Data (type: 0 ): 0a0a0a0a0a]

I need to retrieve the data part only.  How is this done?

**Comment by aberaud** [comment]
It's in the `data` field:
```c++
value->data
```
