### ISSUE TITLE
Better code documentation

### ISSUE THREAD

**Issue by NicoHood** [savoirfairelinux/opendht#24]
There are almost no comments in the code, so its hard for some to work into it. If there were at least a few comments, stating what the functions just do would be nice.

I hope you dont mind that I flag this as issue. This project looks promising.

**Comment by kaldoran** [comment]
Update on this issue : 
Sometime even if there is doc .. its a zrong one ( probably old one ) 
E.g. :
- https://github.com/savoirfairelinux/opendht/blob/master/src/dht.cpp#L310
- https://github.com/savoirfairelinux/opendht/blob/master/src/dht.cpp#L316

**Comment by aberaud** [comment]
>  Sometime even if there is doc .. its a zrong one ( probably old one ) 
Those got fixed.
More documentation will be added, but closing this since it's a long-term ongoing work with no clear completion requirements.
