### ISSUE TITLE
Cmake fails with Android build

### ISSUE THREAD

**Issue by kiddouk** [savoirfairelinux/opendht#240]
Hi guys,

I am trying to compile OpenDHT for android using cmake and the command line.
The command I use is the following:

`cmake  -DOPENDHT_PROXY_CLIENT=ON -DOPENDHT_PUSH_NOTIFICATIONS=ON -DANDROID_ABI=armeabi-v7a -DCMAKE_TOOLCHAIN_FILE=/usr/local/opt/android-ndk-r16b/build/cmake/android.toolchain.cmake`

and the error that I get:

```-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1")
CMake Error at /usr/local/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find GnuTLS (missing: GNUTLS_LIBRARY GNUTLS_INCLUDE_DIR) (found
  suitable version "3.4.10", minimum required is "3.3")
Call Stack (most recent call first):
  /usr/local/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/share/cmake-3.10/Modules/FindGnuTLS.cmake:54 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:31 (find_package)
```

It seems that the lib is found but the compilation parameters are failing somehow. I suspect this to be bound to the android cmake file for the toolchain. I can reproduce both on Mac OS X and Ubuntu with the respective NDK r16b installed.

How do you compile OpenDHT for android?

**Comment by aberaud** [comment]
Hi,
How do you build GnuTLS for Android ?
Have you tried setting CMAKE_FIND_ROOT_PATH to the install root of your project (including all dependencies built for Android)

**Comment by kiddouk** [comment]
That's good input, thanks!

Indeed, I am making a mistake on my side. I naively thought that providing the dev package was enough while trying to cross compile for ARM-EABI. Which ... was not about to happen. Duh!

I will go about GnuTLS and the deps and see what I can do from there.
Maybe that will be a good occasion for a PR for the build section of the wiki? 😃

**Comment by AmarOk1412** [comment]
sure!

**Comment by kiddouk** [comment]
Not yet but I am working actively on it at the moment. I decided to explore the mix of standalone toolchain AND the cmake file provided by the android NDK. 

One of the issue I got with NDK r16b (latest as time of writing) is that `__sbuf` and `_sFILE` structs are not defined anymore like they were in r13. It's no big deal but I am wondering if I should send my patch upstream to libunistring (a dependency) or if I am just doing something wrong. 🤔

Which NDK are you using to compile ring for example ?

**Comment by aberaud** [comment]
Hi,
We build GnuTLS with:
```
	--disable-gtk-doc \
	--without-p11-kit \
	--disable-cxx \
	--disable-srp-authentication \
	--disable-psk-authentication-FIXME \
	--with-included-libtasn1 \
	--with-included-unistring \
	--disable-openpgp-authentication \
	--disable-openssl-compatibility \
	--disable-guile \
	--disable-nls \
	--disable-dtls-srtp-support \
	--without-libintl-prefix \
	--disable-non-suiteb-curves
```
So a built-in version of unistring is used.

We build OpenDHT on Android as a part of Ring. The build makes use of our "contrib" mechanism that was initially borrowed from VLC.
https://github.com/savoirfairelinux/ring-daemon/tree/master/contrib
Also check
https://github.com/savoirfairelinux/ring-client-android/blob/master/build-daemon.sh
to see how the contrib system is invoked for Android.

You should be able to use this infrastructure to build only OpenDHT and dependencies for Android.

Clone ring-daemon and export some environnement variables:
```bash
DAEMON_DIR=/path/to/ring-daemon
TARGET_TUPLE=arm-linux-androideabi
ANDROID_NDK=/path/to/ndk
ANDROID_SDK=/path/to/sdk
ANDROID_ABI=armeabi-v7a
NDK_TOOLCHAIN_PATH=${ANDROID_TOOLCHAIN}/bin
SYSROOT=$ANDROID_TOOLCHAIN/sysroot
PATH=${NDK_TOOLCHAIN_PATH}:${PATH}
CROSS_COMPILE=${NDK_TOOLCHAIN_PATH}/${TARGET_TUPLE}-
```
Now start the contrib build for OpenDHT only:
```bash
cd $DAEMON_DIR
mkdir -p contrib/native-${TARGET_TUPLE}
mkdir -p contrib/${TARGET_TUPLE}/lib/pkgconfig
cd $DAEMON_DIR/contrib/native-${TARGET_TUPLE}
../bootstrap --host=${TARGET_TUPLE}

echo "EXTRA_CFLAGS= -g -fpic ${EXTRA_CFLAGS}" >> config.mak
echo "EXTRA_CXXFLAGS= -g -fpic ${EXTRA_CXXFLAGS}" >> config.mak
echo "EXTRA_LDFLAGS= ${EXTRA_LDFLAGS} -L${SYSROOT}/usr/${LIBDIR}" >> config.mak
make list
make fetch
make .opendht
```

Build configuration for OpenDHT and dependencies can be edited at `ring-daemon/contrib/src/package_name/rules.mak`

**Comment by kiddouk** [comment]
Thanks for all those info!

I ended up building my own version of OpenDHT (with the official libunitstring and a home made patch). Like you I disabled p11-kit for gnutls and I let OpenSSL aside for now.

I will have a look at your build and see what I can pull in order to automate my different builds on my CI.

**Comment by qipx0033** [comment]
@kiddouk have you built your android project successful ?

**Comment by kiddouk** [comment]
Hej guys,

sorry for the silence. As for the android project, nothing has moved in a while due to my agenda. As for compiling on android, I got it to work. :)

**Comment by AmarOk1412** [comment]
Cool! So we can close this issue?
