### ISSUE TITLE
OpenDHT build is broken without push notifications

### ISSUE THREAD

**Issue by AmarOk1412** [savoirfairelinux/opendht#242]
`cmake -DOPENDHT_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/usr -DOPENDHT_PROXY_SERVER=ON -DOPENDHT_PROXY_CLIENT=ON -DOPENDHT_PUSH_NOTIFICATIONS=OFF` is broken...

I'll fix this ASAP. Other idea: add a build matrix for the travis to test multiple options and avoid this.

**Comment by kiddouk** [comment]
Please note that I _suspect_ that OPENDHT_PROXY_SERVER is *required* when adding OPENDHT_PUSH_NOTIFICATIONS.

**Comment by AmarOk1412** [comment]
@kiddouk sorry for the delay, have a lot of things to do :)

if you enable `OPENDHT_PUSH_NOTIFICATIONS`, you must have `OPENDHT_PROXY_SERVER` OR `OPENDHT_PROXY_CLIENT`, but the server is not required.

Have a nice day!
