### ISSUE TITLE
./configure: line 17172: syntax error near unexpected token `PKG_CHECK_MODULES'

### ISSUE THREAD

**Issue by lightzhan** [savoirfairelinux/opendht#253]
When I run "./configure". There is a error:
./configure: line 17172: syntax error near unexpected token `PKG_CHECK_MODULES'
./configure: line 17172: `PKG_CHECK_MODULES(Nettle, nettle >= 2.4)'

And I have installed pkg-config. I compile it on ubuntu16.04.

**Comment by AmarOk1412** [comment]
Can you run `pkg-config --version`?
also `which pkg-config`?

Do you see something like:

`checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes`

**Comment by lightzhan** [comment]
Yes, I can see this:
0.29.1

**Comment by lightzhan** [comment]
when run 'which pkg-config':
/usr/bin/pkg-config

**Comment by AmarOk1412** [comment]
Wow.

Can you test this: https://stackoverflow.com/questions/36659867/pkg-check-modules-syntax-error-near-luajit

Is there any `PKG_CHECK_MODULES` in `/usr/share/aclocal/pkg.m4`?

This is definitively a problem with `pkg-config`, not OpenDHT. If you have nettle on your system you can try to comment this line or use the cmake build.

**Comment by lightzhan** [comment]
@AmarOk1412 Thank you. I will have a try!

**Comment by lightzhan** [comment]
@AmarOk1412 I have solved the problem. Thanks your help!

**Comment by AmarOk1412** [comment]
What was the solution?

Np. Have a nice day.

**Comment by lightzhan** [comment]
@AmarOk1412 I copy pkg.m4 to the m4 directory and modify the Makefile.am. I add "--install" to the end of "ACLOCAL_AMFLAGS = -I m4". Then run "autoreconf -i -f", "aclocal -I m4" and "./configure". It works. I meet the problem when I compile Ring. When it compile sndfile and ring-daemon, It has the same problem but can use this method to solve it, In addition, they need modify the configure.ac.We need add "AC_CONFIG_MACRO_DIR([m4])" to the file. Because the opendht configure.ac file already has it,so we do not need modify it. Wish it helpful for anyone! Have a nice day! : )

**Comment by divyeshg94** [comment]
In my case, I added the conf file before installing the libtool, so you need to run "autoreconf -i -f" after installing the libtool

**Comment by ryanneph** [comment]
@lightzhan and @divyeshg94 gave the solution that worked for me. A simple `autoreconf -i -f` solved it. Thanks!
