### ISSUE TITLE
Ability to work under custom protocol (not UDP only)

### ISSUE THREAD

**Issue by allright** [savoirfairelinux/opendht#274]
Is it possible to move out UDP logic from NetworkEngine. To be able to use OpenDHT over custom transport protocol, not UDP only? May be even not socket based.

**Comment by aberaud** [comment]
It would definitely be possible, a PR would be welcome :-)

**Comment by AmarOk1412** [comment]
Not only TCP in fact.

**Comment by aviau** [comment]
I take this as a yes?

**Comment by AmarOk1412** [comment]
yeap. If this issue is fulfilled, TCP transport will be available.

**Comment by ovari** [comment]
[GNOME] Unable to register account from public WiFi
https://git.ring.cx/savoirfairelinux/ring-client-gnome/issues/662

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by aberaud** [comment]
It's now possible with the current API to plug in a custom transport class, so closing this issue.
