### ISSUE TITLE
msvc build fail (incorrect import path)

### ISSUE THREAD

**Issue by ghost** [savoirfairelinux/opendht#304]
I tried to build opendht for windows, first running `fetch_deps.bat` and then `build_vs2015_release_x64.bat` and `build_vs2015_release_x64.bat` fails with 
```
msbuild "C:\Users\DEC05EBA\git\opendht\MSVC\contrib\build\argon2\vs2015\Argon2Ref\Argon2Ref.vcxproj" /nologo /p:Configuration=Release /p:Platform=x64 /verbosity:normal /maxcpucount:4
Build started 2018-05-29 22:18:14.
     1>Project "C:\Users\DEC05EBA\git\opendht\MSVC\contrib\build\argon2\vs2015\Argon2Ref\Argon2Ref.vcxproj" on node 1 (default targets).
     **1>C:\Users\DEC05EBA\git\opendht\MSVC\contrib\build\argon2\vs2015\Argon2Ref\Argon2Ref.vcxproj(34,3): error MSB4019: The imported project "C:\Microsoft.Cpp.Default.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.**
     1>Done Building Project "C:\Users\DEC05EBA\git\opendht\MSVC\contrib\build\argon2\vs2015\Argon2Ref\Argon2Ref.vcxproj" (default targets) -- FAILED.
```
The same thing happens for all dependencies (gmp, nettle, gnutls, etc).
Tested on windows 10 with visual studio 2017 community edition installed (msbuild 15.0).
From the logs it doesn't look like it fails because im using visual studio 2017 instead of visual studio 2015

**Comment by Mazecreator** [comment]
Any update on the MSVC build process.  I don't see these BAT files distributed in the current master and haven't successfully build OpenDHT on Windows MSVC as of yet.  Would love to help debug the process and upgrade if needed, would like to help debug some of the problems I am having with OpenDHT, but need both a debug & release version.

(Are their pre-build libraries available to avoid the build process?)

**Comment by binarytrails** [comment]
Hi @Mazecreator,

To my understanding, the build system for Windows is located in the jami-daemon (previously called ring-daemon) project in the contrib folder, you can see the ```build_all.bat``` [1] file which you could use to only build a specific core dependency like OpenDHT. Besides, there is a new Python build system for Windows coming shortly to simply the .bat files. Also, GitHub is just a mirror for Jami the bleeding edge changes are at Gerrit hosted by Jami.net [2]. I'm not sure about the pre-build libraries for the Windows platform.

Cheers,
Seva

[1] https://github.com/savoirfairelinux/ring-daemon/blob/master/contrib/build_all.bat
[2] https://review.jami.net/q/project:ring-daemon

**Comment by ghenry** [comment]
Issue still there?

**Comment by aberaud** [comment]
Should now be fixed
