### ISSUE TITLE
Error code: 8

### ISSUE THREAD

**Issue by chudsonwr** [savoirfairelinux/opendht#314]
Hi. I am not sure where else to put this. I am tracking down an issue we have with some network devices that are using DHT to maintain session state. We are receiving error 8 during a put operation to DHT, but I cannot track down what that error number refers to. 
Are you able to list error codes in your wiki?
`DHT_OP_PUT operation returned an error: 8`

**Comment by AmarOk1412** [comment]
Do you have some code? The put operations only takes a callback launched at the end with a boolean as a result. How do you use `DhtRunner::put`?

What gives you this: `DHT_OP_PUT operation returned an error: 8`?

**Comment by AmarOk1412** [comment]
Any update?

**Comment by aberaud** [comment]
Weird because OpenDHT doesn't return error codes.. Where does this code comes from ?

**Comment by aberaud** [comment]
Closing the issue because no news since June, feel free to re-open it.
