### ISSUE TITLE
dht name service?

### ISSUE THREAD

**Issue by testbird** [savoirfairelinux/opendht#315]
A naive idea:

Opendht is used as a key->value data-store, mapping RingIDs to IPs.

Couldn't there just be another dht namespace, mapping usernames to RingIDs, to establish a distributed name service?

Of course the second namespace could need to support things like ensuring longer expiration times, and the ability to revoke accounts again (https://github.com/savoirfairelinux/opendht/issues/196), but couldn't it be possible to have it store say vcards signed by the RingIDs key, to detect authenticated updates?

**Comment by testbird** [comment]
Oh right, had overlooked doublets of names.

Concerning the size, traffic, and revoking of registratons, is there maybe some implementation supporting a block**tree**, i.e. something like a [Trie](https://en.wikipedia.org/wiki/Trie) that could allow removing of unused node registrations from the shared data again.

**Comment by testbird** [comment]
I think the best thing of using an arbitrary name service is that it allows using nicks, as well as address book data, as well as hashes and encryptions of them. I could not yet find docs about the ring name service, for example mentioning a default hash algorithm. Is there one, yet?

As soon as using it, the inability of removing entries will create real problems. Like when the owner of a phone number changes. Have you already thought about ways how to solve this problem?
Like documenting add, edit and remove transactions in a  blockchain, or a blocktree that allows expiration and removal of leaves?


Is it an isse

**Comment by AmarOk1412** [comment]
Note: the doc is here https://git.ring.cx/savoirfairelinux/ring-project/wikis/technical/Name-Server-Protocol

@testbird for now, on the nameserver ns,ring.cx there is no way to remove an username (unless the blockchain crash)

**Comment by aberaud** [comment]
@testbird Linking to external services (email, phone number...) would definitely require some edition ability.

It would also require some sort of recognized authority to validate the email/phone number ownership to avoid MITM attacks.

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by aberaud** [comment]
Closing the issue. Please use the "discussions" feature on github to discuss this further.
