### ISSUE TITLE
undefined symbol in .so (python import fails)

### ISSUE THREAD

**Issue by gkarsai** [savoirfairelinux/opendht#328]
OS:Ubuntu 18.04.1 

Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import opendht
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/local/lib/python3.6/dist-packages/opendht.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN3dht10indexation10IndexEntry4TYPEE
---
opendht built from master branch.

Undefined symbol is:  dht::indexation::IndexEntry::TYPE, which is a statically initialized variable in src/indexation/pht.cpp. 

g++ --version: g++ (Ubuntu 7.3.0-16ubuntu3) 7.3.0

**Comment by aberaud** [comment]
Hi,
Yes there is an issue with the default build configuration,

Until it's fixed you should build with indexation enabled to build the python package
( `-DOPENDHT_INDEX=On` with cmake)

**Comment by aberaud** [comment]
Hi,
Starting with https://github.com/savoirfairelinux/opendht/commit/2b938110fd65a9c0cfc9bd1ec5d169973ae0f5d9, 
Indexation is automatically enabled when Python is.
