### ISSUE TITLE
Does Opendht save information to disk

### ISSUE THREAD

**Issue by techwizardg** [savoirfairelinux/opendht#330]
This is not an issue but not sure where to post this, does opendht retain information between server restarts?

**Comment by AmarOk1412** [comment]
No. Why?

**Comment by aberaud** [comment]
Not automatically, however APIs are available to export serializable data.
There are two types of data:

- the routing table (see `DhtRunner::exportNodes()` and `DhtRunner::bootstrap()` ) 
- stored values (see `DhtRunner::exportValues()` and `DhtRunner::importValues()` )

**Comment by aberaud** [comment]
@techwizardg Does that answer your question ?

**Comment by techwizardg** [comment]
Yes and you can close the issue.

**Comment by nadendlaprasad** [comment]
Imagine, we have exported the values when a node is shutting down and if we import the data back in to the node during restarting. what if the user updates one of the key value pair in the hash table when this node shutdown. does this import ensures to get in sync with the new values  ?
