### ISSUE TITLE
Replication factor

### ISSUE THREAD

**Issue by nadendlaprasad** [savoirfairelinux/opendht#334]
Does **openDHT** supports replication, If yes could you please provide any reference ? I tried looking into the **DhtRunner** API and not able to find out any clue .

**Comment by aberaud** [comment]
Every value is stored on 8 nodes for redundancy and to handle the flow of nodes joining/leaving the network.

**Comment by nadendlaprasad** [comment]
how could i customize the replication factor setting to some number say 3 ?

**Comment by aberaud** [comment]
You can change TARGET_NODES in routing_table.h

**Comment by nadendlaprasad** [comment]
thank you
