### ISSUE TITLE
Get list of keys across all dht nodes

### ISSUE THREAD

**Issue by nadendlaprasad** [savoirfairelinux/opendht#339]
Is it possible to fetch list of all keys in the distributed hash table using opendht?

**Comment by aberaud** [comment]
No it's not possible by design.

However you can try the experimental DHT indexation feature for indexation and search of structured data on the DHT

**Comment by nadendlaprasad** [comment]
thanks.I'll look into the indexation feature.

**Comment by nadendlaprasad** [comment]
thanks.I'll look into the indexation feature.
