### ISSUE TITLE
getId vs getNodeId from dhtRunner object?

### ISSUE THREAD

**Issue by nadendlaprasad** [savoirfairelinux/opendht#341]
Apologies. This is not an issue. But i did not know any other place to post this question.

May I know the difference between getId and getNodeId from dht::DhtRunner object?

**Comment by aberaud** [comment]
getId() returns the node public key fingerprint (if any), used when performing cryptographic operations like putSigned or putEncrypted.
getId() can also be used to know if a value was encrypted for this node' identity, by checking value->recipient == node->getId().

 getNodeId is the DHT node ID used for DHT routing. It is mostly exposed for debugging purposes.

**Comment by nadendlaprasad** [comment]
Thank you :)
