### ISSUE TITLE
Help with POST Curl JSON Format

### ISSUE THREAD

**Issue by science-girl** [savoirfairelinux/opendht#344]
I want to put data on my proxy server using curl.  I execute: 
```curl -X POST -d '{test}' <ip_address>:<port>/key1```
and get back ```{"err":"Incorrect JSON"}```

I have tried a few different permutations for the data but I can't seem to post data.  I get this:
```Got put 1073ab6cda4b991cd29f9e83a307f34004ae9327 Value[id:0 Data (type: 0 ): ] ```
which appears to be empty.

How can I format this to work?

**Comment by science-girl** [comment]
Nevermind :-)

Should be like this: 
```curl -X POST -d '{"test":123}' <ip_address>:<port>/key1```

**Comment by science-girl** [comment]
The data doesn't get stored...
```g key1
Using h(key1) = 1073ab6cda4b991cd29f9e83a307f34004ae9327
>> Get: found value (after 7.6418e-05s)
	Value[id:63c73218a74f79e7 Data (type: 0 ): ]```

Why?

**Comment by AmarOk1412** [comment]
Hi !

See https://github.com/savoirfairelinux/opendht/wiki/REST-API :)

For example:
```
 AmarOk@tars3  ~  curl -X POST -d "@DATA" http://127.0.0.1:8000/hash
{"data":"aGkgZnJvbSB0aGUgZGh0","id":"11320771760392112489","type":0}
 AmarOk@tars3  ~  curl http://127.0.0.1:8000/hash      
{"data":"aGkgZnJvbSB0aGUgZGh0","id":"11320771760392112489","type":0}
 AmarOk@tars3  ~  cat DATA                       
{"data":"aGkgZnJvbSB0aGUgZGh0","type":0}

 ✘ AmarOk@tars3  ~/Projets/opendht/build   master  ./tools/dhtnode -b bootstrap.ring.cx
OpenDht node 72eb0402b052a7b72928a2a832060cc5ea37f553 running on port 44285
 (type 'h' or 'help' for a list of possible commands)

>> g hash
Using h(hash) = 2346ad27d7568ba9896f1b7da6b5991251debdf2
>> Get: found value (after 0.0169384s)
	Value[id:9d1b75efa1720969 Data (type: 0 ): 68692066726f6d2074686520646874]

>> Get: completed (took 4.58076s)


# 68692066726f6d2074686520646874 = "hi from the dht" in hex
# aGkgZnJvbSB0aGUgZGh0 = base64(hi from the dht)
```

**Comment by science-girl** [comment]
Thank you so much, @AmarOk1412 !  I wasn't putting the data in base64 and I wasn't using a file, which I didn't realize was necessary :-)

**Comment by aberaud** [comment]
Hi :-) Note that using a file isn't strictly necessary, data could be a string in the command line like in your question.

**Comment by AmarOk1412** [comment]
Yeah, the `-d "@DATA"` is not important, you can POST from what you want it will be the same request for the proxy.

**Comment by rsdelhi91** [comment]
Following this thread, when we are placing data into the DHT node network, do we have the `hash` before making the POST request or is there some step I'm missing here?

I am trying to place a data, into my DHT node network and am trying this:

`curl -X POST -d "{"test":123}" http://127.0.0.1:8080/testhash`

I can see the REST API section of OpenDHT mention that the testhash location should be having a hash value there but I don't completely understand how we get that value, given that in my case I am introducing a new value to my network, one which does not exist.

Any assistance on this would be highly appreciated.

**Comment by aberaud** [comment]
Hi,
If you use a string `S` instead of hex hash, `sha1(S)` will be used as the key.

Note there can be multiple values for a single key (differentiated using the value id)

**Comment by rsdelhi91** [comment]
Thank you for sharing this. I noticed this line mentioned above: `# 68692066726f6d2074686520646874 = "hi from the dht" in hex`

This is apparently what's returned if we do a GET in the terminal version of dhtnode. What encoding scheme is used to represent - `68692066726f6d2074686520646874` and how may I decode it to `hi from the dht`? I can see that its written in hex but from which format to hexadecimal would be the right approach here?

**Comment by AmarOk1412** [comment]
@rsdelhi91 it's a vector of unsigned char (`using Blob = std::vector<uint8_t>;`). So `std::string((const char*)v.data.data(), v.data.size())` is enough (v is your value)

**Comment by rsdelhi91** [comment]
@AmarOk1412 - I would not need to worry about this if I'm using the proxy, would I?

Because the proxy would still be storing the data I send in the data param of my payload `curl -X POST -d '{"data":"dGVzdA==","type":0}' http://127.0.0.1:8080/test3` as base64? so when I perform a GET, I'll just need to decode the base64 value being returned as this - `{"data":"dGVzdA==","id":"8690897351346270540","type":0}`, right? 

Also, what does the `type` param actually mean here?

**Comment by AmarOk1412** [comment]
>  I would not need to worry about this if I'm using the proxy, would I?

You don't
> 68692066726f6d2074686520646874 = "hi from the dht"

A vector<uint8_t> or a string is only related to your client.

```bash
AmarOk@localhost  ~/ curl -X POST -d '{"data":"dGVzdA==","type":0}' http://localhost:8000/test3
{"data":"dGVzdA==","id":"3276606883550101785","type":0}
AmarOk@localhost  ~/  curl http://localhost:8000/test3           
{"data":"dGVzdA==","id":"3276606883550101785","type":0}
```

The type=0 correspond to the value type. The default one is a value expiring after 10 minutes. The types are defined here; https://github.com/savoirfairelinux/opendht/blob/4519a23996e6472939065d1da9bc593f1bb6d375/src/default_types.cpp#L84

As specified here: https://github.com/savoirfairelinux/opendht/wiki/API-Overview

> Every value also has a "value type". Each value type defines potentially complex storage, edition and expiration policies, allowing for instance different value expiration times. The set of supported "value types" is hardcoded and known by every node.

**Comment by rsdelhi91** [comment]
Thank you very much for that feedback.

I've taken a while to go through the default types class and am noticing that by default, a DHT Node holds a message for about 5 mins, does this mean that a message placed into the network gets purged after that time? Is there a way to increase the time to a couple of days maybe? Given that the type category 4 - "Certificate trust request" stays valid for a period of 24 hours, if I place a `"type":3` for a message, would it be kept valid as a normal message for the DHT node to ingest but kept in the network for a period of 24 hours?

**Comment by rsdelhi91** [comment]
@AmarOk1412 @aberaud - In the command line utility `dhtnode`, there is a way to maintain a data message persistently using `cpp` (please correct me if I'm inaccurate here). Is there a way to do the same, i.e. retain a message in my DHT network persistently (maybe even for a few days) using the REST API for OpenDHT? If yes, can someone please point me to the message format?
