### ISSUE TITLE
listen fetch only new values

### ISSUE THREAD

**Issue by nadendlaprasad** [savoirfairelinux/opendht#349]
```
dht.listen<dht::ImMessage>(room, [&](dht::ImMessage&& msg) {
                        if (msg.from != myid)
                            std::cout << msg.from.toString() << " at " << printTime(msg.date)
                                      << " (took " << print_dt(std::chrono::system_clock::now() - std::chrono::system_clock::from_time_t(msg.date))
                                      << "s) " << (msg.to == myid ? "ENCRYPTED ":"") << ": " << msg.id << " - " << msg.msg << std::endl;
                        return true;
                    });
```

The above code returns the old messages which are pushed to dht before subscription. Is it possible to fetch only the new values that are pushing to the DHT from the time of listening ?

**Comment by aberaud** [comment]
It will be a bit complex to implement in OpenDHT in a robust way without data races, however that's planned for future OpenDHT releases.

What's your use case ? A solution might be to keep previous message IDs to discard already processed ones (like what we do in Ring), or to have a timestamp in the messages if you trust data sources (something like msg.date above).

**Comment by nadendlaprasad** [comment]
I am glad, as this is planned for future release.
