### ISSUE TITLE
get last inserted value under the key

### ISSUE THREAD

**Issue by nadendlaprasad** [savoirfairelinux/opendht#365]
Hi,

Is it possible to fetch the last inserted value under the given key instead of fetching all the values ?

Also, Is there a way we can override the value when we perform put operation multiple times using the same key ?

**Comment by aberaud** [comment]
Hi,

There is no ordering guarantee with OpenDHT, so there is currently no way to get the "last value" in a consistent/reliable way (there would be race conditions).

However this can be implemented at the application level, for instance with a sequence number.

Currently only signed values can be edited. To do that you should edit the `dht::Value::data` field and perform putSigned again with this value.
