### ISSUE TITLE
OpenDHT benchmarks?

### ISSUE THREAD

**Issue by lonnieOST** [savoirfairelinux/opendht#371]
Hello,

I am strongly considering OpenDHT for a c++ project that I am working on that will entail a high-performance yet simple distributed type of database system but seem to recall reading, in the past, that OpenDHT had rather slow performance.

Can you please comment on if, or how, this has improved since I would like to fairly consider OpenDHT given its very nice properties.

Thanks :)

**Comment by aberaud** [comment]
Hi and thanks for your interest,

It mostly depends on what you consider acceptable performance, keeping in mind OpenDHT maintains a redundancy of 8 nodes to support heavy churn (up to 85% of nodes can change every 10 minutes without data loss).

We run OpenDHT nodes as proxy servers, and we observed a single node handling 1500 client requests (get/put/listen) per second while connected to the main public network. A node is single-threaded, so a single server could run as many nodes as its number of cores if necessary.

Actual performance will highly depends on your network and load type/use case. During the last few months we optimized a lot of use cases and in some cases performance (ops/s) was multiplied by 20x.

OpenDHT includes some python benchmark scripts for Linux that help to spot regressions by simulating a network environment and churn, however it's not a good way to predict real-world performance for a particular use case.
