### ISSUE TITLE
get value does not work on one node network in some cases

### ISSUE THREAD

**Issue by allright** [savoirfairelinux/opendht#379]
1. Run first node 
./dhtnode
OpenDht node 6437325bf8a916413601217df8e1bdc368fe998a running on port 53122

2. 
pp key 1
Using h(key) = a62f2225bf70bfaccbc7f1ef2a397836717377de
>> Put: failure (took 0.000336475s). Value ID: e5e1984918b18f18

3.
g key 1
Using h(key) = a62f2225bf70bfaccbc7f1ef2a397836717377de
>> Get: found value (after 0.00013038s)
	Value[id:e5e1984918b18f18 Data (type: 0 ): 31]
Get: failure (took 0.000199309s)

4. start second node: 
./dhtnode -b 0.0.0.0:53122

5. on first node type:
g key 1
Using h(key) = a62f2225bf70bfaccbc7f1ef2a397836717377de
Get: found value (after 3.9539e-05s)>> 
	Value[id:e5e1984918b18f18 Data (type: 0 ): 31]
Get: completed (took 0.000746944s)

6. stop second node
exit
Stopping node...

7. on first node try get key:
Using h(key) = a62f2225bf70bfaccbc7f1ef2a397836717377de

8. start second node again:
./dhtnode -b 0.0.0.0:53122

7. You will see immediately:
>> Get: found value (after 24.1714s)
	Value[id:e5e1984918b18f18 Data (type: 0 ): 31]
Get: completed (took 24.1717s)

// But I think this answer must not to be dependent from second node availability.
Really the value of "key" are cached on the first node, but it can not be extracted!

link to screenshot after scenario pass:
https://yadi.sk/i/BAHX9S_vLgy1RA

**Comment by aberaud** [comment]
Hi,
Thanks for reporting this,
Can you still reproduce this behavior with latest master ?

Many thanks

**Comment by aberaud** [comment]
I made some tests and coudn't reproduce it but still investigating

**Comment by ghenry** [comment]
Stale. Closing.
