### ISSUE TITLE
OpenDHT on Raspberry Pi

### ISSUE THREAD

**Issue by MatejKovacic** [savoirfairelinux/opendht#38]
Hi,

I am trying to compile OpenDHT on Raspberry Pi Model B (version 1). Here are the compile errors I get:

http://pastebin.com/1FE22rXS

Any help?

**Comment by aberaud** [comment]
Hi,

The issue is probably that GCC 4.7.3 is too old.
OpenDHT supports compilation with at least GCC 4.8+, because it makes use of many C++11 features.

I think Rasbian now includes GCC 4.8 ( package g++-4.8 ).
