### ISSUE TITLE
dhtnode IPv6 bootstrap/mesh issues

### ISSUE THREAD

**Issue by EternityForest** [savoirfairelinux/opendht#382]
When I try to bootstrap dhtnode using the b command, I seem to be unable to do so if I use an IPv6 address directly(I tried the [2607:f7a0:3:2:216:3cff:fee8:5106]:33540  format). However, if I give the address a name in my hosts file, for some reason everything seems to work fine.

Is this expected behavior, or am I misunderstanding the expected format for IPv6 addresses?

The reason I'm asking is because I'm interested in using OpenDHT and Jami over CJDNS or Yggdrasil, which leads to the additional question of what happens if a whole bunch of mesh users got on the network? Is the DHT fairly partition-tolerant, or do mesh users need to use a separate network ID to avoid polluting the DHT for non-mesh users?

It seems like there should be a way for everyone to use the same DHT since many users have both types of connection.

Thanks guys!

**Comment by tekknolagi** [comment]
I see the same results for direct IPv6 address but have not tried a hostname.

**Comment by AmarOk1412** [comment]
Hi!
I did three tests

1. Your address:
```
./dhtnode -b [2607:f7a0:3:2:216:3cff:fee8:5106]:33540 -v
OpenDht node 35643644b4074d717c4333ae20305dab3689d59b running on port 43065
 (type 'h' or 'help' for a list of possible commands)

[474267.201840] Sending ping to [2607:f7a0:3:2:216:3cff:fee8:5106]:33540
>> [474270.202372] [node 0000000000000000000000000000000000000000 [2607:f7a0:3:2:216:3cff:fee8:5106]:33540] expired !
[474277.201375] Sending ping to [2607:f7a0:3:2:216:3cff:fee8:5106]:33540
[474280.202047] [node 0000000000000000000000000000000000000000 [2607:f7a0:3:2:216:3cff:fee8:5106]:33540] expired !
[474287.201386] Sending ping to [2607:f7a0:3:2:216:3cff:fee8:5106]:33540
[474290.201793] [node 0000000000000000000000000000000000000000 [2607:f7a0:3:2:216:3cff:fee8:5106]:33540] expired !
```

2. With a local node
```
$1> ./dhtnode -p 8000
$2> ./dhtnode -b '[::1]:8000' -v                                          
OpenDht node 3257ffe7d0cb00298feae004f0caf348f08d7de4 running on port 59949
 (type 'h' or 'help' for a list of possible commands)

[474354.277060] Sending ping to [::1]:8000
[474354.277255] [node c8e08657e0b97dffb95da60868e821fbd4354f85 [::1]:8000] got pong !
>> [474357.756840] [confirm nodes] initial IPv6 'get' for my id (3257ffe7d0cb00298feae004f0caf348f08d7de4)
```

3. With bootstrap.jami.net
```
./dhtnode -b '[2607:fad8:0:1::3]' -v  
OpenDht node ec6ff31acab53a8fc6d7c40864e6cfe462c8a1a2 running on port 34618
 (type 'h' or 'help' for a list of possible commands)

[474545.537220] Sending ping to [2607:fad8:0:1::3]:4222
>> [474545.568257] [node 3e552eb049a6ba26dadf1aba00b9f5a262b3ba63 [2607:fad8:0:1::3]:4222] got pong !
```

This is working. You can try to use `-v` to get more logs. Also, depending your shell, you have to escape `[` and `]`.

**Comment by aberaud** [comment]
Hi,

We recently noticed that the port shown by dhtnode was only the IPv4 bound port.

However, when not giving any port (no -p) to dhtnode, any available port is bound for each socket and that usually means that different ports are bound for IPv4 and IPv6.

dhtnode was improved accordingly and now prints both ports since 958cb250a3e828fcea9607ab6047fa20ac87e7eb.

I made a few tests and was successfully able to use IPv6 in every supported configuration.

Closing the issue, please re-open if IPv6 issues persist
