### ISSUE TITLE
Support for short names in dhtchat

### ISSUE THREAD

**Issue by tekknolagi** [savoirfairelinux/opendht#383]
I'm writing a weechat interface for dhtchat and it would be nice to have short-names displayed in the chat messages. I can think of a couple approaches to this:

1. First-come first-serve nicknames, like normal IRC server nicks -- with some kind of consensus
2. Announce your nickname with a special kind of message and get it + a partial ID suffix (eg `username|18ja`)

Neither is particularly great, so I was wondering if there was something like this planned. Cheers!

**Comment by aberaud** [comment]
For Jami we use a blockchain-based nameservice that can be used to resolve a public-key or hash to a username. (for instance http://ns.jami.net/name/test )

**Comment by tekknolagi** [comment]
Is that software open source and/or is there a public API for it?

**Comment by aberaud** [comment]
yes !
https://git.jami.net/savoirfairelinux/ring-nameservice

Public API is not documented yet however it's a very simple REST API
