### ISSUE TITLE
Build the library steps not working for Ubuntu 16.04

### ISSUE THREAD

**Issue by rsdelhi91** [savoirfairelinux/opendht#388]
Hi,

I'm following the steps outlined here: https://github.com/savoirfairelinux/opendht/wiki/Build-the-library and I'm having issues with some of the steps outlined. I'm a bit unsure if I'm doing something wrong or the documentation needs to be updated but here's some of the stack trace I have when trying out on Ubuntu 16.04:

1. Issues installing `librestbed-dev`. Unable to install this.

2. When I run:

`$ cmake -DMSGPACK_CXX11=ON -DMSGPACK_BUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=/usr ..`

The compiler spits out the following:

```-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:100 (FIND_PACKAGE)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:100 (FIND_PACKAGE)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:100 (FIND_PACKAGE)


CMake Warning at /usr/share/cmake-3.5/Modules/FindBoost.cmake:725 (message):
  Imported targets not available for Boost version
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:763 (_Boost_COMPONENT_DEPENDENCIES)
  /usr/share/cmake-3.5/Modules/FindBoost.cmake:1332 (_Boost_MISSING_DEPENDENCIES)
  CMakeLists.txt:100 (FIND_PACKAGE)

  -- Could NOT find Boost
-- Could NOT find GTest (missing:  GTEST_LIBRARY GTEST_INCLUDE_DIR GTEST_MAIN_LIBRARY) 
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC
-- Performing Test MSGPACK_ENABLE_GCC_CXX_ATOMIC - Failed
-- Could NOT find Doxygen (missing:  DOXYGEN_EXECUTABLE) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/rsharma2/msgpack-2.1.1/build
```

3. When looking at `CMakeFiles/CMakeError.log`, I'm getting this:

```Determining if the pthread_create exist failed with the following output:
Change Dir: /home/rsharma2/opendht/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_2f264/fast"
/usr/bin/make -f CMakeFiles/cmTC_2f264.dir/build.make CMakeFiles/cmTC_2f264.dir/build
make[1]: Entering directory '/home/rsharma2/opendht/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_2f264.dir/CheckSymbolExists.c.o
/usr/bin/cc     -o CMakeFiles/cmTC_2f264.dir/CheckSymbolExists.c.o   -c /home/rsharma2/opendht/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_2f264
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_2f264.dir/link.txt --verbose=1
/usr/bin/cc       CMakeFiles/cmTC_2f264.dir/CheckSymbolExists.c.o  -o cmTC_2f264 -rdynamic 
CMakeFiles/cmTC_2f264.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_2f264.dir/build.make:97: recipe for target 'cmTC_2f264' failed
make[1]: *** [cmTC_2f264] Error 1
make[1]: Leaving directory '/home/rsharma2/opendht/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_2f264/fast' failed
make: *** [cmTC_2f264/fast] Error 2

File /home/rsharma2/opendht/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/rsharma2/opendht/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/make" "cmTC_c8e9f/fast"
/usr/bin/make -f CMakeFiles/cmTC_c8e9f.dir/build.make CMakeFiles/cmTC_c8e9f.dir/build
make[1]: Entering directory '/home/rsharma2/opendht/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_c8e9f.dir/CheckFunctionExists.c.o
/usr/bin/cc    -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_c8e9f.dir/CheckFunctionExists.c.o   -c /usr/share/cmake-3.5/Modules/CheckFunctionExists.c
Linking C executable cmTC_c8e9f
/usr/bin/cmake -E cmake_link_script CMakeFiles/cmTC_c8e9f.dir/link.txt --verbose=1
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create    CMakeFiles/cmTC_c8e9f.dir/CheckFunctionExists.c.o  -o cmTC_c8e9f -rdynamic -lpthreads 
/usr/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
CMakeFiles/cmTC_c8e9f.dir/build.make:97: recipe for target 'cmTC_c8e9f' failed
make[1]: *** [cmTC_c8e9f] Error 1
make[1]: Leaving directory '/home/rsharma2/opendht/build/CMakeFiles/CMakeTmp'
Makefile:126: recipe for target 'cmTC_c8e9f/fast' failed
make: *** [cmTC_c8e9f/fast] Error 2
```

It would be highly appreciated to get some assistance on this, thanks!

**Comment by aberaud** [comment]
Hi,

You can check our Dockerfiles, which are based on Ubuntu 16.04:
https://github.com/savoirfairelinux/opendht/blob/master/docker/DockerfileDeps

They include commands to build restbed from source.

Step 2: It seems that msgpack-c is configured just fine ! Warnings only say that Boost can't be found. Boost is an optional dependency of msgpack-c, not used by OpenDHT. After step 2 you should be able to run `make` and `sudo make install`.

Will try to update the documentation

**Comment by rsdelhi91** [comment]
Thank you for the docker file link. I've tuned the commands in that a bit and used it as a shell script as follows:

```
#!/bin/sh

sudo apt-get update && sudo apt-get install -y build-essential cmake git wget libncurses5-dev libreadline-dev nettle-dev libgnutls28-dev libuv1-dev  cython3 python3-dev libcppunit-dev libjsoncpp-dev libasio-dev libssl-dev python3-setuptools && sudo apt-get clean

git clone --recursive https://github.com/corvusoft/restbed.git && cd restbed && mkdir build && cd build && sudo cmake -DBUILD_TESTS=NO -DBUILD_EXAMPLES=NO -DBUILD_SSL=NO -DBUILD_SHARED=YES -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib .. && sudo make -j8 install && cd .. && sudo rm -rf restbed


wget https://github.com/msgpack/msgpack-c/releases/download/cpp-2.1.5/msgpack-2.1.5.tar.gz && tar -xzf msgpack-2.1.5.tar.gz && cd msgpack-2.1.5 && mkdir build && cd build && sudo cmake -DMSGPACK_CXX11=ON -DMSGPACK_BUILD_EXAMPLES=OFF -DCMAKE_INSTALL_PREFIX=/usr .. && sudo make -j8 && sudo make install && cd ../.. && sudo rm -rf msgpack-2.1.5 msgpack-2.1.5.tar.gz

cd 

git clone https://github.com/savoirfairelinux/opendht.git

cd opendht && mkdir build && cd build

cmake -DOPENDHT_PYTHON=ON -DOPENDHT_PROXY_SERVER=ON -DOPENDHT_PROXY_SERVER_IDENTITY=ON -DOPENDHT_PROXY_CLIENT=ON -DOPENDHT_PUSH_NOTIFICATIONS=ON -DOPENDHT_SYSTEMD=ON -DCMAKE_INSTALL_PREFIX=/usr ..

make -j4

sudo make install

systemctl start dhtnode
```
It would be quite helpful if you or someone can verify that I'm doing this right.

Also, I can see that the dhtnode.service has started but am not really sure how to make use of it now. I noticed that OpenDHT has support for Python as well, but after exploring the examples section of the root README, I'm a bit lost as to how to go about using it. Is there some sort of doc page I can refer to for understanding how to use Python3 with this please? 

Ideally I'm looking to setup a 5 node cluster with OpenDHT so just to validate my understanding, once the `dhtnode.service` is up and running, I need to use a Python3 (in my case) program to instantiate/launch a node and there are some functions/ReST API's available to join the node network? Would this be accurate?

**Comment by aberaud** [comment]
Hi,

You can use this example from the homepage:

```python
import opendht as dht

node = dht.DhtRunner()
node.run()

# Join the network through any running node
node.bootstrap("127.0.0.1", "4222")
```

This will start a node and connect to your dhtnode. Note that any running node can be used to join the network

**Comment by rsdelhi91** [comment]
I've modified my shell script to accomodate the Python3 error coming up in: https://github.com/savoirfairelinux/opendht/issues/328

Your Python script above makes sense now as the opendht package was throwing an error.

So just to clarify on your last statement, the python script shared by you will start a node, which connects to my dhtnode service that has now been built and is available . Will this node be running constantly when connected to the service or is there another concept at play here that I am missing?

All I'm trying to do is create my own personal 5 node network to create some tests for myself. It would be highly appreciated to get some of your valuable input on this.

**Comment by aberaud** [comment]
Every node, dhtnode or python, is exactly the same and nodes will share other nodes' address. Nodes remain connected to the distributed network until stopped (or until connectivity loss).

If you want to run a cluster of 5 nodes it's as simple as running your script 4 times.. (note that the script above would need some sort of sleep or loop at the end, to avoid ending, and keep the node running).

**Comment by rsdelhi91** [comment]
In regards to running a private 5 node cluster, If I want to carry out the following:

Running my script in a VPC (with no public IP - a private routable network) on 5 VM's, how would I create my script in this instance? Will the following bootstrap command still be valid:

`node.bootstrap("13.13.89.90", "4222")`

where 13.13.89.90 is the public IP address of my VM, and every other VM running a DHT node will connect to this? Would you be able to share an example for me to understand this process please?

**Comment by rsdelhi91** [comment]
Hi @aberaud , is there a way to find out which node has which set of keys using the dhtnode interpreter or in python? I am running the dhtnode interpreter and am registering my nodes using b <IP>:<port> then using p <key> <str> to place some <k:v> using one of the nodes but I can't tell if its being distributed across or not.

It would be highly helpful if you can suggest how to go about doing this.

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by aberaud** [comment]
Hi,
From dhtnode you can use the 'ls' command to show the routing table of each search (each operation on a given key uses the search routing table for that key).
Note that it's not required to add every node since nodes will find each other on the network.
Also note that Ubuntu 16.04 is not supported anymore. Closing the issue.
