### ISSUE TITLE
memory leak from Request

### ISSUE THREAD

**Issue by nkzxw** [savoirfairelinux/opendht#393]
struct net::Request has member std::shared_ptr<Node> node ，struct dht::Node has member std::map<Tid, std::shared_ptr <net::Request>> requests_, so circular reference happens when sending any network request.

**Comment by aberaud** [comment]
Current design supposedly breaks this link when a request succeeds (removed from the node' request map) or failed (node expires and request map is cleared).

However i'm working on make the node pointer in the request a weak_ptr, which should fix the issue

**Comment by nkzxw** [comment]
maybe you could use raw node pointer in the request, to make it Die fast and Die fierce when error happens.
