### ISSUE TITLE
Intensive CPU usage

### ISSUE THREAD

**Issue by Ralayax** [savoirfairelinux/opendht#395]
Hello,

I want to help the network by running a node on my dedicated server, but dhtnode uses a full cpu core at 100% all the time.

Is this normal behaviour ?

For info :
I run a self compiled 1.9.3 version, using a self compiled restbed 4.6.0.

Configuration file :
DHT_ARGS=-b bootstrap.jami.net -p 4222 --proxyserver 4522 -v

**Comment by aberaud** [comment]
Hello,
No it's not, OpenDHT should use close to 0% CPU when idle.

I just reproduced the issue, should be fixed soon, thanks for reporting..

**Comment by aberaud** [comment]
The issue should now be fixed in master. It was a combinaison of multiple minor corner cases in dhtnode and dhtrunner.
Thanks again for reporting this :)

**Comment by Ralayax** [comment]
It's always a pleasure to help good open source projects like this one ;)
