### ISSUE TITLE
Callback when answering a request

### ISSUE THREAD

**Issue by G10h4ck** [savoirfairelinux/opendht#399]
In RetroShare we are discussing about replacing our own Bittorrent compatible old DHT implementation (bitdht) with OpenDHT.
As far as we have understand the only missing feature is to be able to register a callback when our DHT node actually answer a get request, in our use case this is important because on this callback we trigger a UDP NAT traversal attempt. We do the same on the node which run the get (which already take a callback as parameter on OpenDHT too).
This way the firewall NAT see near in time UDP packets with reciprocal direction, addresses and ports, and "think" they are from an established connection, and hopefully instead of dropping them, it add them to it's NAT table and a "connection" is established.

I have been looking at OpenDHT code to see if I could contribute that with a pull request by myself, but although it seems it shouldn't be hard to provide such a mechanism in the current design, I haven't been able to understand where and what code I should write to make implement this. do you plan to implement this feature or could you give me some hints on how this could be implemented so I can contribute it in a pull request?

Thanks in advance!

**Comment by G10h4ck** [comment]
To look for help about this issue I am proposing an idea for GSoC 2020 under Freifunk umbrella.

**Comment by G10h4ck** [comment]
Any news about this?

**Comment by aberaud** [comment]
Hi,
Thanks a lot for your contribution proposal :-)
I started work on a "light" branch which goal is to build without GnuTLS or threading support, with the aim of building on embedded systems:
https://github.com/savoirfairelinux/opendht/compare/light

Sorry I couldn't make it for GSoC mentoring, but I would be happy to help in any way.

**Comment by aberaud** [comment]
Hi,
Thanks a lot for your contribution proposal :-)
I would be happy to help in any way.

To be honest I'm not sure about what you want to do with the "get" callback, as in many cases if the Dht node is NATed it won't receive a get request in the first place ?

Maybe the "Listen" feature can be used by RetroShare ? It was implemented by Jami to listen for incoming calls/messages and allows to separate the Dht layer from the Application layer.

Best luck and best regards

**Comment by G10h4ck** [comment]
> To be honest I'm not sure about what you want to do with the "get" callback, as in many cases if the Dht node is NATed it won't receive a get request in the first place ? If receiving the `get` triggers sending messages to another IP/port than the source of the `get`, that seems like asking for network abuse for DDoS.

RetroShare would check if get comes from a trusted friend ID and in that case trigger UDP connection/nat trasversal attempt, do you see DDoS risk also in this case?


> Maybe the "Listen" feature can be used by RetroShare ? It was implemented for Jami to listen for incoming calls/messages and allows to separate the Dht layer from the Application layer (also good from a privacy standpoint).

This seems interesting too where can i read more on how Jami uses that? So we can evaluate if it could work well for RetroShare too? Do the listen feature work well also behind NAT?

**Comment by csoler** [comment]
Retroshare (RS) method for NAT punching relies a lot on the specific implementation of the Kadmelia algorithm. If OpenDHT uses a similar method, then at some point it will receive forwarded UDP packets that correspond to a DHT request, and containing the IP of the origin of the request. That's how the NAT punching is initiated.

Another thing we really would enjoy having is a way to anonymously push/pull information to the DHT. If we can do that, we would be able to provide an automated friend list completion system for Retroshare over Tor, which would help a lot new users to have "friends". I spoke to some OpenDHT devs at FOSDEM some years ago and they said that anonymous push/pull was on its way but not finished yet. Any news of that too?

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by aberaud** [comment]
Consider using dhtnet for the general p2p connectivity establishment.
It uses ICE to establish an authenticated TLS/TCP socket, internally making use of OpenDHT to exchange ICE requests.

**Comment by G10h4ck** [comment]
Did you closed it because the callback has been added or because what we wanted to do with the callback can be done with https://github.com/savoirfairelinux/dhtnet ? About dhtnet sure it is an interesting project, but for our use case seems an overkill and introduce a bunch of dependencies such as gnutls.

**Comment by aberaud** [comment]
Hi,
Note that OpenDHT also depends on gnutls (mostly for sha1/sha256 computation, and for Certificate and Public/private key management). We had plans to make a light version that would not depend on it, but it's not being worked on right now.

If you think it still makes sense I'll reopen the issue and check to add the callback.

**Comment by G10h4ck** [comment]
> Hi, Note that OpenDHT also depends on gnutls (mostly for sha1/sha256 computation, and for Certificate and Public/private key management). We had plans to make a light version that would not depend on it, but it's not being worked on right now.

Yeah but it still seems doable


> If you think it still makes sense I'll reopen the issue and check to add the callback.

I think it still make sense, IMHO it is a relevant functionality for a DHT library to have such a callback/event
