### ISSUE TITLE
REST API for Python

### ISSUE THREAD

**Issue by rsdelhi91** [savoirfairelinux/opendht#400]
Hi,

From what I can observe, is this the only REST API for OpenDHT in Python - https://github.com/savoirfairelinux/opendht/blob/master/python/tools/http_server.py ?

Is there a possibility to include the same functionalities as listen, update routing table, join, etc for the Python REST API as well if its not there? If its already present and I'm looking at the wrong place, can someone please point me to where may I be able to access that spec?

Thanks in advance!

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by aberaud** [comment]
Hi,
This server is a small example tool but is not meant as a full REST proxy implementation,
However OpenDHT now provides a full proxy client and server implementation, accessible using the Python binding.
