### ISSUE TITLE
How do we PUT data onto the DHT Node using curl?

### ISSUE THREAD

**Issue by rsdelhi91** [savoirfairelinux/opendht#404]
Hi,

I am running my DHT node as `dhtnode -b private-IP:port --proxyserver 8080` which starts a DHT Node and registers it to my running network. Now, if I want to place a data onto the DHT Node network I am looking into the POST example provided in the [API Documentation](https://github.com/savoirfairelinux/opendht/wiki/REST-API) page of the wiki here. 

To verify my understanding here, does curl work as `curl -X POST -d "{"test":123}" http://127.0.0.1:8080/testhash` where testhash needs to be a hash value? If yes, how can I generate that hash value? Also, whether there is support for using text here instead?

Some insight into placing values onto the DHT Node network would be highly appreciated. Thank you!

**Comment by aberaud** [comment]
Hi,
You can experiment with the API using the web client at `tools/proxy_node.html` and look at the code or at network requests using the network console in dev tools.

> Also, whether there is support for using text here instead?

yes, you could use testhash as a key and sha1(testhash) will actually be used.

**Comment by rsdelhi91** [comment]
Hey,

Thank you for pointing to proxy_node.html. I'll have a look at it.

> yes, you could use testhash as a key and sha1(testhash) will actually be used.

I tried running `curl -X POST -d "{"test":123}" http://127.0.0.1:8080/testhash` but it keeps returning `{"err":"Incorrect JSON"}`. Am I doing something wrong here by any chance?

**Comment by rsdelhi91** [comment]
I realised that I was using double quotes all the way... `"{"test":123}"`, which should have been `'{"test":123}'`. My mistake. So essentially, the data part that I put in needs to be of this format? - `{"data":"<base64 value of my actual value payload for the key in my URL>","type":0}` or can it be a different format as well? If not, what exactly does `type` here mean?

Also, does the data portion of the json payload need to be a base64 value specifically?

**Comment by binarytrails** [comment]
@rsdelhi91 

Yes, the data needs to be base64 lets say you did ```echo "myvalue" | base64``` you can then, use curl:
```curl -X POST -H "Content-Type: application/json" 127.0.0.1:8080/mykey -d '{"data": "d2FmZmxlcwo="}' -v```

otherwise, send it with httpie in one line:
```echo $(echo "myvalue" | base64 | xargs -i echo '{"data": "{}"}') | http POST 127.0.0.1:8080/mykey```
