### ISSUE TITLE
PUT/GET messages from the DHT Network using SSL/TLS

### ISSUE THREAD

**Issue by rsdelhi91** [savoirfairelinux/opendht#407]
Hi,

I was wondering if there is a way to PUT and GET messages introduced into the DHT network using SSL/TLS or some sort of encryption between the nodes? I can see that there is a functionality of the REST API for OpenDHT called [ENCRYPT](https://github.com/savoirfairelinux/opendht/wiki/REST-API#encrypt) but I'm not sure if it does SSL/TLS communication between nodes.

If this is the answer to how SSL/TLS communication of messages would work, can you please share the relevant curl messages how to PUT/POST (encrypted messages) and GET (decrypted) messages along with the relevant settings to create my network?

Any feedback on this would be highly appreciated. Thanks.

**Comment by binarytrails** [comment]
@rsdelhi91 I think this is exactly what you're looking for: [REST-API#encrypt](https://github.com/savoirfairelinux/opendht/wiki/REST-API#encrypt);
keep in mind that an identity means a pair of keys generated for a specific node ```-i```.

**Comment by rsdelhi91** [comment]
@binarytrails I get that bit, but does that DHT node share those keys with the rest of the DHT network? If I end up starting a DHT node with the `-i` param, it will encrypt and store data. But how does it work with the rest of the nodes being communicated, does it share a secret with all the nodes to enable SSL/TLS communication or rather sharing of encrypted data or does every node need to have its own identity?

For instance, when a message for a key is being inserted into the network at one node having (lets say) `identity 1`, gets encrypted by `identity 1` and it is placed (while encrypted by `identity 1`) in another DHT node having `identity 2`, then does that message get encrypted by `identity 2` as well? If yes, how would `GET` work in terms of decryption?

**Comment by binarytrails** [comment]
@rsdelhi91 the link I sent to you to the wiki's REST-API encrypt section answers your question: 

> Note: If you run another node with another identity, you will not be able to see encrypted data (just signed one)

**Comment by rsdelhi91** [comment]
@binarytrails Extremely sorry, I'm still struggling to understand this concept (especially the Note... it does not elaborate on what exactly is happening from an actual interaction perspective) looking at the example in that section. It says that an identity will be generated for a specific node then how exactly does secure communication happen in OpenDHT if we're running a 3 node cluster let's say? How will the `PUT` and `GET` part work?

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by aberaud** [comment]
Hi,
You can use putEncrypted to use encryption and signature at the data level.
We are investigating adding encryption at the protocol level.
