### ISSUE TITLE
Bootstrap Node (Example?)

### ISSUE THREAD

**Issue by innerop** [savoirfairelinux/opendht#409]
Hi,

The docs do not mention how to run a bootstrap node.

If I do the following in a Python3 script:

import opendht as dht

node = dht.DhtRunner()
node.run()

Where do I specify the port number. Is it missing anything else to act as a bootstrap server?

Thanks,

**Comment by AmarOk1412** [comment]
`node.run(ipv4=ip4, ipv6=ip6, port=p, is_bootstrap=is_bootstrap)`

**Comment by innerop** [comment]
That’s very clear. Thank you. 

Should it be added to Readme for sake of completeness? It seems like missing basic information. Is it documented anywhere?

Looking forward to trying OpenDHT. I heard good things about it!

**Comment by AmarOk1412** [comment]
Feel free to update the README. But indeed a wiki page for that, can be nice.

https://github.com/savoirfairelinux/opendht/tree/master/python/tools contains some examples.

**Comment by aberaud** [comment]
Hi,

Note that no special configuration is needed to run a bootstrap node except the port number. The is_bootstrap flag is experimental and not used by our bootstrap nodes.

The main requirement to run a bootstrap node is that it should have a stable public IP address (or domain name) and port. The port recommended for bootstrap/stable nodes is `4222` (default port used when bootstraping so people can simply use your IP/domain as the bootstrap).

To run a long-running bootstrap node on GNU/Linux the easiest way is with the systemd service, however a python script would do the job just fine :)

**Comment by innerop** [comment]
@aberaud  I believe auto-running a Python script using systemd is straight forward: https://tecadmin.net/setup-autorun-python-script-using-systemd/

@AmarOk1412 I'm not yet very familiar with OpenDHT as a project so my verbalizing may be a bit off, but I'll take a stab at it (for Readme or Wiki, depending on how concise I can make it) once I have a bootstrap DHT node service up and running and can test client put/get successfully from at least two other nodes. Will close this for now. Thank you both for the info.
