### ISSUE TITLE
Pht cache

### ISSUE THREAD

**Issue by sim590** [savoirfairelinux/opendht#41]
After implementing the initial code for the Pht indexation, an optimization for `lookup` operations seemed obvious: a cache of the PHT on the network. A first discussion on the subject led to the following model:

![conception](https://raw.githubusercontent.com/sim590/opendht/conception/doc/conception/PhtCache/concept.png)

@kaldoran, @aberaud: do you have any further suggestions to this model?

**Comment by kaldoran** [comment]
I think you forget the time_point on the cache node, @aberaud explain to me that this time_point (on all node ) is the key of the multimap. 
So we need a time_point into the CacheNode

**Comment by sim590** [comment]
@kaldoran yes, you are right. I fixed it.

**Comment by kaldoran** [comment]
I've got another question,
The Root of the tree should not be a shared_ptr ? 

As long as, if  there is no data in the leaves multimap, we could always access to the first node.

**Comment by sim590** [comment]
If the left and right child of the root do not exist while the root does, then the root is a leaf and there's a shared_ptr in the map pointing to the root. If the root has not been added to the map, the tree is empty and the root is null (cause of weak_ptr) which makes sense. In other words, the existence of the nodes totally depend on the (leaves).

**Comment by kaldoran** [comment]
Ok that seams good to me then, thanks for the explain.
Then i've got no more suggestions for the moment

**Comment by kaldoran** [comment]
Just a little question here, shouldn't we use the name : NodeCache instead of CacheNode to be consistent with the dht Cache Node name ? 
C.f Line : 435 of this file : https://github.com/savoirfairelinux/opendht/blob/master/include/opendht/dht.h

**Comment by sim590** [comment]
The names given in the graph are completely conceptual and you can change them.  However, notice that the class `NodeCache` doesn't refer to the same concept as the class `CacheNode` shown in the graph. The former represents the whole cache while the latter represents a node part of the cache.

**Comment by sim590** [comment]
Closing this as, #56 was merged.
