### ISSUE TITLE
Can't preserve node identity

### ISSUE THREAD

**Issue by AlekseiSmirnov** [savoirfairelinux/opendht#412]
We plan to utilize openDHT for one of our projects.
We were able to run a network of nodes but faced several questions and problems:

1) We need to preserve the identity of the node. But when we run 
`dhtnode -b  private_ip -p 4222 -v -i -f 'test'`
it seems that -f parameter doesn't work, as the test file where node state should be dumped is not even created.

each time we execute the command, different `Public key ID's` are assigned. How do we preserve the public key?

2) is it possible to directly specify identity key pair if I already have a pair of keys generated?

3) There is a ` --proxyserver` parameter mentioned in the [documentation](https://github.com/savoirfairelinux/opendht/wiki/REST-API), but `man dhtnode` doesn't tell anything about it. What's this parameter exactly stands for?

4) we created a private network consisting of two nodes on two different servers. In some time one of the nodes spawns the third node at the different port. Why does this 3rd node appear?

Thanks in advance for your answers

**Comment by AmarOk1412** [comment]
@AlekseiSmirnov I let @aberaud answer for 1 and 2, a patch will come for you

3. Indeed the man is not complete. But --proxyserver will make your node available via http (`--proxyserver 8000` will launch the REST interface available through http://nodeip:8000) The doc is here https://github.com/savoirfairelinux/opendht/wiki/REST-API

4. I never see that and a dhtnode never launch another node. So can you give more details about that. What do you see exactly/how to reproduce/etc

**Comment by aberaud** [comment]
@AlekseiSmirnov I pushed a few commits to master:
* Added dhtnode arguments to load/save certificate & private key
  - `--certificate file.crt` to specify a certificate file
  - `--privkey file.pem` to specify a private key file
  - `--privkey-password passwd` to specify a private key password (if necessary)
  - `--save-identity file` to save identity generated with `-i` to file prefix. If `--privkey-password` is specified it is used to encrypt the private key.
* Improved manpage for dhtnode and the wiki page https://github.com/savoirfairelinux/opendht/wiki/Running-a-node-with-dhtnode
* Improved signal handling in dhtnode to perform graceful shutdown when receiving `SIGTERM` in CLI mode. dhtnode now performs graceful shutdown (allowing to save the state to file) in two cases:
  - in CLI when receiving end of file (`CTRL+D`)
  - in every mode when receiving `SIGTERM`

**Comment by AlekseiSmirnov** [comment]
Thank you @aberaud! 
Now everything works as expected. Couldn't reproduce a problem with 3d node anymore, if I face it again, will create another issue.
