### ISSUE TITLE
Could NOT find Restinio (missing: Restinio_INCLUDE_DIR)

### ISSUE THREAD

**Issue by brailateo** [savoirfairelinux/opendht#418]
Tried compiling on Ubuntu 18.04 64 bit with options:

cmake -DOPENDHT_PYTHON=ON -DCMAKE_INSTALL_PREFIX=/usr -DOPENDHT_PROXY_SERVER=ON -DOPENDHT_PROXY_CLIENT=ON ..

Error is:
```
. . .
. . .
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find Restinio (missing: Restinio_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  cmake/FindRestinio.cmake:9 (find_package_handle_standard_args)
  CMakeLists.txt:63 (find_package)
```

**Comment by AmarOk1412** [comment]
@brailateo please look at the README.md, for the REST API (`-DOPENDHT_PROXY_SERVER=ON -DOPENDHT_PROXY_CLIENT=ON`), restinio is necessary (it replace restbed from previous versions). Now restbed is unused. 

Note that the wiki is not up-to-date on this point (cc @binarytrails)

**Comment by binarytrails** [comment]
@brailateo 

Here is how to install it:
https://github.com/savoirfairelinux/opendht/blob/master/docker/DockerfileDeps#L23

**Comment by rsdelhi91** [comment]
Trying the commands given in: https://github.com/savoirfairelinux/opendht/blob/master/docker/DockerfileDeps#L23

gives me the following errors:

```
> cmake -DCMAKE_INSTALL_PREFIX=/usr -DRESTINIO_TEST=OFF -DRESTINIO_SAMPLE=OFF              -DRESTINIO_INSTALL_SAMPLES=OFF -DRESTINIO_BENCH=OFF -DRESTINIO_INSTALL_BENCHES=OFF              -DRESTINIO_FIND_DEPS=ON -DRESTINIO_ALLOW_SOBJECTIZER=Off -DRESTINIO_USE_BOOST_ASIO=none .
-- Boost version: 1.58.0
-- Found the following Boost libraries:
--   regex
-- Found Boost for regex.
CMake Error at CMakeLists.txt:71 (find_package):
  By not providing "Findfmt.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "fmt", but
  CMake did not find one.

  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.


-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/restinio-v.0.5.1.1/dev/CMakeFiles/CMakeOutput.log".

**Comment by binarytrails** [comment]
@rsdelhi91 you still need to ```make install``` the restinio header files. please, see this PR:
https://github.com/savoirfairelinux/opendht/pull/424/files#diff-976e39bbf51c94418a2ef723dd9fff4fR42

**Comment by binarytrails** [comment]
@rsdelhi91 there is couple of fixes for this docker that are currently in review in the PR #424. besides, your error indicates that libfmt is not found which is a dependency that you have to install. also, you can use conan to install restinio as well by checking their repo: [Stiffstream/restinio-conan-example](https://github.com/Stiffstream/restinio-conan-example)

**Comment by aberaud** [comment]
@rsdelhi91 try `sudo apt install libfmt-dev libhttp-parser-dev` or a similar command to install `libfmt` and  `libhttp-parser` development files&library on your system

**Comment by brailateo** [comment]
Succeeded! Thanks a lot!
Teo
