### ISSUE TITLE
[PHT] Multi dimensional key support

### ISSUE THREAD

**Issue by sim590** [savoirfairelinux/opendht#44]
As of now, only unidimensional keys are supported, i.e. keys containing only **one field**. Having support for multidimensionnal keys could enlarge the range of use cases of the PHT indexation feature. This is also a sort of optimization for incomplete queries which could be resolved faster using a [z-curve][] linearization (interleaving bits on diffrent fields of the key) for e.g.

[z-curve]: https://en.wikipedia.org/wiki/Z-order_curve

**Comment by kaldoran** [comment]
In the next few week i will start working on it, with Adrien we start figure out what method would be the better one and a solution comes out. 
I'm going to create a new structure that will encode unknown bit and known one. 
Then the lookupstep going to look for both version a prefix if a value is not given.

**Comment by kaldoran** [comment]
,

**Comment by kaldoran** [comment]
Work in progress on that, for the moment i can transform Prefix on 1 bit to Prefix on 2 bit ( 1 bit indicate if the value is known, the second one indicate the value ) and vice-versa.

Next step : Change the lookupStep and make it work with prefix on 2 bit. ( without changing the algorithm), then change algorithm for lookup on prefix with 2 bit ( with some bit unknown).
