### ISSUE TITLE
Rate limiting enhancements

### ISSUE THREAD

**Issue by linas** [savoirfairelinux/opendht#460]
I'd like to propose a set of rate-limiting enhancements, which I'm willing to code, as I want them. (I'll need some handholding and feedback, being a newbie to the codebase.)

Motivation: I'm developing/testing an app on top of DHT (this one: https://github.com/opencog/atomspace-dht) and ran into several issues. My testing is on the local (private) network (just localhost, actually) and I'd like to `put()` as fast as possible. The current rate-limiter prevents DHT daemons from receiving more than 10 or 20 or something Values per second. (I'd love to get to as-fast-as-possible, e.g. 2K/second or better.)

The rate limiter also affects `get()`, indirectly: if I do 25 `get()` as fast as possible, the responses also seem to be lost.  Not sure where.  Even if the data is on the local node, the `get()`'s still get lost.

I propose being able to set different rate-limits on a per-host and per-address-range basis. 

To mitigate DDOS, it might even be wise to set rate-limits based on whether a node is trusted or not (I have not yet played with node trust in OpenDHT, I assume its possible?)

**Comment by aberaud** [comment]
Implemented in https://github.com/savoirfairelinux/opendht/commit/cb7d7f6614d68b84aa72b76931af3a50a4cc4e79

**Comment by linas** [comment]
Thank you. With this change, (and setting 
```
 _config.dht_config.node_config.max_req_per_sec = -1;
 _config.dht_config.node_config.max_peer_req_per_sec = -1;
```
 I no longer get ` Dropping request due to rate limiting` messages printed!

That's the good news. The bad news is that I still get intermittent data loss, unless I add sleeps so that `runner.get()` and/or `runner.put()` is called less than about 400 times/sec.  I do not yet understand why this happens.  This is related to #461 and specifically to  https://github.com/savoirfairelinux/opendht/issues/461#issuecomment-562903421

I'm going to close this, since the original issue seems to be solved. 

(Although there is another whiz-bang enhancement possible: provide a public API to `IpLimiterMap address_rate_limiter;` so that rates on `localhost` are unlimited, rates on the local network can be high, rates to remote machines can be lower, etc. I don't need this now, but it seems like a whizzy feature to have.)
