### ISSUE TITLE
Enhancement: flush and shutdown

### ISSUE THREAD

**Issue by linas** [savoirfairelinux/opendht#461]
I'm having problems with transient DHT nodes, and would like to have reliable, dependable flush and shutdown.  The issue is this: I'd like to have a node appear on the network, publish a bunch of data, and then promptly disappear from the network.  I'd like to get all of that data pushed out of the local node, and then exit only after it appears that it's all been pushed.

What I've learned so far:
* `DhtRunner()::join()` clobbers the `pending_ops` and `pending_ops_prio` (lines 266-267)
   so anything queued is lost.  This is OK,I guess, but should be documented, as it is a surprise.
* One can work around this by calling `DhtRunner::loop_()` twice. The first time, it flushes  
  `pending_ops_prio` and the second time it flushes `pending_ops`. This should be 
   documented,  as it's hard to understand.  Better yet, there should be an explicit
   `DhtRunner::flush()` call that does this.
* I was unable to find any method, anywhere, that forces local data out onto the net.
   This is what I really want/need.
* The `ShutdownCallback` is not always called. I was hoping to use this as a guaranteed
   syncpoint, but no luck. For example, calling `cv->notify_one()` from the `ShutdownCallback`
   can sometimes result in hangs.

I'm willing to submit patches that address some of these issues, but would need some guidance ...

**Comment by aberaud** [comment]
Hi and thanks for your input,
I will investigate these issues,
in particular ShutdownCallback should always be called

**Comment by linas** [comment]
I discovered the test case where `ShutdownCallback` is never called. 

My test setup involves two nodes, both on localhost one on port 4444 the other on port 4242. The second one is told to bootstrap from the first. This is supposed to be a "private net", for my testing only. Last night, I left it running. This morning, there were 30 external IP's who had contacted these servers and left data with them. I think it's Jami, and its doing a port-scan and finds my private net. One the system reaches this state, then `ShutdownCallback` is never called.

Well -- I can't say "never" -- I've waited 5-10 minutes, and it hasn't been called.  Maybe the system is trying to contact the 30 different IP's, and some of those IP's are not responding?  That could certainly lead to a situation where the system is blocked from making forward progress...

**Comment by aberaud** [comment]
Do you use `maintain_storage` ? If so, can you try without it ?

**Comment by linas** [comment]
No, I have not altered `maintain_storage`.  The missing `ShutdownCallback` still occurs if I work with a private (non-default) `NetId`.   If all of the nodes sit idle for 5-10 minutes, and then shutdown is done on one, the callback is never called.  The other node thinks it's still connected:
```
IPv4 stats:
Known nodes: 1 good, 0 dubious, 1 incoming.
```

**Comment by aberaud** [comment]
Hi,
On latest master, shutdown will only complete when all pending `get` and `put` operation have completed and their done callbacks have been called.

This should allow to simply run a node, perform some operations and shutdown without the risk of uncompleted operations.

**Comment by linas** [comment]
I will test in the next day or two.

**Comment by linas** [comment]
Spent the day testing. I have not yet fully reproduced all the conditions that lead to the original failures.  Part of the issue is that rate-limiting is also contributing to data-loss (in my code), and so I have to revisit/re-design how that works (in my code).

I'm going to close this issue, as it is confusing, and open new issues if/when/as problems come up.

Anyway, thanks!

**Comment by linas** [comment]
I may have been too quick to close this.  If I do
```
runner.shutdown(calback);
... wait for the callback to be called ..
runner.join();
```
then I *consistently* lose data.
If instead I sleep:
```
runner.shutdown(calback);
... wait for the callback to be called ..
sleep(2);
runner.join();
```
then data loss is usually (almost always?) avoided.  I do not yet understand why this is so.  But clearly, something is happening in some thread, after the shutdown ...

**Comment by linas** [comment]
I just now realized that my intermittent data loss is almost surely UDP packet loss! Aieee!
