### ISSUE TITLE
Thread safety issues

### ISSUE THREAD

**Issue by linas** [savoirfairelinux/opendht#463]
I'm having several thread-safety issues with OpenDHT.  I have not yet found all of them, but one seems to be that `dht::crypto::generateIdentity()` is not thread-safe. When invoked from multiple threads, it crashes on a bizzarro linker bug, where an unexpected `realloc()` is called from outer space.  I reported this to guile, thinking it was another component, but it now seems clear that it's DHT related ... https://debbugs.gnu.org/cgi/bugreport.cgi?bug=38041

Placing a global lock around `dht::crypto::generateIdentity()`  fixes that crash; but there are others.

**Comment by linas** [comment]
Err, well, maybe its gnutls that is not thread-safe!? But its hard to debug when misc deep libraries misbehave... OpenDHT should always be thread safe...

**Comment by linas** [comment]
Closing ... I just attempted a simple, staond-alone test to report this with, and the stand-alone test is not failing.  Hmmm...

**Comment by linas** [comment]
My stand-alone multi-threaded OpenDHT unit test passes (it creates 16 instances of `dht::Runner`, one in each thread, without any locks, and does 5000 puts in each thread. Works great).
 
My full-system test, which links to guile, python3, OpenDHT and several other libs, runs fine, multi-threaded, with ONE instance of `dht::DhtRunner`, shared from 6 threads, and zero locks around the runner, doing thousands of gets, puts, and multiple ValueTypes with policies: works great, no problems! Excellent!

My simulated multi-user test 6 threads, SIX instances of `dht::DhtRunner`, crashes before I even run any of them!  The first crash occurs in `dht::crypto::generateIdentity()` and putting a lock around this to serialize calls avoids the crash.   Once this is fixed, the second call to `dht::DhtRunner::run()` on the second instance of `dht::DhtRunner` in it's own thread crashes.  Putting a lock around this, to serialize it, does NOT prevent the second crash!

I don't understand how this can happen.  The symptoms are that its some kind of crazy linker-loader bug... but why would there be linker-loader bugs?

**Comment by linas** [comment]
OK, so avoiding the call to dht::crypto::generateIdentity();` stops the crazy crash.   I conclude the bug is some crazy interaction between BoehmGC and nettle.  Sorry for the noise.

**Comment by aberaud** [comment]
Thanks a lot for reporting your findings. Good to know `dht::DhtRunner` behaves well in a multithreaded environment.

Strange that `dht::crypto::generateIdentity()` crashes if called from multiple threads. I would prefer to not put a lock in it since it takes quite some time to execute.

I made a few tests and couldn't reproduce the issue on Ubuntu 19.10 (GnuTLS 3.6.9 and Nettle 3.4.1)
