### ISSUE TITLE
License

### ISSUE THREAD

**Issue by KrishnaPG** [savoirfairelinux/opendht#467]
This looks good, but one request: Could you please consider MIT / BSD / Apache license? 

Would like to create NodeJS bindings for this, and GPL would not be a right fit. 

Also, it seems the [https://github.com/jech/dht](https://github.com/jech/dht), which was acknowledged as this project is based on, is MIT licensed. Re-licensing this project as MIT (or any of its peer licenses) could greatly improve the reachability of this for developer integration. Please consider.

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by KrishnaPG** [comment]
Yes
