### ISSUE TITLE
OSX 10.9.5 linking with gnutls issue (using brew and cmake)

### ISSUE THREAD

**Issue by Tulerpeton** [savoirfairelinux/opendht#47]
I've built opendht for Fedora and for Windows without any problems, tested a little data sharing code, and it runs almost fine, the problem is with OSX Mavericks, I've installed gnutls with "brew install gnutls", got everything in /usr/local/lib 
_libgnutls.dylib, libgnutls.30.dylib, libgnutlsxx.28.dylib, libgnutlsxx.dylib_

I use:
cmake -DOPENDHT_PYTHON=OFF -DCMAKE_INSTALL_PREFIX=/usr/local ..
make opendht

Compilation running fine, but linking opendht with gnutls falls in error. 

[100%] Linking CXX shared library libopendht.dylib
clang: warning: argument unused during compilation: '-pthread'
Undefined symbols for architecture x86_64:
  "_gnutls_fingerprint", referenced from:
      dht::InfoHash::get(unsigned char const*, unsigned long) in infohash.cpp.o
      dht::Dht::makeToken(sockaddr const*, bool) const in dht.cpp.o

Do I miss something ?
Thanx.

**Comment by sim590** [comment]
I have managed to reproduce the exact same bug on another mac osx computer with homebrew. Issuing the following command showed the the version of homebrew's gnuttls was okay:
```sh
nm /usr/local/lib/libgnutls.dylib | grep "_gnutls_fingerprint"
...
```
Finally, as explained in #50, it appears that on macosx, the linking flags are not deduced from the dependencies.
