### ISSUE TITLE
Error in make

### ISSUE THREAD

**Issue by kuabhish** [savoirfairelinux/opendht#474]
`
/home/dragon/opendht/src/peer_discovery.cpp:25:10: fatal error: asio.hpp: No such file or directory
 #include <asio.hpp>
`

**Comment by binarytrails** [comment]
It says that you need Asio standalone dependency since you're using Peer Discovery.

**Comment by BITXUJI** [comment]
some error

**Comment by kuabhish** [comment]
`
/home/dragon/opendht/include/opendht/crypto.h:26:10: fatal error: gnutls/gnutls.h: No such file or directory
 #include <gnutls/gnutls.h>
`
Now I am getting this?

**Comment by kuabhish** [comment]
> some error
Please Try this  : 

        wget https://github.com/aberaud/asio/archive/b2b7a1c166390459e1c169c8ae9ef3234b361e3f.tar.gz \
        && tar -xvf b2b7a1c166390459e1c169c8ae9ef3234b361e3f.tar.gz && cd asio-b2b7a1c166390459e1c169c8ae9ef3234b361e3f/asio \
        && ./autogen.sh && ./configure --prefix=/usr --without-boost --disable-examples --disable-tests  \
        && sudo make install \

**Comment by AmarOk1412** [comment]
GNUTls is necessary (cf README)

**Comment by kuabhish** [comment]
> GNUTls is necessary (cf README)

It worked by building in /lib directory?

But  I want to know  why can't I import opendht with python  ??

**Comment by binarytrails** [comment]
@kuabhish

First for all, if you're fairly new to the C++ build systems, I would suggest you to use a packet manager to install it which has all of the dependencies as requirements.

If you wish to continue this manual build path, please read the instructions from the README: https://github.com/savoirfairelinux/opendht#how-to-build-and-install
