### ISSUE TITLE
segfault in dhtnode during pp key1 test

### ISSUE THREAD

**Issue by snblitz** [savoirfairelinux/opendht#484]
I have a debian 10 based 4 node cluster setup using dhtnode.  'p' and 'g' work as expected, but 'pp' causes a seg fault.

>> ll
OpenDHT node da08d1c9ba4750d614d6f8f8aed24b19de6a9f22 running on port 4222
0 ongoing operations
IPv4 stats:
Known nodes: 3 good, 0 dubious, 0 incoming.

IPv6 stats:
Known nodes: 0 good, 0 dubious, 0 incoming.

>> pp key1 test

Using h(key1) = 1073ab6cda4b991cd29f9e83a307f34004ae9327
>> [494940.634791] put: adding 1073ab6cda4b991cd29f9e83a307f34004ae9327 -> Value[id:9bca0a0a3d139657 data(text/plain):"test"]
[494940.634911] [search 1073ab6cda4b991cd29f9e83a307f34004ae9327 IPv4] new search
[494940.634951] [search 1073ab6cda4b991cd29f9e83a307f34004ae9327 IPv4] refilled search with 3 nodes from node cache
[494940.635009] [search 1073ab6cda4b991cd29f9e83a307f34004ae9327 IPv6] new search
[494940.635152] [search 1073ab6cda4b991cd29f9e83a307f34004ae9327 IPv6] no nodes from cache while refilling search
[494940.635525] [search 1073ab6cda4b991cd29f9e83a307f34004ae9327 IPv6] expired
[494940.635559] Announce done IPv6 0
[494940.635641] [node f7f37092ea2a3ea1b3c6c0a73f787e6acc81312f 178.128.68.154:4222] sending [find da08d1c9ba4750d614d6f8f8aed24b19de6a9fd4] for neighborhood maintenance
zsh: segmentation fault (core dumped)  dhtnode -p 4222 -v

Here is the stack trace from the fault

Core was generated by `dhtnode -p 4222 -v'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fd787a045b8 in dht::operator<<(std::ostream&, dht::Select const&) ()
   from /usr/lib/libopendht.so.2
[Current thread is 1 (Thread 0x7fd785c4e700 (LWP 26386))]
(gdb) bt full
#0  0x00007fd787a045b8 in dht::operator<<(std::ostream&, dht::Select const&) ()
   from /usr/lib/libopendht.so.2
No symbol table info available.
#1  0x00007fd7879c6384 in dht::Query::toString[abi:cxx11]() const ()
   from /usr/lib/libopendht.so.2
No symbol table info available.
#2  0x00007fd7879b3385 in dht::Dht::searchSendAnnounceValue(std::shared_ptr<dht::Dht::Search> const&) () from /usr/lib/libopendht.so.2
No symbol table info available.
#3  0x00007fd7879bb88b in dht::Dht::searchStep(std::shared_ptr<dht::Dht::Search>) ()
   from /usr/lib/libopendht.so.2
No symbol table info available.
#4  0x00007fd7879cb13a in std::_Function_handler<void (), std::_Bind<void (dht::Dht::*(dht::Dht*, std::shared_ptr<dht::Dht::Search>))(std::shared_ptr<dht::Dht::Search>)> >::_M_invoke(std::_Any_data const&) () from /usr/lib/libopendht.so.2
No symbol table info available.
#5  0x00007fd7879a5f40 in dht::Dht::periodic(unsigned char const*, unsigned long, dht::SockAddr, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&) () from /usr/lib/libopendht.so.2
No symbol table info available.
#6  0x00007fd7879ca26e in dht::Dht::periodic(unsigned char const*, unsigned long, sockaddr const*, unsigned int, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long, std::ratio<1l, 1000000000l> > > const&) ()
   from /usr/lib/libopendht.so.2
No symbol table info available.
#7  0x00007fd787a25de5 in dht::DhtRunner::loop_() () from /usr/lib/libopendht.so.2
No symbol table info available.
#8  0x00007fd787a25ffa in std::thread::_State_impl<std::thread::_Invoker<std::tuple<dht::DhtRunner::run(dht::DhtRunner::Config const&, dht::DhtRunner::Context&&)::{lambda()#2}> > >::_M_run() () from /usr/lib/libopendht.so.2
No symbol table info available.
#9  0x00007fd787452b2f in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
No symbol table info available.
#10 0x00007fd787522fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {140563638970112, 
                -4476849590761029165, 140734735255998, 140734735255999, 
                140563638970112, 140734735256320, 4499098834585387475, 
                4499104413184688595}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 
              0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#11 0x00007fd7871304cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95

**Comment by aberaud** [comment]
thanks, fixed in master
