### ISSUE TITLE
Data serialization with data structures

### ISSUE THREAD

**Issue by eric-m-chan** [savoirfairelinux/opendht#485]
I am trying to properly `get` a data structure from the DHT. I am following the examples from the data serialization wiki page, but I am running into some problems. I have the following code:

```
struct MyClass {
    std::string m_str;
    int m_int;

    MyClass(std::string myStr, int myInt);
    // implements msgpack-c serialization methods
    MSGPACK_DEFINE(m_str, m_int);
};

MyClass(std::string myStr, int myInt) {
    m_str = myStr;
    m_int = myInt;
}

int main() {
    dht::DhtRunner node;
    // ... I have properly bootstrapped etc. Works with regular values

    MyClass data("cats", 42);
    node.put("unique_key", data);
    //Do this because get does not work with string parameter
    dht::InfoHash myIH("unique_key");

    node.get<MyClass>(myIH, [](MyClass&& MyObject) {
        printf("Entering callback...\n");
    });
}
```

This compiles, but never enters the callback. I have two suspicions: (1) I am not properly calling ` dht::InfoHash myIH("unique_key");`, or (2) my lambda `[](MyClass&& MyObject)` is incorrect. There is no mention of (1) in the wiki, and I took (2) directly from the wiki. Thus, I am not sure how to fix xthis problem

**Comment by lucvrgdias** [comment]
try using node.put ("unique_key", dht :: Value :: pack <MyClass> (data)). dht :: Value :: pack serializes data

**Comment by aberaud** [comment]
Make sure your class is default-constructible
