### ISSUE TITLE
Building from source - a nightmare , as my previous attempt :-(

### ISSUE THREAD

**Issue by brailateo** [savoirfairelinux/opendht#506]
Ubuntu 20.04 

Done
```
# Install OpenDHT dependencies
sudo apt install libncurses5-dev libreadline-dev nettle-dev libgnutls28-dev libargon2-0-dev libmsgpack-dev librestbed-dev libjsoncpp-dev
sudo apt-get install cython3 python3-dev python3-setuptools
```
But seems it's not enough. Needed to add libssl manually! Needed to build restinio (it's a nightmare also).
Tried to build with PROXY_SERVER. 
Got errors:

cmake -DOPENDHT_PYTHON=ON -DOPENDHT_PROXY_SERVER=ON  -DRestinio_INCLUDE_DIR=/home/teo/Work/teste/restinio/dev/target/gcc_9_3_0__x86_64_linux_gnu/release/lib  -DCMAKE_INSTALL_PREFIX=/usr ..
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Found Argon2:  (found version "20171227")
-- Found OpenSSL 1.1.1f
Indexation enabled since it is required for Python support
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
FMT_LIBRARY
    linked by target "opendht" in directory /home/teo/Work/teste/opendht
    linked by target "opendht-static" in directory /home/teo/Work/teste/opendht
HTTP_PARSER_LIBRARY
    linked by target "opendht" in directory /home/teo/Work/teste/opendht
    linked by target "opendht-static" in directory /home/teo/Work/teste/opendht

Too bad that OpenDHT has not a "ready to eat" binary distribution that does everything.
I was watching RING and now  Jami, hoping that someday, I might find an executable, statically build, that don't rely on other libraries and so's, that can be installed with just a wget, a single, unique executable (like Telegram executabile, that runs everywhere), that runs a node, allow me to communicate and use it through a simple, REST interface from any language and framework.

OpenDHT might have been used hundred times more that now, all of us need a good DHT and pub/sub from behind routers, make distributed  programs work. :-(

Teo

**Comment by aberaud** [comment]
Hi and thanks for the feedback,

Following your comments, I updated the build instructions to add Ubuntu 20.04. We might also start packaging OpenDHT in official Jami repos.

Our default Dockerfiles have been using Ubuntu 20.04 for a few weeks:
https://github.com/savoirfairelinux/opendht/blob/master/docker/DockerfileDeps

I updated the docker images so they include proxy support.

You can use the Dockerfile `aberaud/opendht` as a base for opendht-based projects, it includes installed pre-built static and dynamic libraries as well as headers.
`aberaud/opendht-deps` includes all the necessary dependencies to build OpenDHT itself.
We're also working with the Debian community to get OpenDHT updated in Debian.

**Comment by brailateo** [comment]
That's good news! I am compiling now opendht following your build instructions for 20.04.
I'll try also the docker version, thanks for your support!
Teo
