### ISSUE TITLE
Increase max values stored for a given key to a large number in Ubuntu 20.04+

### ISSUE THREAD

**Issue by rsdelhi91** [savoirfairelinux/opendht#514]
Hi,

I'm using the latest build for Ubuntu 20.04 and have setup a small OpenDHT cluster. I am trying to increase the limit on the number of objects that can be stored on the DHT nodes, similar to what I asked in this issue: https://github.com/savoirfairelinux/opendht/issues/426

What's would be the recommended way to do this in the current build of OpenDHT? Do I need to update any parameters when building the library for OpenDHT?

Also, is it possible to do this via the CLI tool - `dhtnode` ? It would be highly flexible if this is supported or can be leveraged in any manner.

**Comment by ghenry** [comment]
Much larger number available now in latest release. Thanks!
