### ISSUE TITLE
 "vector iterators incompatible" exception in search.h

### ISSUE THREAD

**Issue by Ventastega** [savoirfairelinux/opendht#515]
There is a bug in search.h the method insertNode raise an exception (MSVC) : "vector iterators incompatible".
After node.resize the comparison (n >= t) is not valid anymore because of iterator invalidation.

```
        if (full) {
            if (t != nodes.cend())
                nodes.resize(std::distance(nodes.cbegin(), t));
            if (n >= t)
                return false;
        }
```

**Comment by aberaud** [comment]
should be fixed by https://github.com/savoirfairelinux/opendht/commit/a69863da4eec4d4c6be8ad59795a68ea988b7394

**Comment by Ventastega** [comment]
Merci beaucoup :-)
