### ISSUE TITLE
Get Python bindings completed

### ISSUE THREAD

**Issue by manu56** [savoirfairelinux/opendht#518]
Is it possible to complete the Python3 bindings ?

It seems that functions such as put_signed and put_encrypted are not accessible from Python.
Is there any work planed about that ?

**Comment by ghenry** [comment]
Still a requirement?  

Thanks.

**Comment by gkarsai** [comment]
Yes, it would be great to use put(...permanent=True),cancel_put(...), peer discovery.... Thanks!

**Comment by aberaud** [comment]
Hi,
Just released 3.1 which adds many missing features to the Python binding, including permanent put, cancelPut, and new configuration in DhtRunnerConfig to support peer discovery.
Working on adding put_signed and put_encrypted for the next release.

**Comment by aberaud** [comment]
Also added putSigned and putEncrypted in 3.1.2 :)
Closing the ticket, please open a new ticket if other required APIs are missing in the Python binding.
