### ISSUE TITLE
Any public network?

### ISSUE THREAD

**Issue by bakwc** [savoirfairelinux/opendht#523]
Hi!

Is there any public opendht network exists? What is bootstrap node?

If not - may be it's a good idea to setup an official general purpose public opendht network? What do you think?

**Comment by aberaud** [comment]
Hi,
You can use `bootstrap.jami.net` as a bootstrap address for the public OpenDHT network.

Best regards

**Comment by bakwc** [comment]
Thank you! Please consider adding this information to README.md
