### ISSUE TITLE
Cannot Complile. error: ‘ASN1_time_parse’ was not declared in this scope

### ISSUE THREAD

**Issue by meatshooter** [savoirfairelinux/opendht#529]
-- Checking for one of the modules 'openssl'
-- Found OpenSSL 1.1.1g

Here is the log:

[ 96%] Building CXX object CMakeFiles/opendht.dir/src/compat/os_cert.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DASIO_STANDALONE -DOPENDHT_BUILD -DOPENDHT_JSONCPP -DOPENDHT_LOG=true -DOPENDHT_PEER_DISCOVERY -DOPENDHT_PROXY_CLIENT -DOPENDHT_PROXY_SERVER -DOPENDHT_PUSH_NOTIFICATIONS -DPACKAGE_VERSION=\"2.1.6\" -Dopendht_EXPORTS -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/. -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include/opendht -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999_build/include -isystem /usr/include/jsoncpp   -DNDEBUG -O2 -pipe -Wno-return-type -Wall -Wextra -Wnon-virtual-dtor -pedantic-errors -fvisibility=hidden -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -fPIC   -std=gnu++14 -o CMakeFiles/opendht.dir/src/compat/os_cert.cpp.o -c /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/compat/os_cert.cpp
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp: In function ‘time_t dht::http::parse_ocsp_time(ASN1_GENERALIZEDTIME*)’:
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp:210:9: error: ‘ASN1_time_parse’ was not declared in this scope; did you mean ‘ASN1_item_free’?
  210 |     if (ASN1_time_parse((const char*)gt->data, gt->length, &tm, V_ASN1_GENERALIZEDTIME) == -1)
      |         ^~~~~~~~~~~~~~~
      |         ASN1_item_free
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp: In lambda function:
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp:482:125: error: invalid use of incomplete type ‘X509_STORE_CTX’ {aka ‘struct x509_store_ctx_st’}
  482 |                         ocspVerified = ocspValidateResponse(*ocspInfo, chain, ocspResp.body, ctx.native_handle()->ctx, logger);
      |                                                                                                                 ^~

In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/conf.h:13,
                 from /usr/include/asio/ssl/detail/openssl_types.hpp:23,
                 from /usr/include/asio/ssl/context_base.hpp:19,
                 from /usr/include/asio/ssl/context.hpp:23,
                 from /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include/opendht/http.h:32,
                 from /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp:19:
/usr/include/openssl/ossl_typ.h:129:16: note: forward declaration of ‘X509_STORE_CTX’ {aka ‘struct x509_store_ctx_st’}
  129 | typedef struct x509_store_ctx_st X509_STORE_CTX;
      |                ^~~~~~~~~~~~~~~~~
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp: In lambda function:
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp:1388:46: warning: unused parameter ‘resp’ [-Wunused-parameter]
 1388 |     add_on_done_callback([&](const Response& resp){
      |                              ~~~~~~~~~~~~~~~~^~~~
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/compat/os_cert.cpp: In function ‘void dht::http::addSystemCaCertificates(SSL_CTX*, const std::shared_ptr<dht::Logger>&)’:
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/compat/os_cert.cpp:151:11: warning: unused variable ‘x509cert’ [-Wunused-variable]
  151 |     X509* x509cert;
      |           ^~~~~~~~
make[2]: *** [CMakeFiles/opendht.dir/build.make:356: CMakeFiles/opendht.dir/src/http.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999_build'
make[1]: *** [CMakeFiles/Makefile2:116: CMakeFiles/opendht.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999_build'
make: *** [Makefile:150: all] Error 2

**Comment by meatshooter** [comment]
Still not compilling.
By the way, "ASN1_time_parse" is used in src/http.cpp, may be 
[ 96%] Building CXX object CMakeFiles/opendht.dir/src/compat/os_cert.cpp.o was wrong place because of parallel build, I am not sure. 

I think that ASN1_time_parse should be moved/copied from src/compat/os_cert.cpp to src/http.cpp (or something like this)
Thanks!

P.S. I switched off parallel build, now log is the following: 


[ 88%] Building CXX object CMakeFiles/opendht.dir/src/http.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DASIO_STANDALONE -DOPENDHT_BUILD -DOPENDHT_JSONCPP -DOPENDHT_LOG=true -DOPENDHT_PEER_DISCOVERY -DOPENDHT_PROXY_CLIENT -DOPENDHT_PROXY_SERVER -DOPENDHT_PUSH_NOTIFICATIONS -DPACKAGE_VERSION=\"2.1.7\" -Dopendht_EXPORTS -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/. -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include/opendht -I/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999_build/include -isystem /usr/include/jsoncpp   -DNDEBUG -O2 -pipe -Wno-return-type -Wall -Wextra -Wnon-virtual-dtor -pedantic-errors -fvisibility=hidden -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -fPIC   -std=gnu++14 -o CMakeFiles/opendht.dir/src/http.cpp.o -c /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp: In function ‘time_t dht::http::parse_ocsp_time(ASN1_GENERALIZEDTIME*)’:
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp:227:9: error: ‘ASN1_time_parse’ was not declared in this scope; did you mean ‘ASN1_item_free’?
  227 |     if (ASN1_time_parse((const char*)gt->data, gt->length, &tm, V_ASN1_GENERALIZEDTIME) == -1)
      |         ^~~~~~~~~~~~~~~
      |         ASN1_item_free
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp: In lambda function:
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp:499:125: error: invalid use of incomplete type ‘X509_STORE_CTX’ {aka ‘struct x509_store_ctx_st’}
  499 |                         ocspVerified = ocspValidateResponse(*ocspInfo, chain, ocspResp.body, ctx.native_handle()->ctx, logger);
      |                                                                                                                 ^~

In file included from /usr/include/openssl/crypto.h:25,
                 from /usr/include/openssl/bio.h:20,
                 from /usr/include/openssl/conf.h:13,
                 from /usr/include/asio/ssl/detail/openssl_types.hpp:23,
                 from /usr/include/asio/ssl/context_base.hpp:19,
                 from /usr/include/asio/ssl/context.hpp:23,
                 from /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/include/opendht/http.h:32,
                 from /var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp:19:
/usr/include/openssl/ossl_typ.h:129:16: note: forward declaration of ‘X509_STORE_CTX’ {aka ‘struct x509_store_ctx_st’}
  129 | typedef struct x509_store_ctx_st X509_STORE_CTX;
      |                ^~~~~~~~~~~~~~~~~
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp: In lambda function:
/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999/src/http.cpp:1406:46: warning: unused parameter ‘resp’ [-Wunused-parameter]
 1406 |     add_on_done_callback([&](const Response& resp){
      |                              ~~~~~~~~~~~~~~~~^~~~
make[2]: *** [CMakeFiles/opendht.dir/build.make:356: CMakeFiles/opendht.dir/src/http.cpp.o] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999_build'
make[1]: *** [CMakeFiles/Makefile2:116: CMakeFiles/opendht.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-libs/opendht-9999/work/opendht-9999_build'
make: *** [Makefile:150: all] Error 2

**Comment by meatshooter** [comment]
@aberaud, please take a look

**Comment by aberaud** [comment]
should be fixed with 2.1.8

**Comment by meatshooter** [comment]
works now, thanks!
