### ISSUE TITLE
Routing table gives incorrect result in some cases.

### ISSUE THREAD

**Issue by SmnTin** [savoirfairelinux/opendht#533]
https://github.com/savoirfairelinux/opendht/blob/2524e167d9621a92832763105503568638c80f5e/src/routing_table.cpp#L133

I used this implementation as a reference in my uni project. I wrote a simple test to try out the implementation that was pretty straightforward. It just fills the routing table with random hashes and then performs a query on a random hash. Then I noticed that in some cases the test failed. I tried to analyze the problem from a mathematical standpoint.

Actual implementation for a quick reference while reading some fizzy mathematical explanations :
```cpp
auto itn = bucket;
    auto itp = (bucket == begin()) ? end() : std::prev(bucket);
    while (nodes.size() < count && (itn != end() || itp != end())) {
        if (itn != end()) {
            sortedBucketInsert(*itn);
            itn = std::next(itn);
        }
        if (itp != end()) {
            sortedBucketInsert(*itp);
            itp = (itp == begin()) ? end() : std::prev(itp);
        }
    }
```

So I would like to explain what is bad about this particular piece of code. Let's define longest common prefix of two hashes counting from the most significant bit. Actually,  LCP of two hashes is the 0-indexed position of the most significant set bit in their XOR product.

There is one crucial propery of LCP. Consider three hashes: `s`, `s1`, `s2`. Let `l1 = LCP(s, s1)`, `l2 = LCP(s, s2)`. If `l1 != l2`, then `LCP(s1, s2) = min {l1, l2}`. If `l1 = l2`, then `LCP(s1, s2) > min{l1, l2}`. It's easy to check by visualizing the prefixes on a sheet of paper.

In the routing table we compare other hashes relatively to ours hash. The `i`-th bucket is filled with hashes whose `LCP(s, s') = i` where `s` is the host id's hash and `s'` is the hash in the bucket. And the mentioned LCP property shows that when it comes to finding nearest peers to some arbitrary hash the best bucket to look at is the one whose index equals to `LCP(s, a)` where `s` is again the host id's hash and `a` is the queried hash. In this case `LCP(a, s')` with any `s'` is greater than `LCP(s, a)`. In the other buckets this value is at most the `LCP(s, a)`. Which in terms of XOR metric means that the closest to the queried hash peers are kept in this bucket. 

But what happens when the number of peers in the bucket is less than `K`? We start to iteratively gather peers from the neighbor buckets. And it's where the issue arise. Gathering buckets from the left is no help as LCP with hashes in them is less than LCP with the initially chosen buckets which means that the picked hashes are too far away. In contrast, LCP of `a` with hashes in the buckets to the right side is precisely the `LCP(s, a)` but the MSB of XOR product is the only thing we can extract from LCP. It tells nearly nothing about lower bits which means that just splitting the iterative search into two separate loops is not enough.

Unfortunately, to achieve full mathematical correctness we have to collect all the hashes from the right side and only after that pick the closest ones. It would be a performance disaster to the current implementation that inserts a hash into a result vector in O(n) time complexity. It can be vastly improved with the usage of set with a custom comparator but we still may check `(hash_size - 1) * K` nodes in the worst scenario. This CPU bound does not make a real difference when comparing to the network delays but can create a bottleneck in the energy efficience on a handheld device.

The results of the queries in the current implementation are not that far from the accurate results. And in fully loaded routing tables don't differ at all.

**Comment by ghenry** [comment]
Tested on latest release?

**Comment by aberaud** [comment]
We studied this issue in depth after the initial post. Sorry that we forgot to report our conclusions here.

We basically agree with the writer, that while this problem is real from a mathematical standpoint, in real-life this is unlikely to occur. We decided to keep the current implementation for now, as a reasonable optimisation.

**Comment by SmnTin** [comment]
Thank you for the answer! I consider the issue closed then.
