### ISSUE TITLE
Version mismatch in python bindings

### ISSUE THREAD

**Issue by lgbaldoni** [savoirfairelinux/opendht#537]
Using 2.1.10 on openSUSE Tumbleweed, these are the installed files:
```
opendht-2.1.9-py3.8.egg-info
opendht.cpython-38-x86_64-linux-gnu.so
```

**Comment by ghenry** [comment]
Still an issue on latest?  

Thanks.

**Comment by lgbaldoni** [comment]
> Still an issue on latest?

Apparently it isn't.

**Comment by ghenry** [comment]
Thanks for checking. Closing.
