### ISSUE TITLE
Consider switching http-parser to llhttp

### ISSUE THREAD

**Issue by micwoj92** [savoirfairelinux/opendht#545]
http-parser is not actively maintained and maintainers suggest switching to llhttp
https://github.com/nodejs/http-parser/issues/522

**Comment by aberaud** [comment]
Thanks for the notice,
We shall consider it and start working on migration,
But it would only fully replace http-parser when it's widely packaged in distros.

**Comment by papoteur-mga** [comment]
libgit2 has bundled llhttp.
https://github.com/libgit2/libgit2/issues/6074

**Comment by aberaud** [comment]
OpenDHT moved to llhttp with [v3.2.0](https://github.com/savoirfairelinux/opendht/releases/tag/v3.2.0)
