### ISSUE TITLE
Compiling using musl failed

### ISSUE THREAD

**Issue by terrytw** [savoirfairelinux/opendht#546]
Hello respected devs,

Greetings. First of all, thank you for this amazing project. 

I ran into a problem while trying to compile dhtnode using musl. I am using a x86_64 debian buster system. First I compiled opendht using gcc, and it was successful. Next I tried to compile it using musl, by adding 

`export CC="musl-gcc -static -Os"`

before cmake command. Then I ran 
`cmake -DOPENDHT_PYTHON=OFF -DOPENDHT_PROXY_SERVER=ON -DOPENDHT_PROXY_SERVER_IDENTITY=ON -DOPENDHT_STATIC=ON -DOPENDHT_SHARED=OFF -DCMAKE_INSTALL_PREFIX=/usr ..`
`make -j2`,
before running into this problem:

`/usr/bin/ld: CMakeFiles/dhtscanner.dir/dhtscanner.cpp.o: undefined reference to symbol 'pthread_join@@GLIBC_2.2.5'`
`/usr/bin/ld: //lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line`

I am not very familiar with coding so this might be quite primitive question, still I hope someone can offer a little generous help, it would be much appreciated!

**Comment by terrytw** [comment]
OK I switch to alpine and manage to successfully compile a binary using musl-gcc. 

Now the problem is the tools (dhtproxy dhtchat etc) still requires quite some share libraries like libargon2, libnettle, libhttp-parser. 

Is it possible to compile a single binary that runs out of the box with all the libraries included? Is it possible through some tweak of the makefile?

**Comment by terrytw** [comment]
So I guess I need to compile all the libraries like jsoncpp, gnutls, ncurses, etc, statically to make it work. Too much hassle. 

Hope the official docker can be more updated.

**Comment by ghenry** [comment]
Hi @terrytw 

Did you create a [APKBUILD](https://wiki.alpinelinux.org/wiki/APKBUILD_examples:Simple) file at all for these?

I'm about to start one as I'd like to pull in opendht c lib for my [SentryPeer Docker container](https://github.com/SentryPeer/SentryPeer/blob/main/Dockerfile) and also package [SentryPeer](https://github.com/SentryPeer/SentryPeer) so have a `depends_dev` would be needed.

Thanks,
Gavin.

**Comment by terrytw** [comment]
Hi unfortunately I did not. Also I have given up this project, in part due to the reason that Jami's Android version had some connectivity issue. I was not able to receive notification consistently. I do wonder how it is doing right now with the new swarm feature. Anyway, good luck to you.

**Comment by ghenry** [comment]
Ah, OK. I did one last night https://github.com/savoirfairelinux/opendht/issues/592

What did you use instead?

**Comment by terrytw** [comment]
I switched to telegram. It ticks all the boxes for me in terms of functionality. 

I like the concept of distributed network, but in reality, especially in a censored environment like where I live, it is not ideal. GMS/FMS is not working reliabily, any TCP connection gets cut down in 5 minutes in a mobile environment, etc.

**Comment by ghenry** [comment]
Ah, makes sense. Thanks for the explanation.
