### ISSUE TITLE
Confusion about dhtnode's error message

### ISSUE THREAD

**Issue by marty1885** [savoirfairelinux/opendht#564]
Hi, new to OpenDHT. I've watched a few videos on YouTube, read the original papers by previous project authors and read the documents. It's a cool project. I started a standalone OpenDHT node through the command line, trying to learn how it operates in practice. But every `p` and `g` command I wrote seems to have actually worked. Yet it still printed error messages. Am I doing something wrong?

```
❯ dhtnode -D
OpenDHT node 3a1e636983846a3f4c362b9a0be5b28a2559da7b running on port 41727
 (type 'h' or 'help' for a list of possible commands)

>> p test 123
Using h(test) = a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
Put: failure, took 152 us. Value ID: ad06e91f1b263c16
>> g test
Using h(test) = a94a8fe5ccb19ba61c4c0873d391e987982fbbd3
Get: found 1 value(s) after >> 78.3 us
        Value[id:ad06e91f1b263c16 data(text/plain):"123"]
Get: failure, took 253 us
```

OS: Arch Linux
OpenDHT: 2.1.10 (Built by Arch Linux's maintainers)

**Comment by AmarOk1412** [comment]
you need to have at least one another node to be connected. -b bootstrap.jami.net or another address (if you start a first node, then bootstrap a second node on the first one)

**Comment by marty1885** [comment]
Ah. Thanks
