### ISSUE TITLE
C lib functions mainly return void

### ISSUE THREAD

**Issue by ghenry** [savoirfairelinux/opendht#586]
Hi all,

Would it be advisable to return `int` on most of the applicable `dht_` C lib functions so a user can test for success/failures? The only ones possible to test on our the functions that return a dht type.

Thanks,
Gavin.

**Comment by ghenry** [comment]
For example, I get a core dump if another SentryPeer node is listening on port 4222:

```
terminate called after throwing an instance of 'std::runtime_error'
  what():  Error starting the node: DhtException occurred: Can't bind socket
Aborted (core dumped)
```

I've no way to handle this with:

```
	// https://github.com/savoirfairelinux/opendht/issues/590#issuecomment-1063158916
	dht_runner_config dht_config;
	dht_runner_config_default(&dht_config);

	dht_config.peer_discovery = true; // Look for other peers on the network
	dht_config.peer_publish = true; // Publish our own peer info

	dht_runner *runner = dht_runner_new();
	assert(runner);

	dht_runner_run_config(runner, DHT_PORT, &dht_config);

	config->dht_node = runner;
```

unless I check by opening a socket myself first.

**Comment by aberaud** [comment]
Fixed in https://github.com/savoirfairelinux/opendht/commit/fada8d067dde466a8d947de31ee1e84c68a8044b for dht_runner_run*

most other functions have callbacks that signal failure

**Comment by ghenry** [comment]
Thanks! Is there an example for detecting errors via callback?

**Comment by aberaud** [comment]
`dht_done_cb` would get called with `ok = false` in case of failure.

If the node is not running, the callback will be called synchronously with `ok = false`.

**Comment by ghenry** [comment]
Of course! Thanks. I see that in dhtcnode now.

**Comment by aberaud** [comment]
can we close this issue, or are there other functions that would need to return error codes?

**Comment by ghenry** [comment]
Let's close. I see you're getting ready for 2.4.0! :-) I'll update Alpine and Homebrew when you do. Thanks.
