### ISSUE TITLE
dhtnode and confirming what a value is

### ISSUE THREAD

**Issue by ghenry** [savoirfairelinux/opendht#587]
Hi all,

I've successfully integrated OpenDHT with [SentryPeer](url) now and can see my key is saved and query for the value on my bootstrap node:

```
[1830049.579981] sending 67 bytes of values
g peers
Using h(peers) = 4ba3854d6d8261bcf3b345a7a3527e1f8d66a323
Get: found value (after 3.3173e-05s)
	Value[id:4e0b4a1803ac0692 Data (type: 0 ): 6d795f69705f61646472657373]
>> [1830051.609384] [search 4ba3854d6d8261bcf3b345a7a3527e1f8d66a323 IPv4] refilled search with 0 nodes from node cache
```

How do I confirm with my eyeballs what the value actually is? 

Thanks.

**Comment by ghenry** [comment]
I think this is because I'm using a v1.8 dhtnode on Ubuntu 20 LTS. On a build of master I see:

```
Using h(peers) = 4ba3854d6d8261bcf3b345a7a3527e1f8d66a323
>> Get: found 1 value(s) after 98.2 ms
        Value[id:c1f9052f6e593691 data(text/plain):"my_ip_address"]
```

So all good. Closing.

**Comment by aberaud** [comment]
In older versions, the raw (binary) value was printed as hexadecimal, which is `6d795f69705f61646472657373`. New versions use the mime/type "text/plain" to know it should be shown as text.

Note that this is just what the dht node prints for testing/debugging purposes.
Using the C or C++ API, you can access the full raw data field of the value. It would be possible to store the IP address in binary form.

For instance, to write a received value to a file or socket with the C API:
```c
dht_data_view data = dht_value_get_data(value);
fwrite(data.data, data.size, 1, fd);
```

**Comment by ghenry** [comment]
Thanks for the explanation! I noticed the `p key value` on the cli
truncates too.
