### ISSUE TITLE
benchmark error

### ISSUE THREAD

**Issue by kaldoran** [savoirfairelinux/opendht#59]
Hi,

Here i get an error while testing benchmark for the dht.
I use the following commands : 
`sudo python benchmark.py --pht -t insert` [ From the index branch]

And i got this error : 
http://pastebin.com/CGJTfZsj

Cant locate the error since this commands work before.
I'll try to track back commit and check for change.

Btw, it create the subnetwork ( like "ethdht7@ethdht7.1" )

**Comment by kaldoran** [comment]
Update, that will may help you 
`> cat /dev/net/tun
cat: /dev/net/tun: Le descripteur du fichier est dans un mauvais état`

benchmark seams to left tun into a bad state

**Comment by sim590** [comment]
Yes. I have noticed that a while ago. It somehow fixed itself before and now it's back. I'll have a solution for this soon. As a work around, you can do the following before starting a test:
```sh
$ cd ${OPENDHT_DIR}/python/tools/
$ sudo python ./dht/virtual_network_builder.py -n 8 -4 -6
$ # start your benchmark test...
```

**Comment by kaldoran** [comment]
This does not seams to solve the issue :cry:

**Comment by kaldoran** [comment]
After update of my all system, i've still got the same error :/

**Comment by sim590** [comment]
> This does not seams to solve the issue

Do you mean you cannot use the benchmark or that the error message still appears ? If the latter, it's completely normal for now since there is a bug that doesn't appear to prevent the benchmark to work though.

> Here is a dump of the error :

@kaldoran. The error dump you pasted is in fact an issue, but it shouldn't stop you from using the benchmark as explained in my previous post.

Can you confirm you cannot start your benchmark tests. For e.g., the following should work:
```sh
$ cd ${OPENDHT_DIR}/python/tools/
$ # make sure `ip link` only lists your normal interfaces,
  # otherwise adjust -n <n-iface> to the number of remaining interfaces.
$ sudo python ./dht/virtual_network_builder.py -n $N -r
$ # set $N to the number of clusters you want.
$ sudo python ./dht/virtual_network_builder.py -n $N -4 -6
$ sudo python benchmark.py --performance -t gets -n 32
```

**Comment by kaldoran** [comment]
Since there is now a fix for this problem, I think we can close this issue ;)
No point to keep it open

**Comment by sim590** [comment]
@kaldoran: Actually, I'm referring only to one of the error you mentionned ([the first log](https://github.com/savoirfairelinux/opendht/issues/59#issue-148372673)). The [second comment](https://github.com/savoirfairelinux/opendht/issues/59#issuecomment-211374690) you made still expresses an error that has to be fixed, so I would leave this issue opened.

**Comment by ghenry** [comment]
Still requirement?

Thanks.
