### ISSUE TITLE
dht_runner_shutdown() usage

### ISSUE THREAD

**Issue by ghenry** [savoirfairelinux/opendht#591]
Hi all,

What is this used for? Should I switch to it?

https://github.com/savoirfairelinux/opendht/blob/c59f951e5aa89313460fb5037d382b95550c04d0/c/opendht.cpp#L452

I note it's not used in dhtcnode.c example:

https://github.com/savoirfairelinux/opendht/blob/c59f951e5aa89313460fb5037d382b95550c04d0/tools/dhtcnode.c#L120

I'm just doing the same as `dhtcnode.c`

https://github.com/SentryPeer/SentryPeer/blob/c56f33925eaac6bbce9df65dc5688c42bbebacf6/src/peer_to_peer_dht.c#L383

Thanks,
Gavin.

**Comment by aberaud** [comment]
`dht_runner_shutdown` can be used for graceful shutdown, which will wait for completion of pending operations.

It doesn't need to be used if you don't need to ensure that pending operations (put, get etc.) are completed.

**Comment by ghenry** [comment]
Thanks. Can it replace these three?

```
	dht_runner_cancel_listen(config->dht_node, config->dht_info_hash,
				 config->dht_op_token);
	dht_op_token_delete(config->dht_op_token);
	dht_runner_delete(config->dht_node);
```

**Comment by aberaud** [comment]
no, shutdown will not destroy the dhtrunner. After the shutdown is complete, the runner could be resued with a new call to dht_runner_run*().

**Comment by ghenry** [comment]
OK, thanks. I've been seeing some thread hangs in my signal handler. I'll
add this maybe and debug.
