### ISSUE TITLE
Alpine Linux and Homebrew updated to 2.4.0

### ISSUE THREAD

**Issue by ghenry** [savoirfairelinux/opendht#593]
- https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/32389 
- https://github.com/Homebrew/homebrew-core/pull/97660

Homebrew may need a tweak for C++17

**Comment by aberaud** [comment]
it would be super cool if these packages included python binding tool

**Comment by ghenry** [comment]
I can have a play and add the build options if you have an example of what the cmake bits are? I could also work on a GitHub Action to do this on a release. Maybe best doing manual as I depend on them in my jobs and Docker container.

**Comment by ghenry** [comment]
Alpine PR is accepted - https://gitlab.alpinelinux.org/alpine/aports/-/commit/813f39a989747e3d910f468463582ef4ae85621d

**Comment by aberaud** [comment]
Awesome !

To enable python with cmake: `-DOPENDHT_PYTHON=On`

**Comment by ghenry** [comment]
Will try with both. You'd need python-dev libs?

**Comment by ghenry** [comment]
python3 I  presume :-)

**Comment by ghenry** [comment]
Looks good - https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/32408

**Comment by ghenry** [comment]
We're chatting at the moment about a separate package for python binding, but we've spotted `dhtcluster`. What is that?

https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/32427

**Comment by ghenry** [comment]
Ah, that's because I enabled python.

**Comment by ghenry** [comment]
Any ideas on this:

https://github.com/Homebrew/homebrew-core/actions/runs/2030663576

**Comment by aberaud** [comment]
I just checked other package and new versions of OpenJDK use `fails_with gcc: "5"` :

https://github.com/Homebrew/homebrew-core/blob/master/Formula/openjdk.rb#L44

**Comment by ghenry** [comment]
And we're done! 💯

https://gitlab.alpinelinux.org/alpine/aports/-/commit/be059c4eb84d39e29aff827f7c813048966c0b51

**Comment by tst2005** [comment]
(type in title s/Homwbrew/Homebrew/ )

**Comment by ghenry** [comment]
I've added some comments on the PR, so should hopefully get it updated.

**Comment by ghenry** [comment]
They sorted it for us :)

https://github.com/Homebrew/homebrew-core/commit/87e4a3471a63637eb41d14729901580ef7eff7dc

**Comment by aberaud** [comment]
Awesome!

**Comment by ghenry** [comment]
Description was changed to a C++17 DHT implementation now too.

**Comment by ghenry** [comment]
Morning,

Just doing this https://github.com/SentryPeer/OpenDHT-packaging to keep all these things.

Thanks.
