### ISSUE TITLE
dht_runner_ping() and staying connected to your bootstrap nodes and other nodes

### ISSUE THREAD

**Issue by ghenry** [savoirfairelinux/opendht#595]
Hi @aberaud 

What's the design pattern for keeping the DHT connections alive after you've bootstrapped to some central dhtnodes? Or do I have to worry about that?

Thanks.

**Comment by aberaud** [comment]
Hi :)

After bootstrapping, DHT nodes exchange lists of other nodes with each other and automatically keep an updated list of joinable nodes.

In case connectivity with every known node is lost, the node will fallback to bootstrapping again (with exponential backoff) automatically.

**Comment by ghenry** [comment]
Thanks for the explanation. What is dht_running_ping() for then?

**Comment by aberaud** [comment]
`dht_running_ping` can be used to test the connectivity of a single given node, without adding it to the list of bootstrap nodes. If the node answers, it would still be considered for addition to our node' routing table.

This can be useful for network monitoring purposes, or to join a network without adding bootstrap nodes (if falling back to bootstrapping in case of disconnection is not wanted, for instance).

**Comment by ghenry** [comment]
Understood. Will try to remember if I ever come across this use case. Thanks!
