### ISSUE TITLE
Homebrew and Alpine Linux updates

### ISSUE THREAD

**Issue by ghenry** [savoirfairelinux/opendht#610]
https://github.com/Homebrew/homebrew-core/pull/100083
https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/33614

**Comment by ghenry** [comment]
Both pass CI.

**Comment by ghenry** [comment]
Alpine merged.

**Comment by ghenry** [comment]
Alpine done.

**Comment by aberaud** [comment]
with cmake:` -DOPENDHT_PROXY_CLIENT=On`

**Comment by ghenry** [comment]
Want me to still do Homebrew and alpine?

**Comment by aberaud** [comment]
Is there a way to automate this ? Maybe through Github actions or some other hook ?

**Comment by ghenry** [comment]
Yep, there are different ways. I've been meaning to do it myself on the
"release"/ publish tag. I'll work on it too.
