### ISSUE TITLE
Storage can't be allocated by the default constructor with recent ARM gcc

### ISSUE THREAD

**Issue by pkeroulas** [savoirfairelinux/opendht#63]
Failed to build in fresh Buildroot using arm-buildroot-linux-uclibcgnueabihf-g++ 4.9.3 because of the default constructor issue (ed7a92481c20e0cf0fcb908da4775c6f985a297b). It may have the same problem than gcc 4.9.0. Keeping the explicit constructor helps.
Not sure how to address this.

<pre>
opendht c9a6a90e1b624fd1a351d0458c6880d33223d9d4 Building
PATH="/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/bin:/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/sbin:/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/bin:/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games"  /usr/bin/make -j5  -C /home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/build/opendht-c9a6a90e1b624fd1a351d0458c6880d33223d9d4/
/usr/bin/make  all-recursive
Making all in src
Making all in argon2
make[5]: Nothing to be done for `all'.
/bin/bash ../libtool  --tag=CXX   --mode=compile /home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabihf-g++ -DHAVE_CONFIG_H -I. -I..  -I../include/opendht -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -O3 -std=c++11 -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -O3 -std=c++11 -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -c -o libopendht_la-dht.lo `test -f 'dht.cpp' || echo './'`dht.cpp
libtool: compile:  /home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabihf-g++ -DHAVE_CONFIG_H -I. -I.. -I../include/opendht -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -O3 -std=c++11 -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -Os -O3 -std=c++11 -DMSGPACK_DISABLE_LEGACY_NIL -DMSGPACK_DISABLE_LEGACY_CONVERT -c dht.cpp  -fPIC -DPIC -o .libs/libopendht_la-dht.o
In file included from /home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/include/c++/4.9.3/memory:64:0,
                 from /home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/include/msgpack/cpp_config.hpp:97,
                 from /home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/include/msgpack/pack.hpp:14,
                 from /home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/include/msgpack/object.hpp:14,
                 from /home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/sysroot/usr/include/msgpack.hpp:10,
                 from ../include/opendht/infohash.h:22,
                 from ../include/opendht/dht.h:30,
                 from dht.cpp:28:
/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/include/c++/4.9.3/bits/stl_construct.h: In instantiation of ‘void std::_Construct(_T1*, _Args&& ...) [with _T1 = dht::Dht::Storage; _Args = {dht::Dht::Storage}]’:
/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/include/c++/4.9.3/bits/stl_uninitialized.h:75:53:   required from ‘static _ForwardIterator std::__uninitialized_copy<_TrivialValueTypes>::__uninit_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<dht::Dht::Storage*>; _ForwardIterator = dht::Dht::Storage*; bool _TrivialValueTypes = false]’
/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/include/c++/4.9.3/bits/stl_uninitialized.h:126:41:   required from ‘_ForwardIterator std::uninitialized_copy(_InputIterator, _InputIterator, _ForwardIterator) [with _InputIterator = std::move_iterator<dht::Dht::Storage*>; _ForwardIterator = dht::Dht::Storage*]’
/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/include/c++/4.9.3/bits/stl_uninitialized.h:279:63:   required from ‘_ForwardIterator std::__uninitialized_copy_a(_InputIterator, _InputIterator, _ForwardIterator, std::allocator<_Tp>&) [with _InputIterator = std::move_iterator<dht::Dht::Storage*>; _ForwardIterator = dht::Dht::Storage*; _Tp = dht::Dht::Storage]’
/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/include/c++/4.9.3/bits/stl_uninitialized.h:302:69:   required from ‘_ForwardIterator std::__uninitialized_move_if_noexcept_a(_InputIterator, _InputIterator, _ForwardIterator, _Allocator&) [with _InputIterator = dht::Dht::Storage*; _ForwardIterator = dht::Dht::Storage*; _Allocator = std::allocator<dht::Dht::Storage>]’
/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/include/c++/4.9.3/bits/vector.tcc:423:43:   required from ‘void std::vector<_Tp, _Alloc>::_M_emplace_back_aux(_Args&& ...) [with _Args = {const dht::InfoHash&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long long int, std::ratio<1ll, 1000000000ll> > >&}; _Tp = dht::Dht::Storage; _Alloc = std::allocator<dht::Dht::Storage>]’
/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/include/c++/4.9.3/bits/vector.tcc:101:54:   required from ‘void std::vector<_Tp, _Alloc>::emplace_back(_Args&& ...) [with _Args = {const dht::InfoHash&, std::chrono::time_point<std::chrono::_V2::steady_clock, std::chrono::duration<long long int, std::ratio<1ll, 1000000000ll> > >&}; _Tp = dht::Dht::Storage; _Alloc = std::allocator<dht::Dht::Storage>]’
dht.cpp:1530:35:   required from here
/home/pkeroulas/DEV/BEAGLEBONE/buildroot/output/host/usr/arm-buildroot-linux-uclibcgnueabihf/include/c++/4.9.3/bits/stl_construct.h:75:7: error: use of deleted function ‘dht::Dht::Storage::Storage(dht::Dht::Storage&&)’
     { ::new(static_cast<void*>(__p)) _T1(std::forward<_Args>(__args)...); }
       ^
make[5]: *** [libopendht_la-dht.lo] Error 1
make[4]: *** [all-recursive] Error 1
make[3]: *** [all-recursive] Error 1
</pre>

**Comment by yomgui1** [comment]
I don't have your environment, but this was my test to confirm the patch:
http://coliru.stacked-crooked.com/a/e20d46a26d7d0248

Could you test this code on your buildtool env?

**Comment by pkeroulas** [comment]
I simply picked up your test code and used this similar command line and this is working fine:
<pre>buildroot/output/host/usr/bin/arm-buildroot-linux-uclibcgnueabihf-g++ -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64  -Os  -O3 -std=c++11  -fPIC -DPIC test.cpp</pre

**Comment by aberaud** [comment]
Fixed by https://github.com/savoirfairelinux/opendht/commit/468331093345e718b5d269a71b3c52a2eea4797e
