### ISSUE TITLE
Please consider enabling "Discussions" on this repo.

### ISSUE THREAD

**Issue by n7tae** [savoirfairelinux/opendht#642]
There doesn't seem to be much activity on \#opendht. I've posted questions there that I don't think were ever answered. IRC is *so 80's* and the discussions tab would be much better for a lot of reasons, imho. You can close this issue with prejudice if you disagree.

**Comment by aberaud** [comment]
Done !
https://github.com/savoirfairelinux/opendht/discussions/643
