### ISSUE TITLE
Several problems with the wiki

### ISSUE THREAD

**Issue by n7tae** [savoirfairelinux/opendht#646]
- On the Data-serialization page, the "this page" link point to https://github.com/msgpack/msgpack-c/blob/master/QUICKSTART-CPP.md. It should point to https://github.com/msgpack/msgpack-c/blob/c_master/QUICKSTART-CPP.md.
- In the Filters section of the API-overview, a "coolValueFilter" is defined in an example, but the get() right below it uses "filter".
- In the Queries section of the API-overview, the example starts with "Where w". This confused me for a few seconds. It would be clearer if this were "dht::Where w".
- Further down in API-overview, in the isSatisfiedBy section, some additional comments are needed why "q1.isSatisfiedBy(q3);" is false and vis-versa is true. I'm not sure under what circumstances a get() using dht::Where w("WHERE id=5") produces a different result from dht::Where w("SELECT id WHERE id=5").

**Comment by aberaud** [comment]
I just went through these issues, tell me if it's clearer now :)

**Comment by n7tae** [comment]
Yes. I guess I was thinking of the case where only a single value was stored in a key. "WHERE id=5" and "SELECT id WHERE id=5" would return the same thing, even though they might not be equivalent. Finally, in a likewise manner to the filter example, I think this query example should use "dht::Query" for the three defined objects instead of just "Query". Thanks!

**Comment by aberaud** [comment]
`SELECT id WHERE id=5` would only return the id (5 or nothing if no result) so the only use case for this would be to check if a value exists with a given key+id.

`WHERE id=5` would instead return the whole value, the use case would be to retrieve a specific value for which you already know the key+id.
