### ISSUE TITLE
2.5.3 release was not completed

### ISSUE THREAD

**Issue by chenrui333** [savoirfairelinux/opendht#662]
👋 looks like the 2.5.3 release [was not completed](https://github.com/savoirfairelinux/opendht/actions/runs/4671119352/jobs/8271699254), just create this issue to raise some awareness. 

relates to https://github.com/Homebrew/homebrew-core/pull/128104

**Comment by aberaud** [comment]
Thanks for the heads up,
2.5.4 should be good
