### ISSUE TITLE
Using OpenDHT on Arch Linux: /usr/include/opendht/rng.h:21:10: fatal error: random: No such file or directory

### ISSUE THREAD

**Issue by D3vil0p3r** [savoirfairelinux/opendht#663]
Hello,
I'm trying to build a project using OpenDHT called [SentryPeer](https://github.com/SentryPeer/SentryPeer).

In order to use OpenDHT capabilities, it needs to be compiled by OpenDHT installed on the system. On Arch Linux I do this by installing `opendht` packages. Since SentryPeer leverages on `opendht/opendht_c.h` header file (that I cannot find in OpenDHT src), I replaced it by `opendht.h` in order to make it working also on Arch Linux. The details of my changes are described on https://github.com/SentryPeer/SentryPeer/issues/81

When I compile the project, by adding also `-std=c++11`, I still get the error:
```
/usr/include/opendht/rng.h:21:10: fatal error: random: No such file or directory
   21 | #include <random>
      |          ^~~~~~~~
```
and on my system, on `/usr/include/` folder I don't have any file called `random`. Is it still right that `opendht/rng.h` should use `#include <random>` or it is deprecated?

**Comment by aberaud** [comment]
Hi,
opendht_c.h is part of the c binding, that might not be packeged or built. It's in the c directory
