### ISSUE TITLE
[dhtnet] Missing readline check in build system

### ISSUE THREAD

**Issue by Apteryks** [savoirfairelinux/opendht#675]
Hi,

I'm reporting this here since the issue tracker is not enabled on the project page (https://github.com/savoirfairelinux/dhtnet/).

The build fails if the readline library is not available; it'd be nicer if the build system required it instead.

Thanks!

**Comment by aberaud** [comment]
Hi,
please report dhtnet issues here:
https://git.jami.net/savoirfairelinux/dhtnet/-/issues
Thanks
