### ISSUE TITLE
[dhtnet] tests/connectionManager.cpp hangs in a network-less container

### ISSUE THREAD

**Issue by Apteryks** [savoirfairelinux/opendht#676]
Hi,

The tests/connectionManager.cpp test seemingly hangs in an isolated container, for example when building the package for Guix.

It'd be nice if the build system could disable network-reliant tests when no network is available.

Another thing: when ran outside of the isolated container, the test eventually (after a rather long time) fails and segfaults; see the attached backtrace.
[gdb.txt](https://github.com/savoirfairelinux/opendht/files/12489523/gdb.txt)

Thanks!

**Comment by Apteryks** [comment]
Looking at the backtrace, the bug appears to be in the Jami added code to pjproject (pj_ice_strans_get_grp_lock).

**Comment by aberaud** [comment]
Hi,
please report issues related to dhtnet here:
https://git.jami.net/savoirfairelinux/dhtnet
