### ISSUE TITLE
Cython is not detected by autotools on Archlinux

### ISSUE THREAD

**Issue by zorun** [savoirfairelinux/opendht#69]
On Archlinux, there is no Cython3 package, the package for Python3 is simply called Cython: https://www.archlinux.org/packages/community/x86_64/cython/

This causes autotools to think that cython is not installed, even though it is:

```
checking for a Python interpreter with version >= 3.3... python
checking for python... /usr/bin/python
checking for python version... 3.5
checking for python platform... linux
checking for python script directory... ${prefix}/lib/python3.5/site-packages
checking for python extension module directory... ${exec_prefix}/lib/python3.5/site-packages
checking for cython3... no
configure: WARNING: Cython not found - continuing without python support
```

When changing ```cython3``` to ```cython``` in ```configure.ac```, it gets correctly detected and the Python bindings are built.

I am not sure if this should be fixed in OpenDHT or in Archlinux.  I will also try the cmake-based build system to see if it has the same issue.

**Comment by zorun** [comment]
CMake does not seem to check at all for cython, so building the Python bindings works out of the box.

**Comment by sim590** [comment]
> I am not sure if this should be fixed in OpenDHT or in Archlinux.

AFAIK, python distributing has the standard of providing `python2` and `python3` binaries/links. I personnaly assume, the same is true for cython, so IMO, Archlinux should provide the same sort of binaries/links in its packages. I've just checked and debian packages from Ubuntu do provide `cython3` binary/link.

**Comment by sim590** [comment]
I have opened a support request ticket [here](https://bugs.archlinux.org/task/49545)

**Comment by szotsaki** [comment]
Subscribe. The same issue is with openSUSE (here they call it python3-Cython).
