### ISSUE TITLE
Fail to run the rust example

### ISSUE THREAD

**Issue by lucassdiass** [savoirfairelinux/opendht#707]
The following example for rust, I have this problem when executing cargo run --example dhtnode:
dhtnode: malloc.c:2379: sysmalloc: Assertion `(old_top == initial_top (av) && old_size == 0) || ((unsigned long) (old_size) >= MINSIZE && prev_inuse (old_top) && ((unsigned long) old_end & (pagesize - 1)) == 0)' failed.
Aborted

Does the example work?

**Comment by aberaud** [comment]
Thanks for the report. The issue should be fixed on the master branch
