### ISSUE TITLE
POST via curl doesn't store data

### ISSUE THREAD

**Issue by reactormonk** [savoirfairelinux/opendht#737]
```
$ curl -d '{"hello": 42}' dhtproxy.jami.net:80/2346ad27d7568ba9896f1b7da6b5991251debdf2
{"data":"","id":"3082593856490043100","type":0}

$ curl dhtproxy.jami.net:80/2346ad27d7568ba9896f1b7da6b5991251debdf2                   
{"data":"","id":"3082593856490043100","type":0}

$ curl dhtproxy.jami.net:80/2346ad27d7568ba9896f1b7da6b5991251debdf2/3082593856490043100
# no result
```

**Comment by aberaud** [comment]
Hello,
The value needs to include a "data" field that should be base64-encoded, like in this example:
`curl -d '{"data":"eyJoZWxsbyI6NDJ9"}' dhtproxy.jami.net:80/2346ad27d7568ba9896f1b7da6b5991251debdf2 -v`

**Comment by reactormonk** [comment]
Ah, RTFM :facepalm:, sorry.

**Comment by aberaud** [comment]
No problem, I updated the wiki but the previous documentation was outdated 🤦
Thanks for reporting your issue, it helped improving the docs
