### ISSUE TITLE
Different libraries built with Autotools and CMake

### ISSUE THREAD

**Issue by szotsaki** [savoirfairelinux/opendht#75]
When building with Autotools, the following library files are created:
- libopendht.so.0.0.0 [executable, valid shared library with correct so naming]
- @libopendht.so.0 [link to the former one with one major version]
- @libopendht.so [link to the first one, only useful for development purposes]

These are correct, and the package library also gets its name from the .so: _libopendht0_.

When bulding with CMake, the following is created:
- libopendht.so [executable, with incorrect so naming]
- @symlinks are missing

**Comment by aberaud** [comment]
Thanks for reporting,
Should be fixed by https://github.com/savoirfairelinux/opendht/commit/9615774114abc8b59eb37ef5b68eccbaf3862d34

**Comment by szotsaki** [comment]
This works great, thank you! 

Please, be aware that the Autotools version generates .so with version `0.0.0` while CMake with `0.6.1`.

**Comment by szotsaki** [comment]
Just to be sure: should I open a new ticket regarding the Autotools version difference? Thank you!

**Comment by sim590** [comment]
@szotsaki. You're right, Autotools doesn't have correct version naming. I've reopened this issue.

**Comment by szotsaki** [comment]
With the release of 0.6.2 I rebuilt the package but unfortunately CMake still builds `/usr/lib64/libopendht.so` without any suffix and symlinks.

**Comment by sim590** [comment]
In fact, it wasn't part of the 0.6.2 release. This should be part of a future release where this whole issue is fixed (including autotools). We did release 0.6.2 for covering the critical #73 bug.

**Comment by kaldoran** [comment]
Here is an update :

>  Start with version information of ‘0:0:0’ for each libtool library.
Update the version information only immediately before a public release of your software. 
[...]
> Never try to set the interface numbers so that they correspond to the release number of your package. 

Source : https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html#Updating-version-info

Then a fix could be adding `-release @PACKAGE_VERSION@` line 7 of src/Makefile.am.
Which then going to create libopendht-0.6.X.so ( x = 2 for now ).

Not sure if this is the correct way to deal with that problem.

**Comment by sim590** [comment]
I have looked a little bit more into this. The main issue is that CMake and Libtool have different and conflicting shared object versionning system. If we want consistent version releases, we're kind of forced to do like [this](https://github.com/chewing/libchewing/issues/55).

**Comment by carlwgeorge** [comment]
Please re-open, this is an issue again.  See https://github.com/savoirfairelinux/opendht/pull/95#issuecomment-481768325.

**Comment by aberaud** [comment]
fixed in https://github.com/savoirfairelinux/opendht/commit/683a1117264191fb72f53827ae90cdd813f99e5a

**Comment by carlwgeorge** [comment]
Thanks @aberaud!
