### ISSUE TITLE
crash on dht::crypto::generateIdentity on x64 (Windows)

### ISSUE THREAD

**Issue by skynetto** [savoirfairelinux/opendht#76]
Hi to all,
I'm tryin to compile openDht in Windows and everything goes fine. Everytime I call generatiIdentity function on x64 (no problem on x86) the library crash with illegal instructions at 

`dht::crypto::PublicKey::getId() Row 532	C++`

Here is the call stack

```
>	OpenDhtTest.exe!x86_sha1_update(sha1_ctx * ctx, unsigned __int64 length, const unsigned char * data) Riga 113	C
 	OpenDhtTest.exe!wrap_x86_hash_fast(gnutls_digest_algorithm_t algo, const void * text, unsigned __int64 text_size, void * digest) Riga 340	C
 	OpenDhtTest.exe!_gnutls_hash_fast(gnutls_digest_algorithm_t algorithm, const void * text, unsigned __int64 textlen, void * digest) Riga 114	C
 	OpenDhtTest.exe!_gnutls_get_key_id(gnutls_pk_algorithm_t pk, gnutls_pk_params_st * params, unsigned char * output_data, unsigned __int64 * output_data_size, unsigned int flags) Riga 2646	C
 	OpenDhtTest.exe!gnutls_pubkey_get_key_id(gnutls_pubkey_st * key, unsigned int flags, unsigned char * output_data, unsigned __int64 * output_data_size) Riga 798	C
 	OpenDhtTest.exe!dht::crypto::PublicKey::getId() Riga 532	C++
 	OpenDhtTest.exe!dht::crypto::Certificate::generate(const dht::crypto::PrivateKey & key, const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, std::pair<std::shared_ptr<dht::crypto::PrivateKey>,std::shared_ptr<dht::crypto::Certificate> > ca, bool is_ca) Riga 811	C++
 	OpenDhtTest.exe!dht::crypto::generateIdentity(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, std::pair<std::shared_ptr<dht::crypto::PrivateKey>,std::shared_ptr<dht::crypto::Certificate> > ca, unsigned int key_length, bool is_ca) Riga 777	C++
 	OpenDhtTest.exe!dht::crypto::generateIdentity(const std::basic_string<char,std::char_traits<char>,std::allocator<char> > & name, std::pair<std::shared_ptr<dht::crypto::PrivateKey>,std::shared_ptr<dht::crypto::Certificate> > ca, unsigned int key_length) Riga 788	C++
 	OpenDhtTest.exe!main(int argc, char * * argv) Riga 265	C++
```

```
+		ctx	0x000000000021da20 {state=0x000000000021da20 {0x67452301, 0xefcdab89, 0x98badcfe, 0x10325476, 0xc3d2e1f0} ...}	sha1_ctx *
+		data	0x0000000000402200 "0‚\x2\"0\r\x6\t*†H†÷\r\x1\x1\x1\x5"	const unsigned char *
		i	0xcccccccc	unsigned int
		length	0x0000000000000200	unsigned __int64
+		octx	{h0=0x67452301 h1=0xefcdab89 h2=0x98badcfe ...}	<unnamed-tag>
		res	0x0000000000000026	unsigned __int64
		t2	0x00000008	unsigned int
```

The problem lies down to gnutls sha1_block_data_order function wich is compiled in assembly.
I saw in the source that two versions of assembly are used (x86 and x64). The x86 version works fine, the x64 dont.
I've tried to reconstruct the x64 version with openssl, but have always the same problem (illegal istruction at: sha1msg1 xmm4,xmm5 assembler instruction.)

Do you guys have the same issue?
Thanks in advance

**Comment by aberaud** [comment]
Seems to be a Visual Studio (VSYASM) bug, which compiles Intel Goldmont specific instructions for other x64 targets.

**Comment by atraczyk** [comment]
In the Windows x86_64 platform configurations of GnuTLS, you must exclude the ASM_X86 preprocessor definition, and it'll work without SSSE3 crypto acceleration.

**Comment by skynetto** [comment]
It's working. Thanks

**Comment by iain17** [comment]
Hey there @skynetto. Sorry to open this thread. I'm trying to compile this project on Windows with CMake. However, I can't seem to get it working. Could you perhaps tell me how you got all the sub-dependencies installed? I'd like to eventually have the .lib files so I can use it in my own C++ project.

Did you perhaps use mingw to compile it? If so how?
