### ISSUE TITLE
OpenDHT won't build with the system's argon2 library

### ISSUE THREAD

**Issue by aviau** [savoirfairelinux/opendht#83]
Reading the CMakeLists.txt seemed to indicate that OpenDHT won't build with the system's argon2 library.

Could it be updated to look for the system libraries first?

**Comment by aberaud** [comment]
Argon2 is not yet included in any real distribution, and the official Argon2 repo has no actual build system (their handmade makefile doesn't even have an "install" target).

Until a serious Argon2 distribution exists, we should keep using the in-tree copy.

**Comment by aviau** [comment]
>  in any real distribution

It is in Debian and Ubuntu...

I had to patch around your buildsystem to have it work in Debian:

```
 tDescription: Use Debian's argon2 library
Bug: https://github.com/savoirfairelinux/opendht/issues/83
Author: Alexandre Viau <aviau@debian.org>
Last-Update: 2016-06-27

--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -51,12 +51,6 @@
     src/network_engine.cpp
     src/securedht.cpp
     src/dhtrunner.cpp
-    src/argon2/argon2.c
-    src/argon2/core.c
-    src/argon2/blake2/blake2b.c
-    src/argon2/thread.c
-    src/argon2/encoding.c
-    src/argon2/ref.c
 )
 
 list (APPEND opendht_HEADERS
@@ -110,7 +104,7 @@
     if (OPENDHT_LTO)
         target_link_libraries(opendht-static -flto -fuse-linker-plugin)
     endif ()
-    target_link_libraries(opendht-static gnutls nettle)
+    target_link_libraries(opendht-static gnutls nettle argon2)
     install (TARGETS opendht-static DESTINATION ${CMAKE_INSTALL_LIBDIR})
 endif ()
 
--- a/src/crypto.cpp
+++ b/src/crypto.cpp
@@ -27,7 +27,7 @@
 #include <nettle/gcm.h>
 #include <nettle/aes.h>
 
-#include "argon2/argon2.h"
+#include "argon2.h"
 }
 
 #include <random>
--- a/tools/CMakeLists.txt
+++ b/tools/CMakeLists.txt
@@ -3,9 +3,9 @@
 add_executable (dhtscanner dhtscanner.cpp tools_common.h)
 add_executable (dhtchat dhtchat.cpp tools_common.h)
 
-target_link_libraries (dhtnode LINK_PUBLIC gnutls readline)
-target_link_libraries (dhtscanner LINK_PUBLIC gnutls readline)
-target_link_libraries (dhtchat LINK_PUBLIC gnutls readline)
+target_link_libraries (dhtnode LINK_PUBLIC gnutls readline argon2)
+target_link_libraries (dhtscanner LINK_PUBLIC gnutls readline argon2)
+target_link_libraries (dhtchat LINK_PUBLIC gnutls readline argon2)
 
 if (OPENDHT_SHARED)
 	target_link_libraries (dhtnode LINK_PUBLIC opendht)
```

**Comment by aviau** [comment]
Also, the package seems to build in a sane way: https://sources.debian.net/src/argon2/0~20160406-2/debian/rules/

**Comment by aberaud** [comment]
Nice to see it started to be included in Debian. It's still not in any stable release yet.

Since Argon2 doesn't provide a proper way to build and install and is not in distros yet, it would be an additional friction for new developers (msgpack does provide a proper build system and yet it's a mess for which many users complained).

If there is a conflict (that would cause a build failure) with a system-installed version of argon2 that's a bug that should be fixed.

**Comment by aviau** [comment]
> If there is a conflict (that would cause a build failure) with a system-installed version of argon2 that's a bug that should be fixed.

There is none, but can we just add a feature that allows for using the system's version without having to patch the CMakeList and source files? I am sure we can add a flag.

**Comment by aberaud** [comment]
Argon2 is currently discussing about using autotools or cmake.
I suggest to wait until they make a decision.

Then we can remove argon2 sources from OpenDHT, update docs, include argon2 in Ring contrib etc.

If Argon2 choses _status quo_ we will keep the sources for now and add a build flag (as suggested).

**Comment by aviau** [comment]
Then shoud we re-open this issue until this is sorted out?

**Comment by aviau** [comment]
@aberaud ping

**Comment by YogSottot** [comment]
Besides Debian/Ubuntu it is also available for the openSUSE, Gentoo, Arch Linux

**Comment by aberaud** [comment]
Release [1.3.1]( https://github.com/savoirfairelinux/opendht/releases/tag/1.3.1 ) adds support for system argon2 (enabled by default).
