### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by aviau** [savoirfairelinux/opendht#86]
Please release 1.0.

You may think that it is best to wait for a stable API to release 1.0, but it is not. This only makes it harder for users to track breaking changes in the pre-1.0 phase. There is no downside to releasing 1.0 now. The only effect may be higher version numbers.

See http://semver.org/ on this:
> How do I know when to release 1.0.0?

> If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you’re worrying a lot about backwards compatibility, you should probably already be 1.0.0.

I would love to see the major version bumped every time there is a breaking change in OpenDHT, this would make it much easier to maintain OpenDHT in distributions.

**Comment by kaldoran** [comment]
So here we are need to do the following : 
- [ ] Bump up version of CMakeList.txt
- [ ] Bump up version of autotool
- [ ] Test all part of OpenDHT
- [ ] Check Wiki
