### ISSUE TITLE
DhtRunner does not allow to give the time_point

### ISSUE THREAD

**Issue by kaldoran** [savoirfairelinux/opendht#91]
While the Dht allow us to give the time_point that we need to put a value into the Dht, the DhtRunner does not allow that.

Shouldn't be a way to put the data using the DhtRunner and add a time_point value ?

**Comment by kaldoran** [comment]
@sim590 and @aberaud i need you there and link that to issue #61 where i need such things

**Comment by sim590** [comment]
So you're asking if the `DhtRunner` API should have function signatures for setting a time of creation for a value to put on the DHT. I'm not sure there'd be a good use case for this and that the `DhtRunner` should provide this. This is more a kind of a low level API. You would have to directly use the `Dht` or `SecureDht` class, but since the `Pht` class model uses a `DhtRunner` instance, then may be the logical thing to do would be to make `Pht` a `friend` of `DhtRunner` so that you could do:

**Comment by kaldoran** [comment]
Thanks for the answer Simon, thats why i was looking for. 
But there is no signature into the SecureDht where you can use a time_point ( or at least i didnt saw it ).
I'm going to follow this : 
`dht_->dht_->put(/* SecureDht::put signature parameters */ );`
Thanks.

I think we can now close this issue.

**Comment by sim590** [comment]
@kaldoran: `SecureDht` is a child class of `Dht`, so it inherits from the `Dht` functions you are looking for.

**Comment by kaldoran** [comment]
@sim590 ok, thanks i will look into that :D 
I will do that and then make a break on the complet node splitting since there is some issue with the merge ( the split look good for the moment )

**Comment by aberaud** [comment]
Hi,

If PHT actually needs this feature, other OpenDHT users might also need it, so it may be relevant to expose the feature in public APIs. PHT is built on top on the DHT so this approach would be cleaner.

Using the private dht_ object directly is not possible as it would create thread safety issues.

**Comment by sim590** [comment]
> Using the private dht_ object directly is not possible as it would create thread safety issues.

Yes! Oops ;)

> If PHT actually needs this feature, other OpenDHT users might also need it, so it may be relevant to expose the feature in public APIs. PHT is built on top on the DHT so this approach would be cleaner.

Yes. I was actually hesitating while giving advice. Considering the thread safety issue, I think this is clear that the `friend` design is not an option.

**Comment by kaldoran** [comment]
I forget to reopen this one :D now its done
