### ISSUE TITLE
[DhtScanner] doesn't compile on LLVM 7.0.2

### ISSUE THREAD

**Issue by sim590** [savoirfairelinux/opendht#92]
As Travis [pointed out](https://travis-ci.org/savoirfairelinux/opendht/builds/143735553) when checking errors in #79, DhtScanner doesn't compile on LLVM. However, everything else compiles, so this is not high priority. The code is now merged in master. I'm highlighting the issue here so that it appears to be a known issue.

**Comment by kaldoran** [comment]
Isn't this https://github.com/savoirfairelinux/opendht/commit/f474f6499bbe95f5b6f2a82a96b50dfe81488b08 patch correct the bug ?

**Comment by sim590** [comment]
Actually, f474f64 gets rid of some warnings, but it doesn't resolves the errors.

**Comment by sim590** [comment]
This issue seems not to apply for LLVM 7.3.0 (Apple version) which is one of the latest release at this point. This bug report may fade in the dark space of forgotten history... Sometime.

**Comment by kaldoran** [comment]
I Keep this one open but i link this PR https://github.com/savoirfairelinux/opendht/pull/94

**Comment by aberaud** [comment]
Fixed since we use a decent LLVM/Clang version in Travis with Docker
