### ISSUE TITLE
[Dht] Optimize search

### ISSUE THREAD

**Issue by kaldoran** [savoirfairelinux/opendht#96]
Optimize search by using NodeCache .
That will speed up all search and should optimize network usage.

**Comment by kaldoran** [comment]
Update here : 
I should update `Dht::bootstrapSearch` of dht.cpp [line : 1238] to include cache.

**At the end on modification** : 
Dht::bootstrapSearch -> network_engine [cache] -> NodeCache [Choose iv4 or v6]-> NodeMap -> function which choose the node (or list of node)

Sound good for you @sim590  or @aberaud ?

**Comment by sim590** [comment]
What you said on IRC. ¯\_(ツ)_/¯
