### ISSUE TITLE
0.6.2 filenames in 0.6.3

### ISSUE THREAD

**Issue by szotsaki** [savoirfairelinux/opendht#99]
The compiled `0.6.3` version has the following file names in its installation path:
* /usr/lib64/python3.4/site-packages/opendht-**0.6.2**-py3.4.egg-info
 * In PKG-INFO inside: `Version: 0.6.2`
* /usr/lib64/pkgconfig/opendht.pc: `Version: 0.6.2`
* /usr/lib64/libopendht.so.**0.6.2**

The used Make generator was CMake.

**Comment by kaldoran** [comment]
Thanks for the report, since that someone ( @sim590 :D ) forgot to bump up the version number into CMake.

**Comment by sim590** [comment]
Alright. beca53a6 fixed it.

**Comment by szotsaki** [comment]
I think this happened again between 1.0.1 and 1.0.2  :).

**Comment by sim590** [comment]
@kaldoran. I think I need your list of things to do before releasing a version.

**Comment by sim590** [comment]
@szotsaki. It's fixed again. I think I will end up by remembering this sometime. :)

**Comment by szotsaki** [comment]
Thank you; now it's building! :)

**Comment by kaldoran** [comment]
@sim590 we should really write this "things to do before new release" :D
I will write them somewhere soon then :)
